### ISSUE TITLE
AttributeError: module 'geatpy' has no attribute 'crtfld'

### ISSUE THREAD

**Issue by mrbluer** [geatpy-dev/geatpy#1]
运行quickstart_demo后提示：
FieldD = ga.crtfld(ranges,borders,precisions,codes,scales) # 调用函数创建区域描述器

AttributeError: module 'geatpy' has no attribute 'crtfld'

**Comment by geatpy-dev** [comment]
Something wrong may happened with your geatpy when installing. Please contact our engineer(QQ: 784068941) for further help. Thank you.

**Comment by ZibinPan** [comment]
非常感谢你的反馈。经过检查发现2018.08.27放在github上的Geatpy出现了文件缺失，原因查明是github的.gitignore设置失误造成的漏放了lib64相关的库文件。现在2018.08.28已修复该问题。其他朋友若在2018.08.27从github下载安装过Geatpy的(原先用pip在线安装方式安装的不会出现该问题)，请卸载重装，或者重新在github下载，并用管理员打开windows控制台运行pip setup.py install进行覆盖安装。感谢！
