### ISSUE TITLE
如何設定0,1變數在目標式當中?

### ISSUE THREAD

**Issue by jdx0813** [geatpy-dev/geatpy#100]
您好~我正在建立一個雙目標的資源分配模型，
模型中有30個變數(x1~x30)，皆為要分配的資源，
目標式為成本及時間的最小化，
時間的目標式想設成y*單位運送時間後相加
y為01變數，當x1+x2+x3=0時(代表該資源不送往該地)
讓y為0後再返回目標式做時間的累計，
我目前的做法是先設一個np.zeros的矩陣，
再使用np.select的方式取代zeros的原矩陣；
但是執行main.py的時候一直報錯:IndexError: too many indices for array
請問我能否實現這個目標式?或是有什麼方法能幫助我

**Comment by geatpy-dev** [comment]
@jdx0813 您好~这个您可以找一下技术员：QQ 1061655504，他会协助您处理建模中碰到的代码问题~

**Comment by geatpy-dev** [comment]
据悉该问题已得到解决，欢迎后续继续发issue提问噢！
