### ISSUE TITLE
NDSet.Obj中的点似乎不全是最终输出的pareto前沿？

### ISSUE THREAD

**Issue by itaoxiaoran** [geatpy-dev/geatpy#101]
通过程序自动画图，画出来的Pareto点是这样的：
![image](https://user-images.githubusercontent.com/35984267/79324835-c94c2080-7f42-11ea-80cb-5374b73a5b85.png)
而我自己，通过
plt.plot(NDSet.ObjV[:, 0], NDSet.ObjV[:, 1], 'ro')
画出来的点是这样的：

![1586944923(1)](https://user-images.githubusercontent.com/35984267/79325438-c00f8380-7f43-11ea-8f7f-d0aff2a3ec83.png)

看得出来，程序自动画的是我自己画的点的更靠近原点的那一些、我自己画的图的点还是存在支配与被支配关系的？
这是何原因呢？说明优化还没有结束吗？但时间已经相当长了，我可能决定：“那就这样算了吧”

我如何提取程序自动画出来的pareto点呢？画图代码是.pyd文件，似乎看不到源码

**Comment by geatpy-dev** [comment]
@itaoxiaoran 您好~您把github里面的Algorithm.py的内容替换掉本地的Algorithm.py，上述问题即可解决。这个问题源于以前的Algorithm.py中的finishing()函数错误地返回了population，正确应该是返回NDSet。

**Comment by itaoxiaoran** [comment]
你好，我是在你们回滚**之后**更新到2.4.0版本了，我是直接下载现在github里的文件，还是重新pip？

**Comment by itaoxiaoran** [comment]
我发现你们algorithm.py的更新是25天之前，而我是前几天安装的2.4.0版本

**Comment by geatpy-dev** [comment]
@itaoxiaoran pip安装的2.4.0是两个月前的，它存在这个问题。需要把github上面的Algorithm.py拷贝下来覆盖掉pip安装的同名文件。或者直接下载整个github源码进行编译安装。另外很快就要发布新版了，届时此问题也会得到解决。

**Comment by geatpy-dev** [comment]
@itaoxiaoran 2.5.0预览版发布啦！执行pip install geatpy==2.5.0rc0即可解决上述问题~

**Comment by geatpy-dev** [comment]
该问题已得到妥善解决，欢迎后续继续发issue提问噢！
