### ISSUE TITLE
RuntimeError: error in ndsortESS: CV and ObjV disagree

### ISSUE THREAD

**Issue by jdx0813** [geatpy-dev/geatpy#102]
请问出现这行错误是因为我设置的约束条件过多吗?
如果是的话，要怎么将我原先的约束条件做调整会比较适当

**Comment by geatpy-dev** [comment]
@jdx0813 您好！这说明CV和ObjV在格式上不匹配。两者均需要是2维的Numpy ndarray矩阵，并且两者的行数要相等（详见《[Geatpy数据结构](http://geatpy.com/index.php/2019/07/28/2-geatpy%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/)》文档）。您可以在自定义目标函数末尾print(CV.shape)和print(ObjV.shape)输出两者的规格，进而修改确保两者的行数一致。

**Comment by jdx0813** [comment]
好的，感谢我再多尝试一会

**Comment by jdx0813** [comment]
print(pop.CV.shape)->(60, 4)
print(pop.ObjV.shape)->(780,)
Traceback (most recent call last):
  File "C:\Users\LAB432\Desktop\pytest\Test\Supply\main.py", line 18, in <module>
    NDSet = myAlgorithm.run()
  File "C:\Users\LAB432\AppData\Roaming\Python\Python35\site-packages\geatpy\templates\moeas\nsga2\moea_NSGA2_templet.py", line 92, in run
    [levels, criLevel] = self.ndSort(self.problem.maxormins * population.ObjV, NIND, None, population.CV) # 对NIND个个体进行非支配分层
ValueError: operands could not be broadcast together with shapes (2,) (780,)

**Comment by jdx0813** [comment]
请问我这样是目标函式的问题吗?

**Comment by geatpy-dev** [comment]
是的，CV是60行的时候，ObjV也要有60行。另外最好print(pop.sizes)看一下个体数是不是60，如果不是60，那么CV也有问题。

**Comment by geatpy-dev** [comment]
如果后续还有问题欢迎继续发issue提问噢！这里就把该问题关闭了。
