### ISSUE TITLE
种群初始化问题需符合特定条件的约束问题

### ISSUE THREAD

**Issue by jdx0813** [geatpy-dev/geatpy#103]
不好意思又来打扰了...
我在编码过程中遇上种群初始化需符合特定条件的约束，
昨天参考过#99的状况，但我的问题不一样，
有6个均为介于0至10的实数变数(x1-x6)，
生成过程中，x1+x3需等于x4+x6，且x1+x2+x3需等于x4+x5+x6，
请问我能否于决策变量上下界设置?
或是能否于约束条件中进行调整(据我了解，约束条件无法输入等号)

**Comment by geatpy-dev** [comment]
@jdx0813 您好！这个属于等式约束，可以看一下[这篇文档](http://geatpy.com/index.php/2019/07/28/4-%E8%BF%9B%E5%8C%96%E7%AE%97%E6%B3%95%E6%A8%A1%E6%9D%BF/)的第4小节。

**Comment by itaoxiaoran** [comment]
我说一个我平时的小技巧，可能不对，欢迎指正
一般情况下，等式约束太多，求解效果可能不佳
比如你x1+x3==x4+x6的约束条件
你可以不这么直白的建模
你可以这样：
提取种群里面这几个变量，然后算一下：x1+x3-x4的值，这个差值就是x6的值，你x6肯定是有上下限的对吧？你就判断一下，如果x6在你的上下限区间里面，你就令这个种群的CV矩阵为任意小于等于0的数，如-1，如果不是，你就算一算这个差值距离你的上限或下限的差距是多少（正数），然后令CV矩阵的这个种群的这个值为你算出来的差距。
实测有效~

**Comment by itaoxiaoran** [comment]
我之前也提过这个问题，后来我觉得如果要满足一开始的种群就需要满足某些约束，需要调用一下商用求解器，求一个“无目标”优化问题，即把你的所有约束去优化，或者你规模不大就枚举？但这样感觉有些麻烦了，你试试我的方法~

**Comment by jdx0813** [comment]
@itaoxiaoran 感谢大大提供的方法，我晚些时候会尝试看看

**Comment by geatpy-dev** [comment]
该问题已超过最长期限，特此关闭。
