### ISSUE TITLE
可否分享下moead模版的代码，我自己写的总是收敛很慢，不知道哪里出了问题

### ISSUE THREAD

**Issue by lepecoder** [geatpy-dev/geatpy#104]

**Comment by geatpy-dev** [comment]
@lepecoder 您好！我帮您想想办法，预计最快本学期结束后能拿到这个代码。据我了解，目前网上发行的诸多EA平台、框架等里面的MOEA/D都没有复现出论文所展示的那么好的效果和性能。在此期间，您不妨试一下用论文里面的参数设置，来评估复现的情况。

**Comment by geatpy-dev** [comment]
@lepecoder 好消息好消息！MOEA/D的geatpy算法模板已被老板批准发行，应该会在2.5.0正式版中和大众见面~

**Comment by lepecoder** [comment]
@geatpy-dev   谢谢，期待ing

**Comment by lepecoder** [comment]
> @lepecoder 好消息好消息！MOEA/D的geatpy算法模板已被老板批准发行，应该会在2.5.0正式版中和大众见面~

谢谢，期待ing~~

**Comment by geatpy-dev** [comment]
> > @lepecoder 好消息好消息！MOEA/D的geatpy算法模板已被老板批准发行，应该会在2.5.0正式版中和大众见面~
> 
> 谢谢，期待ing~~

OK了，已上传更新。
