### ISSUE TITLE
目前只有SEGA支持多种群进化算法嘛？针对多目标的算法如NSGA-2目前可以使用嘛？

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#106]
你好，我看到在template一页中，只有soea_multi_SEGA_templet.py 其中一个带有multi的字样，没有看到moea中哪个template带有multi字样。请问目前是否有什么多目标算法模板可以支持多种群进化算法？如当前不支持，这类多目标算法多种群进化算法模板的开发是否在计划中呢？
谢谢！

**Comment by geatpy-dev** [comment]
@xrzalreadytaken 是哒，之前只给出了一个模板用来展示如何将单一种群的进化算法改成多种群的进化算法。可以结合[这篇文档](http://geatpy.com/index.php/2020/02/10/6-%E5%A4%9A%E7%A7%8D%E7%BE%A4%E8%BF%9B%E5%8C%96%E4%BC%98%E5%8C%96/)，根据需要自定义类似的多种群进化算法模板。目前工作重心发生了变化，未来数月应该不会上传新的算法模板。

**Comment by geatpy-dev** [comment]
该问题已达最长期限，这里就先关掉了。
