### ISSUE TITLE
if的判断式能否运用在参数的计算上

### ISSUE THREAD

**Issue by jdx0813** [geatpy-dev/geatpy#107]
大大好，我现在遇上了另一个问题，
我将6个成本参数各自乘上预设的6个数字后，
需要进行判断是否有高于5万，
如果没有就执行(Yi=1)，有就不执行(Yi=0)
但是每当我使用if判断式就会出现:
"ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"
请问if判断式是否无法使用在aimFunc里面?

**Comment by geatpy-dev** [comment]
@jdx0813 您这个是numpy语法问题，因为传入aimFunc()的种群对象的Phen属性是种群表现型矩阵，意味着它是一个2-D Numpy ndarray。熟知这个数据结构，编程就不会出问题。如果实在不熟悉numpy的矩阵运算，或者模型本身不支持矩阵计算，可以用循环把Phen拆成一行一行，逐个计算各个个体的目标函数值，最后拼在一起即可。

**Comment by jdx0813** [comment]
感谢大大的解说，那我还有两个问题；
若我将是否执行的Yi设置成一个Numpy array，
那我要设置1-D还2-D才能带入目标式中?
另外，我main.py中设置NIND = 60，
那么执行过程中，是先完成60个群体的诞生再执行Yi的判断，
还是先每诞生1个群体就执行一次Yi的判断式?

**Comment by geatpy-dev** [comment]
@jdx0813 可以抛开进化算法不看来单独设计aimFunc()，比如在一个练习脚本里面独立创建一个aimFunc()函数，然后定义一个Phen矩阵（每行代表一组解向量），传给aimFunc()，只要让它计算出满足Geatpy数据结构的目标函数值矩阵ObjV（每行代表一组目标值）即可。

**Comment by jdx0813** [comment]
大大不好意思，我尝试了几天还未能成功，
对于定义Phen矩阵我不太熟悉，能否给个范例，
或是能教教怎么拆解Phen逐个执行后合并吗?

**Comment by geatpy-dev** [comment]
@jdx0813  您好！[这个案例](https://github.com/geatpy-dev/geatpy/blob/master/geatpy/demo/soea_demo/soea_demo3/MyProblem.py)就有讲述如何用循环来求每个个体的目标函数值了呢。

**Comment by hjnnjh** [comment]
@jdx0813 你将参数定义为一个一维的ndarray数组， 直接`(Params * Phen).sum(axis=1).reshape(-1, 1)`就能得到目标函数值矩阵ObjV了，numpy里很简单的矩阵乘法。我倒是觉得快速入门里的把每一列取出来的操作有点麻烦了。

**Comment by jdx0813** [comment]
感谢大大，目标式的问题已经解决了；
想请问一下，我用循环求每个个体目标函数值后，
约束条件该用罚函数法还是可行性法则?
另外，我是否也要利用循环去计算约束条件呢?

**Comment by geatpy-dev** [comment]
@jdx0813 约束条件既可以用罚函数法也可以用可行性法则。是否要用循环去构建违反约束程度矩阵取决于模型是否支持利用矩阵运算同时计算所有个体的约束。

**Comment by jdx0813** [comment]
了解，谢谢大大
