### ISSUE TITLE
pypi中的版本没有更新

### ISSUE THREAD

**Issue by BlackJocker1995** [geatpy-dev/geatpy#109]
soea_demo10 中使用到了2.5版本的函数, 目前无法正常运行.
在pypi中查看其版本仍为2.4, 希望同步更新.

**Comment by geatpy-dev** [comment]
网站公告里面有讲2.5.0预览版的pip安装方法噢，直接执行pipe install geatpy所安装的是2.4.0呢。

**Comment by BlackJocker1995** [comment]
看到具体内容了, 谢谢.
