### ISSUE TITLE
能否得到源代码而不是pyd

### ISSUE THREAD

**Issue by l976308589** [geatpy-dev/geatpy#11]
看到您的核心代码是pyd格式，能否得到py文件

**Comment by 1061655504** [comment]
> 看到您的核心代码是PYD格式，能否得到PY文件

相关代码可以在日后论文收录后在引用处链接查看。

**Comment by liuaer** [comment]
请问什么时候能够看见.pyd中的代码，我对里面怎么写的，真的很感兴趣。

**Comment by liuaer** [comment]
相关代码可以在日后论文收录后在引用处链接查看-----这句话的意思是你们打算论文发表之后再公布代码？
