### ISSUE TITLE
决策变量上界为正无穷时ub行向量如何定义？

### ISSUE THREAD

**Issue by hjnnjh** [geatpy-dev/geatpy#110]
大佬们好，如题。

**Comment by geatpy-dev** [comment]
@hjnnjh 进化算法里面决策变量空间是要有限的，变量上下界均需要为实数，不能设置为无穷。

**Comment by hjnnjh** [comment]
> @hjnnjh 进化算法里面决策变量空间是要有限的，变量上下界均需要为实数，不能设置为无穷。

我设置一个变量可能取到的范围可以吗？

**Comment by geatpy-dev** [comment]
@hjnnjh 可以哒

**Comment by hjnnjh** [comment]
@geatpy-dev 大佬，我还有一个问题，等式约束怎么表示？文档里说的可行性法则吗？

**Comment by geatpy-dev** [comment]
@hjnnjh [这个文档](http://geatpy.com/index.php/2019/07/28/4-%E8%BF%9B%E5%8C%96%E7%AE%97%E6%B3%95%E6%A8%A1%E6%9D%BF/)里面有介绍，不过建议尽量用恒等变换来降维消除等式约束。

**Comment by hjnnjh** [comment]
@geatpy-dev 谢谢大佬

**Comment by hjnnjh** [comment]
@geatpy-dev 大佬，我在使用NSGA-II算法模板求解时，将`drawing`属性赋值1，但是最后画出的图上没有数据点，`ObjV`的值是没问题的，这是怎么回事啊？

**Comment by hjnnjh** [comment]
@geatpy-dev ![image](https://user-images.githubusercontent.com/37699150/80480514-68313d80-8983-11ea-9023-68ac788bda46.png) 
![image](https://user-images.githubusercontent.com/37699150/80480558-78491d00-8983-11ea-805f-12fd00c70a63.png) 这里只取了最优个体中第一个个体的目标函数值

**Comment by hjnnjh** [comment]
@geatpy-dev 我没找到`Plot`相关函数在哪定义的。。。

**Comment by geatpy-dev** [comment]
@hjnnjh 您看看是不是不满足约束条件。算法模板在绘图时会排除非可行解，详见Algorithm.py。

**Comment by hjnnjh** [comment]
@geatpy-dev 啊这。。。每一代所有个体都不满足约束条件，是我约束条件太多了吗，之前用相同的约束条件做线性规划都没问题啊。。。

**Comment by geatpy-dev** [comment]
经典进化算法处理复杂约束尤其是含大量等式约束是比较鸡肋的，需要尽可能消掉等式约束；如果问题规模不大，但包含复杂约束尤其是大量的等式约束，反倒建议用传统精算。

**Comment by hjnnjh** [comment]
@geatpy-dev 谢谢大佬，打算换个思路了
