### ISSUE TITLE
soea_demo10案例报错call_aimFunc 函数里面    self.evalsNum += pop.sizes # 更新评价次数  TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by yijiecaoming** [geatpy-dev/geatpy#112]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by geatpy-dev** [comment]
@yijiecaoming 您用的是什么版本？我这里使用2.5.0进行测试并未发现上述问题呢。

**Comment by yijiecaoming** [comment]
您好，geatpy 版本也是2.5.0，运行时报错，我看了call_aimFunc 函数里面&nbsp; &nbsp; self.evalsNum初始为None，然后运行时报错TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int' ，如果把None改为0的话，做出来的图像的坐标宽度不是0,1,2...整数情况，而是刻度为0,2.5,5,7.5....




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"geatpy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月7日(星期四) 上午8:47
收件人:&nbsp;"geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送:&nbsp;"范猛"<2594809931@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [geatpy-dev/geatpy] soea_demo10案例报错call_aimFunc 函数里面    self.evalsNum += pop.sizes # 更新评价次数  TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int' (#112)





 
@yijiecaoming 您用的是什么版本？我这里使用2.5.0进行测试并未发现上述问题呢。

**Comment by geatpy-dev** [comment]
@yijiecaoming 了解。您添加一下QQ 1061655504，将会有工作人员帮您远程处理上述问题。

**Comment by geatpy-dev** [comment]
据悉问题已解决。原因是soea_demo10为v2.5.0正式版的新增案例，案例的main.py里的一项操作不向下兼容。
