### ISSUE TITLE
moead里切比雪夫距离的计算

### ISSUE THREAD

**Issue by lepecoder** [geatpy-dev/geatpy#113]
我想在moead模版的基础上实现meoad-dra(The Performance of a New Version of MOEA/D on CEC09 Unconstrained MOP Test Instances )，发现ea.tcheby计算的切比雪夫距离和我自己计算的值不一样，是否ea.tcheby做了规格化或是其它类似的修改？

**Comment by geatpy-dev** [comment]
@lepecoder 您好！如果没有给ea.tcheby()传入违反约束程度矩阵CV的话，是直接按照Qingfu Zhang, Hui Li. MOEA/D: A Multiobjective Evolutionary Algorithm Based on Decomposition[M]. IEEE Press, 2007. 这篇文章里面的公式计算的呢。如果传入了CV，那么就先用可行性法则，然后再计算目标聚合。

**Comment by lepecoder** [comment]
找到原因了，原来是模版里传入的参数和我自定义函数里需要的参数格式不一样，
