### ISSUE TITLE
解超出决策变量范围

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#114]
你好，我用soea_DE_rand_1_L求解的时候，大部分时间求出的解都满足限制条件，但极其偶尔会发生求出的解超出决策变量范围的情况，请问这是为什么呢？谢谢！

**Comment by geatpy-dev** [comment]
@xrzalreadytaken hi！这个应该是由于浮点数精度异常所致，比如范围设置在[0, 1] 之间时，往往会有非常接近于0的负数出现。这个问题自2.5.0预览版采用了自研矩阵库起就一直出现，应该会在下一版本中得到彻底解决。

**Comment by xrzalreadytaken** [comment]
@geatpy-dev  我目前使用的是2.4这个版本，也会有精度异常这个问题嘛？

**Comment by geatpy-dev** [comment]
旧版本此前没有收到过此类问题噢，您试一下更新至2.5.0看看是否存在同样的问题？

**Comment by Haofenger** [comment]
> @geatpy-dev 我目前使用的是2.4这个版本，也会有精度异常这个问题嘛？

Python语言本身就存在浮点数精度问题，比如在python里面计算0.1+0.2，得到的是0.30000000000000004。

**Comment by xrzalreadytaken** [comment]
我升级到2.5.0没有这个问题了， 谢谢。

**Comment by geatpy-dev** [comment]
> 我升级到2.5.0没有这个问题了， 谢谢。

不客气哈！感谢您提出宝贵的问题！

**Comment by ZhuFanfa** [comment]
我都升级到2.7了还有这个问题
