### ISSUE TITLE
NDSet只有一组解

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#115]
你好，
我在用NSGA2模板进行双目标求解时，除了添加决策变量范围，没有添加任何限制条件。我的NIND = 100 ，myAlgorithm.MAXGEN = 200 。
根据我的理解，输出的NDSet 应该等于我所设置的中群发规模，也就是100。
但是模型求出的解只有1个，请问这是为什么呢？谢谢！

**Comment by geatpy-dev** [comment]
@xrzalreadytaken 您好！多目标优化只得到一组解一般是说明所优化的所有目标之间没有冲突，即可以使其变成单目标优化问题。

**Comment by xrzalreadytaken** [comment]
好的，谢谢。
