### ISSUE TITLE
绘制结果图时显示一片空白

### ISSUE THREAD

**Issue by jdx0813** [geatpy-dev/geatpy#117]
大大好，我设计的模型有跑出结果了，
帕累托最优解集也有产生，但绘制出来的结果图却是一片空白
请问是我模型设计的不良吗

**Comment by geatpy-dev** [comment]
@jdx0813 您好，这说明没有找到满足约束的个体。

**Comment by jdx0813** [comment]
那解决的方法是要我重新设计约束条件，还是将原先的约束条件放宽?

**Comment by geatpy-dev** [comment]
看看有没有等式约束，如果有要尽可能通过恒等变形等方法消元然后化为不等式约束。如果本身没有等式约束，说明约束太过复杂导致决策空间的可行域比较小，这时就需要修改模型或者去设计一个能很好解决当前特定问题的进化算法了。
