### ISSUE TITLE
开发者您好，请问我想获得目标函数值的具体数据应该怎么写呢

### ISSUE THREAD

**Issue by sunnyszcszc** [geatpy-dev/geatpy#118]
![Figure_1](https://user-images.githubusercontent.com/55119030/82135036-d786a880-9830-11ea-9eba-7ecd70ddd5e3.png)

**Comment by geatpy-dev** [comment]
@sunnyszcszc 如下图所示：
![image](https://user-images.githubusercontent.com/42562919/82137268-217b8880-9849-11ea-872b-3bd84c38416d.png)

**Comment by sunnyszcszc** [comment]
不懂就问，请问是obj_trace这个变量里面是所有的代数最优的数据么

**Comment by geatpy-dev** [comment]
@sunnyszcszc hi 这个obj_trace记录的是单目标优化每一代最优个体的目标函数值，它的赋值代码在Algorithm.py里面。

**Comment by sunnyszcszc** [comment]
好的我再看一下代码，再不会再请教您

**Comment by healer321** [comment]
开发者你好，请问多目标最优目标函数值怎么输出呢？谢谢

**Comment by geatpy-dev** [comment]
@healer321 答案如下图所示：
![image](https://user-images.githubusercontent.com/42562919/83623992-a514d380-a5c4-11ea-98ed-dea0d0c27e42.png)

**Comment by geatpy-dev** [comment]
该问题已超过最长期限，特此关闭。
