### ISSUE TITLE
不支持linux？？？？

### ISSUE THREAD

**Issue by ShuteLee** [geatpy-dev/geatpy#12]
请问什么时候可以支持linux

**Comment by 1061655504** [comment]
您好，网上发行的是Windows版本。需要Linux版本的可发邮件到：1061655504@qq.com 以获取噢。另外，看到您的备注，您是在黄翰的实验室吗？

**Comment by ShuteLee** [comment]
好的，多谢. 我是华工研究生，但不是你说的实验室。有问题再请教。

发自我的 iPhone

**Comment by ShuteLee** [comment]
老哥，你有Linux版本吗？加好友发邮件都没回我呀。

发自我的 iPhone
