### ISSUE TITLE
关于moead的效果

### ISSUE THREAD

**Issue by lepecoder** [geatpy-dev/geatpy#120]
您好，我之前使用的matlab的[PlatEMO](https://github.com/BIMK/PlatEMO)多目标进化工具箱，设置种群600，进化500代，UF1测试问题，在PlatEMO平台[MOEAD-DE](https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Algorithms/MOEA-D-DE/MOEADDE.m)框架下可以得到igd<0.001的效果，在400代时就可以得到近乎完美的前沿面。

而在geatpy平台，同样的参数只能得到IGD=0.05的效果，前沿面也不够平滑。
我已经将moead改成了差分算子和多项式变异，看起来已经和PlatEMO没有什么区别，可仍然不能达到PlatEMO的效果，希望您百忙之中能够解惑。
moea_MOEAD_DE_templet.py https://paste.ubuntu.com/p/4kpRwCT9k6/
mut_de.py https://paste.ubuntu.com/p/3frvhdfXzV/
我添加的行已经用#addition做标记
DE.m  https://paste.ubuntu.com/p/hh5RYmV4pq/

**Comment by geatpy-dev** [comment]
@lepecoder  hello！两个平台的差分进化的算子不一样。geatpy中的差分变异算子与重组算子均与DE算法原文是完全一样的，而matlab那个用的是一个变种，并非与DE原文一样。

**Comment by geatpy-dev** [comment]
噢，原来您还贴了代码，我看了一下里面用的是自己写的DE算子。建议您直接使用内置的差分变异和重组算子，这样才是跟DE原著论文保持一致。

**Comment by sc1101** [comment]
> 您好，我之前使用的matlab的[PlatEMO](https://github.com/BIMK/PlatEMO)多目标进化工具箱，设置种群600，进化500代，UF1测试问题，在PlatEMO平台[MOEAD-DE](https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Algorithms/MOEA-D-DE/MOEADDE.m)框架下可以得到igd<0.001的效果，在400代时就可以得到近乎完美的前沿面。
> 
> 而在geatpy平台，同样的参数只能得到IGD=0.05的效果，前沿面也不够平滑。
> 我已经将moead改成了差分算子和多项式变异，看起来已经和PlatEMO没有什么区别，可仍然不能达到PlatEMO的效果，希望您百忙之中能够解惑。
> moea_MOEAD_DE_templet.py https://paste.ubuntu.com/p/4kpRwCT9k6/
> mut_de.py https://paste.ubuntu.com/p/3frvhdfXzV/
> 我添加的行已经用#addition做标记
> DE.m https://paste.ubuntu.com/p/hh5RYmV4pq/

**老哥你写的代码里面的r1和r2不对劲。我去实现了一个MOEAD-DE，效果比较理想。**
https://paste.ubuntu.com/p/FhTqmJsq6t/

![image](https://user-images.githubusercontent.com/60003504/83131370-4e198500-a112-11ea-94cc-e7f520b93612.png)

**Comment by lepecoder** [comment]
> > 您好，我之前使用的matlab的[PlatEMO](https://github.com/BIMK/PlatEMO)多目标进化工具箱，设置种群600，进化500代，UF1测试问题，在PlatEMO平台[MOEAD-DE](https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Algorithms/MOEA-D-DE/MOEADDE.m)框架下可以得到igd<0.001的效果，在400代时就可以得到近乎完美的前沿面。
> > 而在geatpy平台，同样的参数只能得到IGD=0.05的效果，前沿面也不够平滑。
> > 我已经将moead改成了差分算子和多项式变异，看起来已经和PlatEMO没有什么区别，可仍然不能达到PlatEMO的效果，希望您百忙之中能够解惑。
> > moea_MOEAD_DE_templet.py https://paste.ubuntu.com/p/4kpRwCT9k6/
> > mut_de.py https://paste.ubuntu.com/p/3frvhdfXzV/
> > 我添加的行已经用#addition做标记
> > DE.m https://paste.ubuntu.com/p/hh5RYmV4pq/
> 
> **老哥你写的代码里面的r1和r2不对劲。我去实现了一个MOEAD-DE，效果比较理想。**
> https://paste.ubuntu.com/p/FhTqmJsq6t/
> 
> ![image](https://user-images.githubusercontent.com/60003504/83131370-4e198500-a112-11ea-94cc-e7f520b93612.png)

多谢，我再改改

**Comment by geatpy-dev** [comment]
@sc1101 您这个反而不对吧。
@lepecoder 然后我试了一下您上传的代码，没有发现出现您说的IGD只有0.05的情况。如果您能发一张出问题时的截图就更好了！
