### ISSUE TITLE
与 numpy.array 一起使用的问题

### ISSUE THREAD

**Issue by tanukihee** [geatpy-dev/geatpy#121]
在目标函数较为复杂，且计算中使用了 `numpy.array` 的情况下，进行优化运算时会报错「Setting an array element with a sequence」，即维数不一致的问题，也许需要提取出 `np.array` 中的元素出来计算，请问有相关方法吗

**Comment by tanukihee** [comment]
按 `scikit-opt` 文档
>`scikit-opt`  仍然支持非矢量化计算，因为有些函数很难写成矢量化计算的形式，还有些函数强行写成矢量化形式后可读性会大大降低。

`geatpy` 有无方法可以进行非矢量运算吗

**Comment by geatpy-dev** [comment]
@tanukihee 看一下soea_demo3、soea_demo6、soea_demo7等案例。 其中demo3是循环计算各个个体的目标函数值，demo6是加上了一个并行/并发计算，demo7是一个分布式计算。最好再额外查看网站上的《geatpy数据结构》文档。

**Comment by tanukihee** [comment]
由于我并不了解 SVM 模型，因此我看不懂相关案例，解决不了相关问题，不过还是非常好的轮子，十分感谢

**Comment by sc1101** [comment]
> 由于我并不了解 SVM 模型，因此我看不懂相关案例，解决不了相关问题，不过还是非常好的轮子，十分感谢

路过ing。

这并不难吧，我以前用geatpy搞过进化神经网络，也是无法用矩阵计算来同时计算所有个体的目标函数值，因此我用了个循环……核心是取出种群表现型矩阵Phen的每一行，Phen的每一行就是每个个体的所有决策变量。比如Phen[0, :]就会得到第一个个体的决策变量。用它来计算得到一个目标函数值，以此类推，最后把所有的目标函数值拼接成一个目标函数矩阵就好了。

看到又有一位兄弟被某些广告忽悠我就不得不跟你说一下了：
目前权威的EA框架基本上就这几个：**deap、geatpy、geatbx、jMetal、platemo、pygmo、pagmo、eaopt、pymoo、OTL**等，这些是接受过同行评审的、EA界一些知名导师认可的框架。我买过教训噶，之前被一些广告吸引用了一些并不权威的包含EA算法的框架（国内外的各用过一个，这里就不点名了），有些框架连算法都没写对/流汗，比如把NSGA2的交叉、变异都写错了；把单目标差分进化优化的算子都写错了，害我还浪费时间把它的源码研究了一遍，一行行对照算法文献才发现了问题/倒霉。

**Comment by tanukihee** [comment]
> 这并不难吧，我以前用 geatpy 搞过进化神经网络，也是无法用矩阵计算来同时计算所有个体的目标函数值，因此我用了个循环…… 核心是取出种群表现型矩阵 Phen 的每一行，Phen 的每一行就是每个个体的所有决策变量。比如 Phen [0, :] 就会得到第一个个体的决策变量。用它来计算得到一个目标函数值，以此类推，最后把所有的目标函数值拼接成一个目标函数矩阵就好了。

我仿照案例 3 用循环成功地写出来了，感谢指导。

>看到又有一位兄弟被某些广告忽悠我就不得不跟你说一下了：

多谢担心，但我只是选修课用一下，以后也应该不会有很多的接触了，不过还是谢谢了，十分好的轮子
