### ISSUE TITLE
开发者您好，请问“有效进化代数为0，没找到可行解。”是什么意思？怎么解决？

### ISSUE THREAD

**Issue by 863628123** [geatpy-dev/geatpy#122]
报的错是，RuntimeError: error: No feasible solution. (有效进化代数为0，没找到可行解。)

**Comment by geatpy-dev** [comment]
@863628123 hi, 意思就是整个进化过程都没有进化出一个满足约束条件的个体。可以看一下网站的FAQ的第9条：[http://geatpy.com/index.php/faq/](url)

**Comment by 863628123** [comment]
谢谢您的解答，问题已经解决。不过我还想问个别的问题，我只是了解进化算法的皮毛，只是现在需要优化一个没有解析式的问题，了解到这个库才想试试用这个库解决问题。请问输出的最佳个体参数，是算法找到的最优的一组参数么？如果是，为啥我还能找到更优的一组参数呢？

**Comment by geatpy-dev** [comment]
> 谢谢您的解答，问题已经解决。不过我还想问个别的问题，我只是了解进化算法的皮毛，只是现在需要优化一个没有解析式的问题，了解到这个库才想试试用这个库解决问题。请问输出的最佳个体参数，是算法找到的最优的一组参数么？如果是，为啥我还能找到更优的一组参数呢？

这个问题与该issue的标题不一致，请另外开一个issue提问，麻烦您啦。
