### ISSUE TITLE
开发者您好，对该库的输出中的“最优参数”有疑问

### ISSUE THREAD

**Issue by 863628123** [geatpy-dev/geatpy#123]
您好，谢谢您的解答。我只是了解进化算法的皮毛，只是现在需要优化一个没有解析式的问题，了解到这个库才想试试用这个库解决问题。请问输出的最佳个体参数，是算法找到的最优的一组参数么？如果是，为啥我还能找到更优的一组参数呢？

**Comment by geatpy-dev** [comment]
@863628123 如果是单目标优化的话案例里面最后打印输出的是最优的目标函数值以及与之对应的决策变量值噢。

**Comment by 1234321n** [comment]
大大请问有没有使用数据集进化某个模型参数的例子呢，最近在做用这个优化违约风险评估的课题，才入门，没有相似例子很艰难

**Comment by 1234321n** [comment]
比如我现在有一个一百个公司数据的数据集，在有两个决策变量的情况下，我希望每个公司的数据带入我的目标函数结果都尽可能的大于零，我该怎么解决这步呢

**Comment by geatpy-dev** [comment]
> 大大请问有没有使用数据集进化某个模型参数的例子呢，最近在做用这个优化违约风险评估的课题，才入门，没有相似例子很艰难

把待优化的模型写成问题类，便可以调用工具箱的算法模板进行进化优化了呢。

**Comment by 1234321n** [comment]
我带入数据的for循环是写在aimfunc里吗大大，他老是提醒我未在问题子类中设置目标函数

**Comment by geatpy-dev** [comment]
> 我带入数据的for循环是写在aimfunc里吗大大，他老是提醒我未在问题子类中设置目标函数

这个的话您不妨加一下工作人员QQ：1061655504，他可以远程帮助您快速解决代码上遇到的问题。

**Comment by 1234321n** [comment]
太感谢了

**Comment by geatpy-dev** [comment]
据悉该问题已经得到解决，特此关闭。
