### ISSUE TITLE
比如我现在有一个一百个公司数据的数据集，在有两个决策变量的情况下，我希望每个公司的数据带入我的目标函数结果都尽可能的大于零，我该怎么解决这步呢

### ISSUE THREAD

**Issue by 1234321n** [geatpy-dev/geatpy#124]
比如我现在有一个一百个公司数据的数据集，在有两个决策变量的情况下，我希望每个公司的数据带入我的目标函数结果都尽可能的大于零，我该怎么解决这步呢

_Originally posted by @1234321n in https://github.com/geatpy-dev/geatpy/issues/123#issuecomment-640267862_

**Comment by 1234321n** [comment]
大大，希望得到帮助，万分感谢

**Comment by geatpy-dev** [comment]
@1234321n 这个加个约束条件就行了嘛。
