### ISSUE TITLE
如何使种群满足一些约束但是不通过cv矩阵的方式

### ISSUE THREAD

**Issue by yukunzhan** [geatpy-dev/geatpy#125]
如何使种群满足一些约束但是不通过cv矩阵的方式
问题是这样，我需要求一个在一个4点图中的一个路径，图是一个有向有环图，每个点可以通向包括自己在内的一部分点，路径长度大约为20-30，如果随机生成种群然后用cv矩阵去进行约束会有大部分的染色体都不可用（不存在的路径），请问有什么办法可以在生成时就进行一定的约束？

**Comment by geatpy-dev** [comment]
@yukunzhan 可以使用针对与路径方面有关的染色体编码，比如：排列编码、基于优先级的编码。 排列编码直接设置Encoding为"P"即可；而优先级编码是基于排列编码的一个间接的编码，可以在百度搜索“进化算法基于优先级编码”查到详细是怎么编码的～

**Comment by yukunzhan** [comment]
这两种编码好像也不是太好解决在有环图中的路径产生。。不过我们对原问题重新建了模，换了别的解法，总之很感谢了
