### ISSUE TITLE
如何调用其他变异算子或重组算子？

### ISSUE THREAD

**Issue by yf950919** [geatpy-dev/geatpy#126]
你好，我实现了NSGA2的多目标优化，现在想要尝试其他算子，请问步骤应该怎么实现，可以有一个具体实例吗，是在算法参数这里添加的的吗，谢谢
![image](https://user-images.githubusercontent.com/54619154/84371347-1596a280-ac0c-11ea-95c6-0543bc087f52.png)

**Comment by geatpy-dev** [comment]
@yf950919 对的，把myAlgorithm.mutOper赋值为新的变异算子对象；把myAlgorithm.recOper赋值为新的重组算子对象就OK了。
