### ISSUE TITLE
请问多染色体的算例中是怎样识别多染色体的？

### ISSUE THREAD

**Issue by kikyo520** [geatpy-dev/geatpy#128]
在单目标demo5中，是通过什么方式使得算法模板识别问题的染色体构造(x1 x2 | x3 x4 x5 x6)?
我看到模板中有PsyPopulation.chromnum这个属性，但是没看到有输入或者识别这个属性的过程，是通过main中设置field来识别的吗？
如果是，那就是说如果要使用多染色体功能，即使决策变量的编码方式和取值都一样，也需要分成n个field才能得到n个染色体的个体吗？
小白一枚，问题表述可能不清晰，多多包涵。

**Comment by geatpy-dev** [comment]
@kikyo520 详见《Geatpy数据结构》文档，内容大概如下图：
![image](https://user-images.githubusercontent.com/42562919/84559475-7b4e7000-ad6d-11ea-86e7-4c902c1bc5c8.png)

**Comment by kikyo520** [comment]
嗯，我看了文档，在demo5中，这个chromnum是2，可是我没有在main文件里面看到设置chromnum的过程，这个值是怎么得出来的？

**Comment by geatpy-dev** [comment]
@kikyo520  就在这个种群类的文件里面，您可以用单步调试的方法快速了解整个流程。因为几乎每一行都有注释噢。

**Comment by kikyo520** [comment]
嗯，看完文件明白了，谢谢
