### ISSUE TITLE
关于geatpy在linux上用pyinstaller打包找不到模块的问题

### ISSUE THREAD

**Issue by JohnXB** [geatpy-dev/geatpy#129]
在linux上，我写的脚本里使用了geatpy，但是打包找不到geatpy里的模块，目前找到的问题是在__init__.py里使用的sys.path.append导致找不到，但是我把该文件里的import都改为了绝对路径之后还是会报错，原因是import的模块里又有import，但是这里我改不到，应该怎么解决呢

**Comment by geatpy-dev** [comment]
@JohnXB 与这个问题类似的问题在pyinstaller的github issue可以查到，据他们的回答是正在修复中。如果您急需打包，可以用其他打包方式替代pyinstaller。比如用Inno Setup或用linux自身的打包命令等将：包含geatpy的整个python以及您的项目程序打包。

**Comment by JohnXB** [comment]
@wshikui 目前我的方式是在脚本里显式的import报错的包以及打包的时候使用-p把geatpy的安装路径和缺少的库的路径放进去，例如：在脚本里显式导入
```
# 打包显式导入
import scipy.special
from mpl_toolkits import *
import mpl_toolkits.mplot3d
from rcs import rcs
...
```
打包命令:
 `python3 /usr/local/PyInstaller-3.5/pyinstaller.py -F test.py -p /usr/local/lib/python3.7/site-packages/geatpy/ -p /usr/local/lib/python3.7/site-packages/geatpy/core/   -p /usr/local/lib/python3.7/site-packages/geatpy/templates/moeas/awGA/
`
