### ISSUE TITLE
是什么原因移除Popuplation，setChrom方法？

### ISSUE THREAD

**Issue by rhl713** [geatpy-dev/geatpy#130]
如题，目前只看到将初始化种群放在算法模板这一处改变。
我在做一个大规模的VRP问题，配送点会超过5000点，随机初始化的种群根本不能完成任务。即使更新2.5版本，目前我还是使用setChrom，在mian进行初始化。

**Comment by geatpy-dev** [comment]
@rhl713 您好呀！感谢您的问题。情况大概是这样：前面版本的Population.setChrom()函数，有部分编程水平不是很高的用户反映使用不便，比如种群有100个个体，但先验知识里面的染色体只有一两条的情况，同时这些用户经常忘记在调用setChrom()后对种群的其他参数进行及时的更新。

于是后面就删除了setChrom()，引入了一个更为简便的“先知种群”的设置方法，即把先验知识存储到一个“先知种群”对象里面，然后直接传给算法模板的run()函数即可。详见soea_demo10。
![image](https://user-images.githubusercontent.com/42562919/86076980-b535ab00-babd-11ea-9059-6d310728feea.png)

**Comment by rhl713** [comment]
好的，非常感谢。
另外，PsyPopulation里面有几个异常输出应该漏了格式化 i。
‘error in PsyPopulation: Chrom[i] is None. (种群染色体矩阵未初始化。)'
