### ISSUE TITLE
大规模计算过程的几点改进建议

### ISSUE THREAD

**Issue by rhl713** [geatpy-dev/geatpy#131]
感谢你们维护这个工具箱，让我得以用于进行大规模的VRP运算；
以下是几点在使用过程中我对部分类的改动，以适应大规模的计算。由于大部分使用者用不到大量计算，仅作为issue提交，希望采纳：
Algorithm：1、passTime更改为list类型，用于统计服务器长时间计算波动；2、由于计算时间比较长，增加一个进度条，在terminated方法使用：
`
def process_bar(self , percent, start_str='', end_str='', total_length=0):
        bar = ''.join(['#'] * int(percent * total_length)) + ''
        bar = '\r' + start_str + bar.ljust(total_length) + ' {:0>4.1f}%|'.format(percent*100) + end_str
        print(bar, end='', flush=True)

self.process_bar((self.currentGen+1)/self.MAXGEN,start_str=f'MAXGEN={self.MAXGEN}:',end_str=f'100%', total_length=50)
`
Population，PsyPopulation：因为数据量比较大容易内存不足，另外存储结果文件也比较大，所以将‘P’编码输入输出都改为‘int’类型；

**Comment by geatpy-dev** [comment]
@rhl713  感谢您的宝贵建议！您的支持和鼓励是geatpy工具箱不断发展前进的动力！
