### ISSUE TITLE
请问计算HV时参考点怎么设置？

### ISSUE THREAD

**Issue by lepecoder** [geatpy-dev/geatpy#133]
通常情况计算HV的参考点是设置ones(1,M)，但是有些论文里计算HV时自定义了参考点，如下图
[HV参考点设置](https://i.loli.net/2020/07/08/7TuAcpJb9rh6dRK.jpg)

请问在计算HV时有没有办法自己设置参考点？

**Comment by geatpy-dev** [comment]
HV的计算被写死到了内核函数里面，采用的是所有的xi的最大值的1.1倍的点作为参考点。目前的版本无法设置指定的参考点呢。
