### ISSUE TITLE
能否动态生成目标函数&约束条件

### ISSUE THREAD

**Issue by nuts-mr** [geatpy-dev/geatpy#134]
开发者您好ヾ(•ω•`)o
我有一份数据是需要求在**100个**不同决策变量**样本**下，分别求出每个样本的多目标最优解。
每个样本下都有多个决策变量。
比如：样本①有5个决策变量，样本②有7个决策变量（不同的样本的有不同的目标函数和约束条件）。
而希望求出的最优解是决策变量的min方差与min和。（似乎因为涉及方差所以不能通过设置为0来解决？（；´д｀）ゞ
如果手动输入每个组合的参数要耗费很多时间。
能否根据每次循环输入的参数，动态生成目标函数以及约束条件来自动分别求出100个样本的最优解呢？

**Comment by geatpy-dev** [comment]
@nuts-mr  亲爱的，能否实现您的需求，取决于您能否写出实现这些操作的代码。而这些操作需要您在自定义的目标函数aimFunc()中根据您的模型写代码实现呢。

**Comment by nuts-mr** [comment]
好的~(ง •_•)ง
感谢解答

**Comment by shallphy** [comment]
@nuts-mr 请问您的问题解决了吗
