### ISSUE TITLE
dim相关问题, 以及不同长度染色体咨询

### ISSUE THREAD

**Issue by MaleicAcid** [geatpy-dev/geatpy#136]
请问一下比如我想实现在一个3*3的网格内, 用进化算法搜索出一条路径(允许斜着走)
1 2 3
4 5 6
7 8 9
这种情况下我没法事先确定路径会途径几个网格, 比如有可能是3个, 有可能是5个(7->5->3 和 7->8->9->6->3) 
请问这种情况下我应该如何设置dim变量 , 以及geatpy支持不同长度染色体的重组和变异吗?

(我看tsp问题的示例是有几个城市, dim就设置为几, 但区别在于我不需要所有的点都走到)

**Comment by Haofenger** [comment]
@MaleicAcid 用基于优先级的编码。 染色体是固定长度，而解码得到的路径是不定长的。[https://blog.csdn.net/weixin_37790882/article/details/100622338](url)

**Comment by MaleicAcid** [comment]
> @MaleicAcid 用基于优先级的编码。 染色体是固定长度，而解码得到的路径是不定长的。[https://blog.csdn.net/weixin_37790882/article/details/100622338](url)

谢谢您的回答， 我明白了很多。
我注意到文章里的网络是有向图, 而我的“网格搜索问题”是无向图。文章里也提了一句如果是无向图可以考虑对走过的点加以惩罚， 我下午写代码试了下, 发现按照原来那么写确实会出现一直转圈的情况，请问您知道哪里可以找到“无向图使用优先级编码”的参考资料吗，我搜了一下午...实在没有找到....
如能告知, 万分感谢 ;)

**Comment by Haofenger** [comment]
可以加点代码来回避这个回路问题。比如假如出现回路，则回到上一结点，使之下一步选择优先级次之的结点来访问。如果还是有回路，则回退。

**Comment by MaleicAcid** [comment]
> 可以加点代码来回避这个回路问题。比如假如出现回路，则回到上一结点，使之下一步选择优先级次之的结点来访问。如果还是有回路，则回退。

谢谢解答, 我写出来了哈哈, 就是搜索的时间有点久, 一个染色体可能会回退很多次才能得到最终解码的路径
Thx ;)
