### ISSUE TITLE
求解速度问题

### ISSUE THREAD

**Issue by chf-x** [geatpy-dev/geatpy#137]
请问在计算每一代的种群中个体的适应值的时候有考虑并行加速吗？我发现如果种群数量为50，迭代次数为700，ObjV的项很多的时候(比如车辆的路径规划和控制问题)，这个计算速度会降到1.几秒。这不能满足这些问题对速度的要求

**Comment by geatpy-dev** [comment]
@chf-x 这个性能瓶颈在你自定义的aimFunc() 上面呢。自定义的aimFunc()写出来的运行效率很低的话就会拖慢程序。可以参考soea_demo6、7用并行、并发或者分布式来计算目标函数值。如果有较高的编程能力，这部分还能用C、Java等来加速计算。

**Comment by chf-x** [comment]
请问小数数据如何编码？

**Comment by geatpy-dev** [comment]
@chf-x  文档以及所有的案例里面都有讲这个。即在问题类里面设置varTypes的对应元素为0。

**Comment by chf-x** [comment]
设为0就求不出来有效解了，是编码原因吗？

**Comment by chf-x** [comment]
老哥，我们的问题是离散的，但是求解结果不是小数都是整数。我的意思是想让求解的结果是小数

**Comment by geatpy-dev** [comment]
模型代码问题你联系一下工作人员QQ1061655504吧，他可以远程协助你解决疑难杂症。

**Comment by geatpy-dev** [comment]
据悉该问题已经得到解决。
