### ISSUE TITLE
用训练好的神经网络模型的输出值作为适应度值，但是始终报类型错误

### ISSUE THREAD

**Issue by WholeG** [geatpy-dev/geatpy#138]
开发者您好！
我的代码流程：

- 生成fi = x*x的二次函数的一百组数据 作为训练集 每个样本都是x ，fi
- 把这些样本用来训练一个神经网络
- 用训练好的神经网络模型作为目标函数，找出x输入范围为[-1, 2]中，神经网络模型输出的最小值

始终报错：raise RuntimeError('error: ObjV is illegal. (目标函数值矩阵ObjV的数据格式不合法，请检查目标函数的计算。)')   。
我把这段 if type(pop.ObjV) != np.ndarray or pop.ObjV.ndim != 2 or pop.ObjV.shape[0] != pop.sizes or pop.ObjV.shape[1] != self.problem.M: 分割开
始终卡在raise RuntimeError('1:  type(pop.ObjV) != np.ndarray')， 但我对神经网络的预测值进行类型转换，还是报相同的错误。

`import geatpy as ea
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
import random

#对神经网络的预测值进行类型转换，转换成ndarray格式，shape是(1,10)，还是报错 type(pop.ObjV) != np.ndarray
def arr_to_2_arr(pred_arr):
    arr2 = []
    for elem in pred_arr:
        arr2.append([elem])
    return np.array(arr2)

X = []
y = []
for i in range(200):
    x = random.uniform(-1, 2)
    X.append(x)
    # fi = x * np.sin(10 * np.pi * x)
    fi = x * x + 0.5
    y.append(fi)

X = np.array(X)
X = X.reshape(-1, 1)
y = np.array(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
clf = MLPRegressor(
    hidden_layer_sizes=(200, 100, 50),  activation='relu', solver='adam', alpha=0.1, batch_size='auto',
    learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=5000, shuffle=True,
    random_state=1, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
    early_stopping=False, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
clf.fit(X_train, y_train)

class MyProblem(ea.Problem):  # 继承Problem父类
    def __init__(self):
        name = 'MyProblem'  # 初始化name（函数名称，可以随意设置）
        M = 1  # 初始化M（目标维数）
        maxormins = [-1]  # 初始化maxormins（目标最小最大化标记列表，1：最小化该目标；-1：最大化该目标）
        Dim = 1  # 初始化Dim（决策变量维数）
        varTypes = [0] * Dim  # 初始化varTypes（决策变量的类型，元素为0表示对应的变量是连续的；1表示是离散的）
        lb = [-1]  # 决策变量下界
        ub = [2]  # 决策变量上界
        lbin = [1] * Dim  # 决策变量下边界（0表示不包含该变量的下边界，1表示包含）
        ubin = [1] * Dim  # 决策变量上边界（0表示不包含该变量的上边界，1表示包含）
        # 调用父类构造方法完成实例化
        ea.Problem.__init__(self, name, M, maxormins, Dim, varTypes, lb, ub, lbin, ubin)

    def aimFunc(self, pop):  # 目标函数
        x = pop.Phen  # 得到决策变量矩阵
        predict_result0 = clf.predict(x)
        print("predict_result0", predict_result0, "type------------  ", type(predict_result0))
        predict_result1 = arr_to_2_arr(predict_result0)
        print("predict_result1", predict_result1, "type------------  ", type(predict_result1))
        print("predict_result1 shape ", (predict_result1).shape, "predict_result1 type", type(predict_result1))
        pop.Objv = predict_result1

"""===============================实例化问题对象==========================="""
problem = MyProblem() # 生成问题对象
"""=================================种群设置==============================="""
Encoding = 'BG'       # 编码方式
NIND = 10             # 种群规模
Field = ea.crtfld(Encoding, problem.varTypes, problem.ranges, problem.borders) # 创建区域描述器
population = ea.Population(Encoding, Field, NIND) # 实例化种群对象（此时种群还没被初始化，仅仅是完成种群对象的实例化）
"""===============================算法参数设置============================="""
myAlgorithm = ea.soea_SEGA_templet(problem, population) # 实例化一个算法模板对象
myAlgorithm.MAXGEN = 25 # 最大进化代数
"""==========================调用算法模板进行种群进化======================="""
[population, obj_trace, var_trace] = myAlgorithm.run() # 执行算法模板
population.save() # 把最后一代种群的信息保存到文件中
best_gen = np.argmin(problem.maxormins * obj_trace[:, 1]) # 记录最优种群个体是在哪一代
best_ObjV = obj_trace[best_gen, 1]
print('最优的目标函数值为：%s'%(best_ObjV))
print('最优的控制变量值为：')

#报错情况：
D:\Tools\Anaconda\envs\machine_learning\python.exe D:/Download/Hey/Pycharm_projs/TEST_DEMO/Demos/geatpy_NN.py
Traceback (most recent call last):
  File "D:/Download/Hey/Pycharm_projs/TEST_DEMO/Demos/geatpy_NN.py", line 81, in <module>
predict_result0 [3.76410158 0.86126061 0.80857088 4.22067382 1.2648889  0.507139
    [population, obj_trace, var_trace] = myAlgorithm.run() # 执行算法模板
  File "D:\Download\Hey\Pycharm_projs\TEST_DEMO\geatpy\templates\soeas\GA\SEGA\soea_SEGA_templet.py", line 52, in run
    self.call_aimFunc(population) # 计算种群的目标函数值
 1.35683867 2.92259929 0.51521916 3.10023673] type------------   <class 'numpy.ndarray'>
  File "D:\Download\Hey\Pycharm_projs\TEST_DEMO\geatpy\Algorithm.py", line 116, in call_aimFunc
predict_result1 [[3.76410158]
    raise RuntimeError('1:  type(pop.ObjV) != np.ndarray')
 [0.86126061]
RuntimeError: 1:  type(pop.ObjV) != np.ndarray
 [0.80857088]
 [4.22067382]
 [1.2648889 ]
 [0.507139  ]
 [1.35683867]
 [2.92259929]
 [0.51521916]
 [3.10023673]] type------------   <class 'numpy.ndarray'>
predict_result1 shape  (10, 1) predict_result1 type <class 'numpy.ndarray'>

Process finished with exit code 1

还请帮忙看看， 感激不尽！！

**Comment by geatpy-dev** [comment]
@WholeG  你去联系客服QQ1061655504让他远程协助一下。

**Comment by WholeG** [comment]
已经解决， pop.Objv = predict_result1 这里的Objv中的v要改正为大写V， 此外，主要就是调整模型输出的ndarray类型， 注意是[ [1], [2], [3]]这样的。  非常感谢开发者。 加油！
