### ISSUE TITLE
您好，我在demo7的代码中，打印出预测结果和测试集真实结果发现，当测试集的真实分类为'Very Low',预测结果为 'very_low'，只是大小写和多了一杠，意思一样但会被认为不同，被认为预测错误，从而准确率降低了

### ISSUE THREAD

**Issue by remember331** [geatpy-dev/geatpy#139]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by geatpy-dev** [comment]
该问题是与工具箱不相关的噢，是模型的建立问题。
