### ISSUE TITLE
crtfld.pdf 解释有点不清楚

### ISSUE THREAD

**Issue by zhaosongyi** [geatpy-dev/geatpy#14]
以这几行为例:
x1 = [-3, 5] # 自变量1的范围
x2 = [2, 10] # 自变量2的范围
b1 = [1, 0] # 自变量1的边界
b2 = [1, 1] # 自变量2的边界
codes = [0, 1] # 各变量的编码方式， 2个变量均使用格雷编码
precisions = [0, 0] # 各变量的精度， 0表示精确到个位
scales = [1, 0] # 采用算术刻度
ranges = np.vstack([x1, x2]).T # 生成自变量的范围矩阵
borders = np.vstack([b1, b2]).T # 生成自变量的边界矩阵

b1 是不是应该为[1,1], 因为上下界都存在?
codes=[1,1] 如果两个都是格雷编码?
scales = [1, 1] , 如果都采用算术精度?

**Comment by 1061655504** [comment]
嗯嗯，您说得很对。经查实是该文档描述出现疏漏，已反馈修复并重新上传。
