### ISSUE TITLE
Rhino 软件ironpython 2.7.5导入geatpy问题

### ISSUE THREAD

**Issue by lalaland2020** [geatpy-dev/geatpy#140]
想问下，尝试在rhino里的python（版本是iropython2.7.5）导入geatpy失败，直接复制包到安装目录下依旧是出错：Runtime error (ImportException): No module named geatpy。 
想问下是否不支持iropython？感谢！

**Comment by geatpy-dev** [comment]
@lalaland2020  不支持python2.x的呢。要3.5以上的才行。

**Comment by lalaland2020** [comment]
> @lalaland2020 不支持python2.x的呢。要3.5以上的才行。

哭了，ironpython最新只有2.7.10，https://ironpython.net/

**Comment by geatpy-dev** [comment]
@lalaland2020 有个间接的方法是你用ironpython写个脚本，间接调用python3去运行geatpy的代码。

**Comment by lalaland2020** [comment]
谢谢！我试试~~
