### ISSUE TITLE
DE模板中如何修改crossover的策略

### ISSUE THREAD

**Issue by WindAsMe** [geatpy-dev/geatpy#141]
想请教一下如何在采用模板优化的时候修改DE交叉的策略

**Comment by geatpy-dev** [comment]
@WindAsMe  您好！可否详细描述需求？一般是可以直接在自定义的算法模板中实现自己的创意设计。

**Comment by WindAsMe** [comment]
感谢回复。就是在ea.soea_DE_best_1_L_templet模板中希望用Exponential Crossover来代替Binomial Crossover

**Comment by geatpy-dev** [comment]
@WindAsMe  soea_DE_best_1_L里面使用的交叉算子就是指数交叉了。

**Comment by WindAsMe** [comment]
这样啊 多谢多谢
