### ISSUE TITLE
使用moea_NSGA2_templet时，若无可行解时，属性设置maxForgetCount和MAXTIME完全无效，运行时间非常长

### ISSUE THREAD

**Issue by zypruc** [geatpy-dev/geatpy#142]
使用moea_NSGA2_templet时，若无可行解时，属性设置maxForgetCount和MAXTIME完全无效，运行时间非常长
moea_NSGA2_DE_temple情况类似

**Comment by 1061655504** [comment]
@zypruc 触发了“遗忘策略”，详见Algorithm.py。该问题同[issue 74](https://github.com/geatpy-dev/geatpy/issues/74
)

**Comment by 1061655504** [comment]
在terminated()里添加print(self.currentGen)看看是不是停留在了某一代里面。MAXTIME不可能无效的，检查一下代码。

**Comment by zypruc** [comment]
谢谢，大概懂了，是原生Algorithm.py不调用terminated，因此需要继承写一个新的是吗？

**Comment by 1061655504** [comment]
@zypruc 对哒，照着那个文档写一个terminated()，就可以实现利用MAXTIME来控制进化时间。

**Comment by zypruc** [comment]
说错了，currentGen维持-1，passTime为0

**Comment by 1061655504** [comment]
@zypruc 用MAXTIME控制时间的时候要把遗忘策略关掉，因为遗忘策略会忽略找不到可行解时候的时间。

**Comment by zypruc** [comment]
搞定了，谢谢。源码模版里初始化了maxForgetCount=1000，难怪我后续修改属性maxForgetCount没用。
