### ISSUE TITLE
请教一下可以对染色体某一个点位进行优化吗

### ISSUE THREAD

**Issue by WindAsMe** [geatpy-dev/geatpy#145]
想请教一下是否可以实现在DE中对染色体某一个点位/函数的某一个变量进行优化

**Comment by geatpy-dev** [comment]
@WindAsMe 您的意思是只对染色体上的某个点位进行变异对吧，如果使用的是2.5.x及以下的版本，就只能新建一个自定义算法模板，在变异操作里只提取染色体矩阵的某一列进行变异。后面发布了2.6之后，就可以直接通过设置变异概率来控制对染色体的局部区域进行变异。

**Comment by WindAsMe** [comment]
好的 感谢回答
