### ISSUE TITLE
请问2.0版本何时发布

### ISSUE THREAD

**Issue by l976308589** [geatpy-dev/geatpy#15]
尊敬的作者，看到官网有2.0版本的通知，不知何时发布

**Comment by 1061655504** [comment]
去年8月的时候曾经因草率发布而发生侵权，导致被勒令下架了近一个月。因此在发布2.0版本前我们需等待两篇论文的投稿成功。现论文已在初审，在这段时间里我们也会进行进一步改善。谢谢您的关注和支持！

**Comment by l976308589** [comment]
您好，能否私下给我发送一份新版，想学习一下
976308589@qq.com

**Comment by 1061655504** [comment]
> 您好，能否私下给我发送一份新版，想学习一下
> [976308589@qq.com](mailto:976308589@qq.com)

很抱歉我没有这个权限。不过我很高兴可以和您常联系相互交流一起学习进步噢~
