### ISSUE TITLE
请问能否保留前几优的解

### ISSUE THREAD

**Issue by fkrsr** [geatpy-dev/geatpy#152]
你好，请问一下是否支持输出比如前三个、前十个最好的解？在文档里没查到类似方法。
如果不行的话请教一下如何输出每一代的最优解，谢谢！

**Comment by geatpy-dev** [comment]
@fkrsr 这个定制化需求你用numpy就可以实现了。在soea_demo1的main.py的myAlgorithm.run()的下一行添加以下代码：
top_five_index = np.argsort(population.ObjV * problem.maxormins, axis=0)[:5]
top_five_pop = population[top_five_index]

**Comment by fkrsr** [comment]
> @fkrsr 这个定制化需求你用numpy就可以实现了。在soea_demo1的main.py的myAlgorithm.run()的下一行添加以下代码：
> top_five_index = np.argsort(population.ObjV * problem.maxormins, axis=0)[:5]
> top_five_pop = population[top_five_index]

非常感谢！
