### ISSUE TITLE
moea_amga2(archive based micro genetic algorithm2) and moea_de

### ISSUE THREAD

**Issue by RYANZYC** [geatpy-dev/geatpy#154]
您好，请问有Archive based Micro Genetic Algorithm2多目标优化 和差分多目标优化的模板嘛？

**Comment by geatpy-dev** [comment]
@RYANZYC MOEA/D-DE就是带差分进化的MOEA/D多目标优化算法了。至于“Archive based Micro Genetic Algorithm2”，工具箱没有内置，需要根据具体论文来配合调用工具箱的库函数实现。
