### ISSUE TITLE
NDSet = myAlgorithm.run()返回格式问题

### ISSUE THREAD

**Issue by Uncle-Yuanl** [geatpy-dev/geatpy#155]
https://github.com/geatpy-dev/geatpy/blob/8579e1b365090aac2d94461a8227b23a9c25d177/geatpy/Algorithm.py#L428

上面的连接返回的是一个列表[NDSet, pop]，然而主页中入门的案例NDSet = myAlgorithm.run()是列表，并没有提出中间的元素，导致报错：list没有‘save’等方法，希望尽快修改谢谢！

**Comment by geatpy-dev** [comment]
@Uncle-Yuanl 多谢反馈，新出的2.6版本对返回值作了重新的规范。网页另由他人负责，可能还没更新到。
