### ISSUE TITLE
为什么demo里main代码最后的print无法输出？

### ISSUE THREAD

**Issue by Fuhan2019** [geatpy-dev/geatpy#156]
为什么demo里main代码最后的print无法输出，运行后能出图，但是最后几句print的结果不输出，显示程序还在运行，但是一直出不了结果，CPU也显示没有在利用，不知道是为什么。

我用的是win10环境，pycharm2019.2版本，以前用geatpy库没有问题，一切正常，后来装了anaconda，好像就这样了，升级了geatpy库也还是这样，求指点，谢谢！

**Comment by geatpy-dev** [comment]
@Fuhan2019 可以向工作客服寻求远程协助。QQ: 1061655504。

**Comment by geatpy-dev** [comment]
据悉已帮助该同学妥善解决了该问题。
