### ISSUE TITLE
您好，在2.6.0的Algorithm.py发现一个疑似bug

### ISSUE THREAD

**Issue by yanran-xiong** [geatpy-dev/geatpy#157]
在Algorithm.py的592行，bestIndi = feasiblePop[np.argmax(feasiblePop.FitnV)]中，由于np.argmax(feasiblePop.FitnV)得出的结果是np.intc的类型，在population属性中只支持int32或64型的index，所以我加了.astype(np.int32)后就可以顺利运行了，要不然会报错“index必须是一个整数，一维列表或向量。”

**Comment by geatpy-dev** [comment]
@yanran-xiong 很高兴收到您的提问。但Python中属于整数的类型除了已列出的之外还有相当多，比如tensorflow、pytorch等里面也有一堆的表示整数类型，这个地方不对传入的index参数的合法性进行更详细的检查了。如遇到类型检查不通过，可在算法模板中进行强制类型转换，或把新的类型自己添加到该处的类型检查当中。
![image](https://user-images.githubusercontent.com/42562919/98676948-45063280-2397-11eb-93d4-ccaee61e27f9.png)

**Comment by yanran-xiong** [comment]
谢谢您的回复！
