### ISSUE TITLE
linux版本的获取

### ISSUE THREAD

**Issue by donydex** [geatpy-dev/geatpy#16]
已经给1061655504@qq.com发过邮件了，暂时没有回复，不知道是不是这个邮箱地址变了2333，另外tutorial写的很好，建议直接在网页端展示,pdf看起来切换不是很方便

**Comment by 1061655504** [comment]
> 已经给[1061655504@qq.com](mailto:1061655504@qq.com)发过邮件了，暂时没有回复，不知道是不是这个邮箱地址变了2333，另外tutorial写的很好，建议直接在网页端展示,pdf看起来切换不是很方便

已发~可以下载下来看的噢！
