### ISSUE TITLE
如何设定迭代终止条件

### ISSUE THREAD

**Issue by MaCshan** [geatpy-dev/geatpy#166]
开发者，您好。
geatpy提供了哪个接口，可以自定义总是条件。
如果在网站的文档中有说明，请明确一下位置。
谢谢。

**Comment by geatpy-dev** [comment]
Why not use ctrl + F to find it?

**Comment by geatpy-dev** [comment]
It's not a good question. Every day we receive quite many meaningless questions, we won't answer them because they can figure out themselves.
