### ISSUE TITLE
cannot import name 'migrate' from 'migrate'

### ISSUE THREAD

**Issue by sbwww** [geatpy-dev/geatpy#171]
**Describe the bug**
I encountered the following bug report when importing geatpy

```
Traceback (most recent call last):
  File "...\solve.py", line 3, in <module>
    import geatpy as ea   # import geatpy       
  File "...\Python37\lib\site-packages\geatpy\__init__.py", line 38, in <module>
    from migrate import migrate
ImportError: cannot import name 'migrate' from 'migrate' (...\Python37\lib\site-packages\migrate\__init__.py)
```

**To Reproduce**
It was just importing geatpy

```
import geatpy as ea
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: geatpy 2.6.0

**Additional context**
Maybe it has something to do with my installed packages, I will check it up, but I'm not sure I can handle this.

**Comment by sbwww** [comment]
As the 'migrate' is not in the pip list, I just removed the directory named 'migrate' from 'site-packages', and it seems to be fine.
However, I have no idea why it was there, and whether I had just brought a potential disaster to myself :dizzy_face:

**Comment by geatpy-dev** [comment]
Clapping, you did a good job!
