### ISSUE TITLE
绘制结果图如何调整大小和分辨率

### ISSUE THREAD

**Issue by yuanvq** [geatpy-dev/geatpy#172]
当设置myAlgorithm.drawing = 1 时，可以绘制结果图，如果我想调整绘制结果图的大小和分辨率。我该如何修改？
贴上部分代码

"""================================算法参数设置================================="""
myAlgorithm = ea.soea_EGA_templet(problem, population) # 实例化一个算法模板对象
myAlgorithm.MAXGEN = 200 # 最大进化代数
myAlgorithm.logTras = 1  # 设置每隔多少代记录日志，若设置成0则表示不记录日志
myAlgorithm.verbose = True  # 设置是否打印输出日志信息
myAlgorithm.drawing = 1  # 设置绘图方式（0：不绘图；1：绘制结果图；2：绘制目标空间过程动画；3：绘制决策空间过程动画）
"""===========================调用算法模板进行种群进化==============--==========="""
[BestIndi, population] = myAlgorithm.run()  # 执行算法模板，得到最优个体以及最后一代种群
BestIndi.save()  # 把最优个体的信息保存到文件中

**Comment by geatpy-dev** [comment]
直接用matplotlib画。工具箱里面只有最基本的一些绘图功能，有更多绘图需求得用专门的绘图包。

**Comment by scales123** [comment]
如何保存迭代过程中种群目标值，然后自己画图啊？
