### ISSUE TITLE
是否可以记录个体的目标值，遇到相同个体时不再重复计算

### ISSUE THREAD

**Issue by sbwww** [geatpy-dev/geatpy#174]
**Is your feature request related to a problem? Please describe.**
最近使用时发现，每一代中存在很多重复的个体，如果每个都要重新计算一次的话，可能时间较长，于是在想能不能把个体的目标函数值记录下来

**Describe the solution you'd like**
记录计算过的（或者一些高频出现）的个体，下次遇到相同编码的个体时，不再重新计算

**Describe alternatives you've considered**
或者在aimFunc()里自己定一个dict来存？

**Additional context**
无

**Comment by geatpy-dev** [comment]
当然可以。

**Comment by sbwww** [comment]
不太清楚应该如何把整个进化过程中的高频个体存下来，在 aimFunc 里用字典的话似乎只能存这一代的个体

**Comment by geatpy-dev** [comment]
用数据库即可
