### ISSUE TITLE
关于pop.CV的设置

### ISSUE THREAD

**Issue by bruce0715** [geatpy-dev/geatpy#177]
首先感谢开源这么赞的项目。想询问一下，如果我有10个决策变量，编码是’RI‘（整数编码）。我希望这10个决策变量互不相等，且交叉后的个体10个决策变量也互不相等。我应该如何操作呢？感谢~ （可以想象一张卷子里有10道题，整数是题目编码，不希望一个卷子里有重复题目）。

**Comment by geatpy-dev** [comment]
这个明显得用排列编码'P'。
