### ISSUE TITLE
多目标优化的帕累托解集

### ISSUE THREAD

**Issue by binbin96** [geatpy-dev/geatpy#179]
```python
[NDSet, population] = myAlgorithm.run(prophetPop)
```

开发者您好，我运行上面的命令，计算完成之后，NDSet和population一直都是一模一样的，请问怎么才能得到帕累托解，版本：2.6.0。之前也有相类似的issue，https://github.com/geatpy-dev/geatpy/issues/101 。但是现在新版本好像还是存在一样的问题。

**Comment by geatpy-dev** [comment]
@binbin96 嗯？具体是什么问题？NDSet.ObjV就是算法最终得到的帕累托解呀。

**Comment by binbin96** [comment]
@geatpy-dev 抱歉，因为在我的优化问题里面，最后一代种群全部都是帕累托解个体，我以为是算法存在问题，现在没什么问题了，感谢您的回复！

**Comment by shallphy** [comment]
您的优化问题以及代码可以发我看看不  一直没找到有工程应用方面使用geatpy求解的代码参考 @binbin96

**Comment by binbin96** [comment]
> 您的优化问题以及代码可以发我看看不 一直没找到有工程应用方面使用geatpy求解的代码参考 @binbin96

@shallphy 抱歉哈，我也不是用在工程应用方面的，只是用来做毕业设计而已。
