### ISSUE TITLE
关于多染色体问题

### ISSUE THREAD

**Issue by cugcuiyc** [geatpy-dev/geatpy#181]
![图片1](https://user-images.githubusercontent.com/68642492/115045514-2806fa00-9f09-11eb-8ff0-df6ef88d3c6c.png)
### 
![图片2](https://user-images.githubusercontent.com/68642492/115045542-2f2e0800-9f09-11eb-9136-28a511a78106.png)
### 
![image](https://user-images.githubusercontent.com/68642492/115045616-40771480-9f09-11eb-8840-a14e7e6ffea3.png)

为什么geatpy的多染色体，我设置两个排列编码‘P’，他们不是分别进行重组呢？geatpy貌似将整个染色体进行重组了。
图片1和图片2应该分别都是单独的排列才对，但是现在的结果是他们加在一起才是一个排列。

**Comment by geatpy-dev** [comment]
跟你自定义问题类里面定义的上下界有关。

**Comment by cugcuiyc** [comment]
> 跟你自定义问题类里面定义的上下界有关。

原来如此！解决了！谢谢。
