### ISSUE TITLE
您好，麻烦问下如何设置目标函数值的优化范围

### ISSUE THREAD

**Issue by PeterFanFan** [geatpy-dev/geatpy#182]
我设置了一个目标函数，但如何设置这个目标函数值的最小值？
或者说，需要最小化一个目标函数到一个指定值就停止，如何设定这个最小值呢？

**Comment by geatpy-dev** [comment]
soea\_demo6

**Comment by PeterFanFan** [comment]
那个soea_demo6 与我的需求还是不符合，
我的问题：比如soea_demo6的问题来说，我只想让交叉验证（目标函数）的准确性优化到达90%（一个定值以上)就停下，然后得到此时的决策变量的值

**Comment by geatpy-dev** [comment]
自定义进化算法终止条件。

**Comment by PeterFanFan** [comment]
感谢工程师，此问题已解决。

**Comment by scales123** [comment]
@PeterFanFan 请问您是怎么解决的啊？
