### ISSUE TITLE
request

### ISSUE THREAD

**Issue by shallphy** [geatpy-dev/geatpy#183]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/76924849/116015003-59e73180-a66a-11eb-9796-bf76ef9964cd.png)
请问这个问题是否是因为我自己的优化模型的问题

**Comment by 1061655504** [comment]
该问题已通过QQ咨询解决。
