### ISSUE TITLE
能否让编码为互不相等的一组整数？

### ISSUE THREAD

**Issue by cliff0149** [geatpy-dev/geatpy#185]
我想让我的编码为一组互不相等的整数，每个整数代表作业配送的次序，比如我有30个作业，那就生成一个数字列表，涵盖1-30。我找了一下源码中生成随机编码的代码，但是仿佛是在内核中，所以无法修改？目前我采用的办法是以浮点数为编码，再按浮点数大小来安排次序，但这样会造成冗余，编码和解不能一一对应，感觉会影响收敛速度。请问作者有什么办法可以实现我想要的这种编码方式吗？

**Comment by geatpy-dev** [comment]
不是有个排列编码嘛。
