### ISSUE TITLE
关于选择，交叉的问题

### ISSUE THREAD

**Issue by 1838094824** [geatpy-dev/geatpy#19]
我只是看了几个demo，首先这个运行速度是真的非常快，比自己写的要好很多，不过对于选择和交叉有几个疑问。
首先是选择的时候我发现了重复选取某个个体，就是选择之后的种群中的某几个个体可能时来源于同一个个体，请问这样会造成局部最优解吗，就是感觉可能减少了全局搜索的广度。
第二个交叉，不是太清楚交叉时是哪两个个体进行交叉的
另外，请问方便给linux版本的geatpy吗，毕竟windows下很容易打游戏了，我的邮箱是1838094824@qq.com，是一位来自中国石油大学的小生

**Comment by 1061655504** [comment]
> 我只是看了几个demo，首先这个运行速度是真的非常快，比自己写的要好很多，不过对于选择和交叉有几个疑问。
> 首先是选择的时候我发现了重复选取某个个体，就是选择之后的种群中的某几个个体可能时来源于同一个个体，请问这样会造成局部最优解吗，就是感觉可能减少了全局搜索的广度。
> 第二个交叉，不是太清楚交叉时是哪两个个体进行交叉的
> 另外，请问方便给linux版本的geatpy吗，毕竟windows下很容易打游戏了，我的邮箱是[1838094824@qq.com](mailto:1838094824@qq.com)，是一位来自中国石油大学的小生

进化算法允许选择的个体中出现重复个体，可以在这一点上加以改进创新，提高种群的分布性。比如：
![image](https://user-images.githubusercontent.com/43485717/56090977-8b559000-5edb-11e9-97e4-51e32674ea4d.png)

对于交叉算子，工具箱里面是将第1、2个，第3、4个，第5、6个，以此类推的方法进行交叉。若种群规模是奇数，则最后一个个体不参与交叉。在算法模板里面可以添加随机打乱种群个体顺序的代码。

感谢您提出宝贵的问题！

**Comment by ConnLiu** [comment]
如果设置重组算子的Half_N为整数呢？例如种群数为100时，Half_N为4，那交叉时是哪些个体进行交叉的呢？
文档里讲是全局交叉模式，就是所有个体一起交叉嘛？
