### ISSUE TITLE
全局交叉模式的意思是？

### ISSUE THREAD

**Issue by ConnLiu** [geatpy-dev/geatpy#191]
如果设置重组算子的Half_N为整数呢？例如种群数为100时，Half_N为4，那交叉时是哪些个体进行交叉的呢？
文档里讲是全局交叉模式，就是所有个体一起交叉嘛？

_Originally posted by @ConnLiu in https://github.com/geatpy-dev/geatpy/issues/19#issuecomment-850362707_

**Comment by geatpy-dev** [comment]
就是交叉得到的染色体的各个交叉位置上的元素都有可能来自OldChrom中的任何一条染色体。

**Comment by ConnLiu** [comment]
好的，谢谢！
另外请问 多点交叉算子类 Xovmp（http://geatpy.com/index.php/重组算子/）的文档、文件在哪？ 
2.6版本里没找到，如下图
<img width="222" alt="image" src="https://user-images.githubusercontent.com/15926859/120056951-1d946000-c072-11eb-9f8e-f51495ede63f.png">

**Comment by geatpy-dev** [comment]
Xovmp是冗余的，2.6.0已经将其移除。

**Comment by ConnLiu** [comment]
明白了，谢谢！
