### ISSUE TITLE
请问如何设置某些位的交叉概率呢？

### ISSUE THREAD

**Issue by ConnLiu** [geatpy-dev/geatpy#192]
> @fkrsr 即将发布的2.6版本里面可以设置某些位的交叉和变异概率为0，这样就可以把它们的值锁死了。目前的版本只能用正如你所描述的传统的办法来实现。

@geatpy-dev 求问如何设置某些位的交叉为0？
例如均匀分布交叉xovud这里的XOVR交叉概率是针对整个染色体矩阵的，那如何针对某些位呢？NewChrom =  xovud(OldChrom, XOVR)

_Originally posted by @ConnLiu in https://github.com/geatpy-dev/geatpy/issues/146#issuecomment-850955531_

**Comment by geatpy-dev** [comment]
我看了一下注释，好像发行的2.6.0版本只有变异算子能控制染色体每一位的变异概率。重组算子没有。

**Comment by ConnLiu** [comment]
好的，谢谢！
