### ISSUE TITLE
得到的结果与期望相差较大

### ISSUE THREAD

**Issue by ebestmobile2020** [geatpy-dev/geatpy#193]
**Describe the bug**
输入50个坐标，寻找最优路径，得到附图的结果（部分）

**To Reproduce**
基本用了单目标demo 3中的代码，只是调整了坐标值和数量

**Expected behavior**
寻找最短路径

**Screenshots**
[
![Figure_1](https://user-images.githubusercontent.com/75355862/120621747-c38c0400-c490-11eb-9ada-7151bde1002a.png)
](url)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python Version: 3.8

**Additional context**
想要通过遗传算法找到最佳路径，但是貌似通过修改算法还是无法达到预期的结果。 然后找到了这个库，但似乎结果也不理想

**Comment by geatpy-dev** [comment]
这个与算法有关。需实现最先进的算法。
