### ISSUE TITLE
moea_NSGA2_templet 求解多目标优化问题，结果集中会有多个非支配解，那我们应用时应该选择哪一个解作为最终结果呢？

### ISSUE THREAD

**Issue by Paul-Cui** [geatpy-dev/geatpy#199]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geatpy-dev** [comment]
这个是多目标优化的基本问题，请查阅相关的文献资料。
