### ISSUE TITLE
是否存在NSGA3或者MOEA/D？

### ISSUE THREAD

**Issue by l976308589** [geatpy-dev/geatpy#20]
您好，是否存在NSGA3或者MOEA/D？

**Comment by 1061655504** [comment]
> 您好，是否存在NSGA3或者MOEA/D？

Geatpy发行版没有内置NSGA-III和MOEA/D的算法模板。正在内测，下一版本会提供内置模板噢。现在您可以自定义相关的算法模板，像拼积木似的，难度不大的。
