### ISSUE TITLE
Seed设置问题

### ISSUE THREAD

**Issue by siwuxei** [geatpy-dev/geatpy#210]
使用官网的demo，<http://geatpy.com/index.php/2020/10/19/3-%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A82-6-x/>
![image](https://user-images.githubusercontent.com/50586809/125307240-768a3000-e362-11eb-9609-daddb42a2d69.png)
每次设置np.random.seed()时候都会抛出异常
![image](https://user-images.githubusercontent.com/50586809/125307444-a2a5b100-e362-11eb-928f-0e1b69dccbb5.png)
请问是什么问题的？

**Comment by siwuxei** [comment]
如果这样设置不对，我该如何固定随机种子呢？

**Comment by geatpy-dev** [comment]
我这边把文档里的代码复制下来，执行一切正常呢。而且上图的异常跟随机数种子无关。你单步调试就可以解决。

**Comment by siwuxei** [comment]
感谢您的回复，是我自己问题。
