### ISSUE TITLE
是否有对协同演化（Co-evolution）的支持？

### ISSUE THREAD

**Issue by buaaguotong** [geatpy-dev/geatpy#219]
在解决大规模优化问题时，常常面临由于决策变量维度过高而产生的维度灾难的挑战。一种可行的方法是利用“协同演化”，其主要基于分治思想，通过对决策变量进行分组，实现分治。更先进的协同演化方法还介绍了动态分组等概念。
请问本项目是否有对协同演化机制的支持呢？
在文档中看到了类似的叙述，但仔细阅读发现文档中的协同演化指多种群演化，并非上文所提到的协同演化概念。
谢谢！

**Comment by geatpy-dev** [comment]
工具箱只内置提供一些经典的算法以及可以复用的工具函数，更多算法需要自定义算法类来实现呢。
