### ISSUE TITLE
pyinstaller 打包缺少PYD文件

### ISSUE THREAD

**Issue by youyuxi1006** [geatpy-dev/geatpy#22]
pyinstaller 打包缺少PYD文件

**Comment by geatpy-dev** [comment]
> pyinstaller 打包缺少PYD文件

pyinstaller的配置较为复杂，一不小心就会导致找不到文件路径，所以要小心设置。建议改用 Inno Setup对项目文件进行打包成setup.exe，它基本不需要任何设置，直接打包后运行setup.exe即可安装包内的所有文件。
