### ISSUE TITLE
在进行单目标测试函数测试时，比如Griewangk函数，如果想测试20维、30维的该如何操作，我看你们代码都是2维的

### ISSUE THREAD

**Issue by sunhao3871** [geatpy-dev/geatpy#221]

**Comment by geatpy-dev** [comment]
这些测试函数里面都有变量维度的设置呀。。

**Comment by sunhao3871** [comment]
是在def_inin_(self,Dim=2)那里设置吗，但是我把这里2换成其他维度得到的结果，还是二维的没啥变化



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月13日(周五) 中午11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [geatpy-dev/geatpy] 在进行单目标测试函数测试时，比如Griewangk函数，如果想测试20维、30维的该如何操作，我看你们代码都是2维的 (#221)




 
这些测试函数里面都有变量维度的设置呀。。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by geatpy-dev** [comment]
python编程基础
