### ISSUE TITLE
老师您好又来打扰了。就是因为最后绘图坐标轴量程太大，导致结果不明确，我想改一下坐标轴的量程应该怎么操作，谢谢

### ISSUE THREAD

**Issue by sunhao3871** [geatpy-dev/geatpy#222]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geatpy-dev** [comment]
Geatpy工具箱不提供定制化的绘图功能，请根据绘图所需数据，用已有的专业绘图库，比如Matplotlib进行绘制。
