### ISSUE TITLE
soea_demo4 案例问题

### ISSUE THREAD

**Issue by TeletubbiesPo** [geatpy-dev/geatpy#225]
MyProblem.py

修改

24行 ：       ub = [122] * Dim  # 决策变量上界       这里可以是121。

 或者在不修改24行 122值的情况下  修改26行 

26行：       ubin = [0] * Dim  # 决策变量上边界（0表示不包含该变量的上边界，1表示包含）

**Comment by geatpy-dev** [comment]
python基础问题。
