### ISSUE TITLE
RuntimeError: error: ObjV is illegal. (目标函数值矩阵ObjV的数据格式不合法，请检查目标函数的计算。)

### ISSUE THREAD

**Issue by weidongzhou1994** [geatpy-dev/geatpy#226]
![image](https://user-images.githubusercontent.com/40510496/132482345-ccd9295d-3550-4267-9764-e34093884a43.png)

![image](https://user-images.githubusercontent.com/40510496/132482260-38544b5e-23d1-43ab-8a89-c6bb9358277e.png)

**Comment by geatpy-dev** [comment]
在群里你说此问题已解决。
