### ISSUE TITLE
File "core/scaling.pyx", line 117, in scaling.scaling

### ISSUE THREAD

**Issue by sherryhongxy** [geatpy-dev/geatpy#229]
Traceback (most recent call last):

  File "<ipython-input-59-e50e3db3022d>", line 17, in <module>
    [BestIndi, population] = myAlgorithm.run()  

  File "/Users/hxy/opt/anaconda3/lib/python3.7/site-packages/geatpy/templates/soeas/DE/DE_rand_1_bin/soea_DE_rand_1_bin_templet.py", line 53, in run
    population.FitnV = ea.scaling(population.ObjV, population.CV, self.problem.maxormins)  # 计算适应度

  File "core/scaling.pyx", line 117, in scaling.scaling

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by geatpy-dev** [comment]
检查输入scaling的参数是否合法。因为函数不会对所有项进行合法性检查。

**Comment by sherryhongxy** [comment]
是合法的。代码如下：

class MyProblem(ea.Problem):  # 继承Problem父类
    def __init__(self):
        name = 'MyProblem'  # 初始化name（函数名称，可以随意设置）
        M = 1  # 初始化M（目标维数）
        maxormins = [-1]  # 初始化maxormins（目标最小最大化标记列表，1：最小化该目标；-1：最大化该目标）
        Dim = test_data.shape[0]  # 初始化Dim（决策变量维数）
        varTypes = [1] * test_data.shape[0]  # 初始化varTypes（决策变量的类型，元素为0表示对应的变量是连续的；1表示是离散的）
        lb = [0] * test_data.shape[0] # 决策变量下界
        ub = [1] * test_data.shape[0] # 决策变量上界
        lbin = [1] * test_data.shape[0]  # 决策变量下边界（0表示不包含该变量的下边界，1表示包含）
        ubin = [1] * test_data.shape[0]  # 决策变量上边界（0表示不包含该变量的上边界，1表示包含）
        # 调用父类构造方法完成实例化
        ea.Problem.__init__(self, name, M, maxormins, Dim, varTypes, lb, ub, lbin, ubin)

    def aimFunc(self, pop):  # 目标函数
        Vars = pop.Phen  
        objv = []
        for i in range(Vars.shape[0]):
            objv.append(np.sum(np.array(test_data['day30_avg_settlement_sale_amt'].values)*Vars[i]))

        pop.ObjV = np.array([objv]).T
        print(pop.ObjV.shape)   #(50, 1)
        cv = []
        for i in range(Vars.shape[0]):
            inner_cv = []
            for j in range(A.shape[0]):
                inner_cv.append(A[j]*Vars[i]-B[j])
            inner_cv.append(A3*Vars[i]-C)
            cv.append(inner_cv)
        pop.CV = np.array(cv)    
        print(pop.CV.shape)  #(50, 19)

problem = MyProblem()  
Encoding = 'BG'  
NIND = 50 
Field = ea.crtfld(Encoding, problem.varTypes, problem.ranges, problem.borders) 
population = ea.Population(Encoding, Field, NIND)  
myAlgorithm = ea.soea_SEGA_templet(problem, population)  
myAlgorithm.MAXGEN = 200  
myAlgorithm.mutOper.Pm = 0.5  
myAlgorithm.logTras = 1 
myAlgorithm.verbose = True  
myAlgorithm.drawing = 1 
[BestIndi, population] = myAlgorithm.run()
