### ISSUE TITLE
RuntimeError: error in scaling: ObjV must be a n*1 numpy array. (种群的目标函数值矩阵必须是n行1列的numpy array类型矩阵。)

### ISSUE THREAD

**Issue by chamwen** [geatpy-dev/geatpy#230]
您好，
      使用geatpy做多目标优化时发现，在aimFunc()中设置 pop.ObjV 无效，设置方法类似 `pop.ObjV = np.zeros((pop.sizes, 3))`，（当然目标函数值实际是计算出来的）。初始化时已设置 `M=3, maxormins = [1, -1, -1]`，版本2.6.0
麻烦解答下

**Comment by geatpy-dev** [comment]
python编程基础问题。

**Comment by geatpy-dev** [comment]
你可以单步调试找到问题的根源。

**Comment by chamwen** [comment]
谢谢回复，参考了一些多目标优化的例子
https://github.com/Bardbo/geatpy-Multi-objective-Optimization-for-Shortest-Path/blob/main/code.ipynb
每个目标函数为一列，pop.ObjV的设置也是符合报错所要求的，不是很清楚具体该怎么设置呢，麻烦解释下是什么编程基础问题

**Comment by geatpy-dev** [comment]
scaling里面提示了传入的ObjV只能有一列。而你现在目标个数是3，ObjV有3列，当然不行了。

**Comment by chamwen** [comment]
> scaling里面提示了传入的ObjV只能有一列。而你现在目标个数是3，ObjV有3列，当然不行了。

已解决， 实例化算法模板对象时用的是soea_DE_rand_1_bin_templet，应该采用moea_NSGA3_templet，更换后没报错了
