### ISSUE TITLE
CV函数里面的值都小于0，而且ObjV里面的值都不为空，说明产生可行解了，但是算法模板始终找不到可行解，这是什么原因呢

### ISSUE THREAD

**Issue by TGlove** [geatpy-dev/geatpy#233]
请问为什么在编写完 aimFunc() 这个方法之后，检查了种群的CV 限制条件，是符合的，然后ObjV目标函数也是有值的，说明有可行解

但是为甚么算法模板就是找不到可行解呢？使用的是 soea_psy_EGA_templet 这个多染色体优单目标进化的模板

我的理解是既然CV满足了，ObjV也有值，那应该就产生可行解了啊
但是为什么算法模板还是找不到可行解呢？

**Comment by geatpy-dev** [comment]
你还未理解你当前正在使用的算法的完整流程。

**Comment by TGlove** [comment]
无论算法模板是怎么样的，既然在aimFunc() 这个里面产生可行解了，算法模板不是基于这些可行解进行进化，计算的吗，与流程关系大吗

**Comment by geatpy-dev** [comment]
@TGlove 单步调试可以解决此问题。

**Comment by TGlove** [comment]
问题解决了
