### ISSUE TITLE
  When will version 2.0 be released?

### ISSUE THREAD

**Issue by wuweihust** [geatpy-dev/geatpy#24]
Are there timeline or roadmap about geatpy 2.0？
Very looking forward to the latest version.
Thank you for your awesome work.

**Comment by 1061655504** [comment]
> Are there timeline or roadmap about geatpy 2.0？
> Very looking forward to the latest version.
> Thank you for your awesome work.

About two weeks. So sorry that there is no exact date.

**Comment by wuweihust** [comment]
> 
> 
> > Are there timeline or roadmap about geatpy 2.0？
> > Very looking forward to the latest version.
> > Thank you for your awesome work.
> 
> About two weeks. So sorry that there is no exact date.

Glad to hear that we can see verision 2.0 in about 2 weeks. It doesn't take a long time. That's great!
