### ISSUE TITLE
pyd

### ISSUE THREAD

**Issue by liuaer** [geatpy-dev/geatpy#25]
请问您的论文大概什么时候能够发表，想看源代码，555555

**Comment by 1061655504** [comment]
> 请问您的论文大概什么时候能够发表，想看源代码，555555

您好！下一版本开始将直接呈现python源码。

**Comment by liuaer** [comment]
那真的是太棒了，感谢你们的开源，希望你们能越做越好。




------------------ 原始邮件 ------------------
发件人: "1061655504"<notifications@github.com>; 
发送时间: 2019年6月7日(星期五) 中午11:11
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com>; 
抄送: "白天不懂夜的黑"<542449630@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [geatpy-dev/geatpy] pyd (#25)



 
请问您的论文大概什么时候能够发表，想看源代码，555555
  
您好！下一版本开始将直接呈现python源码。
