### ISSUE TITLE
How to combine the usual Constraint-Handling Technology in Geatpy2

### ISSUE THREAD

**Issue by 0wenwu** [geatpy-dev/geatpy#26]
I am very excited about the Geatpy2 release. 
I am always confused about handling the constraints, which is the key point to the application of EA. 
The punishing function method is quite simple, but once the built-in Constraint-Handling Method does not has good performance, the satisfactory optimization result will not be obtained.
Could you please give some suggestions or introductions about the combination of usual Constraint-Handling Technology with Geatpy2 in the Geatpy Tutorials?
Thanks for your excellent work.

**Comment by geatpy-dev** [comment]
Hello! Geatpy2 has two different methods to handle with constraints now. One is the penalty function method while another one is using the constraint-domination principle. There is a matrix called "CV" in Geatpy2 representing the constraint violation value of each solution x. It will be described detailedly in documents after publishing.

**Comment by 0wenwu** [comment]
> 
> 
> Hello! Geatpy2 has two different methods to handle with constraints now. One is the penalty function method while another one is using the constraint-domination principle. There is a matrix called "CV" in Geatpy2 representing the constraint violation value of each solution x. It will be described detailedly in documents after publishing.

Thx for your rapid reply.
If the documents contain the description about how to customize the constraint handling methods in the algorithm template, it would be more helpful.
Looking forwards to the coming documents.

**Comment by geatpy-dev** [comment]
> > Hello! Geatpy2 has two different methods to handle with constraints now. One is the penalty function method while another one is using the constraint-domination principle. There is a matrix called "CV" in Geatpy2 representing the constraint violation value of each solution x. It will be described detailedly in documents after publishing.
> 
> Thx for your rapid reply.
> If the documents contain the description about how to customize the constraint handling methods in the algorithm template, it would be more helpful.
> Looking forwards to the coming documents.

You're welcome.
