### ISSUE TITLE
为什么我的多目标问题的指标中gd和igd一直为None?

### ISSUE THREAD

**Issue by zhiyunjiang** [geatpy-dev/geatpy#269]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by geatpy-dev** [comment]
没有设置目标函数理论最优参考值，就不会计算GD、IGD等指标。

**Comment by zhiyunjiang** [comment]
目标函数理论最优参考值怎么设置呢
