### ISSUE TITLE
你好，框架中提供的非支配排序方法参考的文献是哪一篇？

### ISSUE THREAD

**Issue by ZhengHui-Z** [geatpy-dev/geatpy#27]
你好，框架中提供的非支配排序方法参考的文献是哪一篇？能提供一下吗？

**Comment by 1061655504** [comment]
> 你好，框架中提供的非支配排序方法参考的文献是哪一篇？能提供一下吗？

您好！有两个非支配排序算子。执行import geatpy as ea后，
执行help(ea.ndsortDED)以及help(ea.ndsortESS)可以查看帮助文档。里面附有参考文献。

**Comment by ZhengHui-Z** [comment]
懂了，非常感谢哦！
