### ISSUE TITLE
module 'geatpy.core.indicator' has no attribute 'ndsortDED'

### ISSUE THREAD

**Issue by penfwang** [geatpy-dev/geatpy#277]
In 2.6.0, ea.indicator.ndsortDED(PF, 1) is used for sorting the individuals.

In 2.7.0, I get the errors: module 'geatpy.core.indicator' has no attribute 'ndsortDED'.

Could you help me solve this issue? Mang thanks!

**Comment by hktkzyx** [comment]
In version 2.7.0, directly use `ea.ndsortDED`

**Comment by geatpy-dev** [comment]
一直就没有ea.indicator.ndsortDED的用法。
