### ISSUE TITLE
请问一下，pyd文件大概什么时候可以开源？

### ISSUE THREAD

**Issue by yyaicc** [geatpy-dev/geatpy#279]
Hi, dears

非常感谢项目组开发了这个开源项目！

想问下，core中的pyd大概什么时候可以开源？

**Comment by geatpy-dev** [comment]
core代码由C和汇编等代码+Python接口组成，编译繁琐，而且代码可读性远不如Python的高，暂时不会开源了。

**Comment by yyaicc** [comment]
> core代码由C和汇编等代码+Python接口组成，编译繁琐，而且代码可读性远不如Python的高，暂时不会开源了。

OK, got it.

Thanks again.
