### ISSUE TITLE
决策变量最优解输出

### ISSUE THREAD

**Issue by liwei066000** [geatpy-dev/geatpy#28]
在多目标求解的结果中，如何输出帕累托最优解对应的各个决策变量的值。

**Comment by 1061655504** [comment]
> 在多目标求解的结果中，如何输出帕累托最优解对应的各个决策变量的值。

您好！调用算法模板后会得到一个非支配种群NDSet，此时通过print(NDSet.Phen)即可查看各个决策变量的值。（Phen是种群个体的表现型，对应着决策变量的值，更多相关属性可详见Population.py源码。）

**Comment by liwei066000** [comment]
谢谢指导！


------------------
小伟信箱


 




------------------ 原始邮件 ------------------
发件人: "1061655504"<notifications@github.com>;
发送时间: 2019年7月15日(星期一) 下午4:43
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com>;
抄送: "李伟"<1538883431@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [geatpy-dev/geatpy] 决策变量最优解输出 (#28)



 
在多目标求解的结果中，如何输出帕累托最优解对应的各个决策变量的值。
  
您好！调用算法模板后会得到一个非支配种群NDSet，此时通过print(NDSet.Phen)即可查看各个决策变量的值。（Phen是种群个体的表现型，对应着决策变量的值，更多相关属性可详见Population.py源码。）

**Comment by remmas** [comment]
您好，我刚接触遗传算法。对您写的目标函数的定义不是太明白，x或者说Vars如何与MyProblem中的决策变量联系在一起

**Comment by 1061655504** [comment]
> 您好，我刚接触遗传算法。对您写的目标函数的定义不是太明白，x或者说Vars如何与MyProblem中的决策变量联系在一起

噢~Vars就是决策变量矩阵。每一列对应一个决策变量，每一行对应一个个体。种群染色体矩阵Chrom解码后得到的表现型矩阵Phen就是决策变量Vars了，Phen是等价于Vars的。现在新版的文档还没完善好，届时可以看得非常明白。

**Comment by remmas** [comment]
嗯嗯，多谢指导。我现在先多看下demo吧，其实还有好多地方不太明白😁，请问文档快出来了吗，相当期待。

**Comment by 1061655504** [comment]
> 嗯嗯，多谢指导。我现在先多看下demo吧，其实还有好多地方不太明白😁，请问文档快出来了吗，相当期待。

文档这个应该最快这周会出炉。其实现在用help命令就可以查看内置的API文档了，比如help(ea.crtint)。

**Comment by remmas** [comment]
好的好的，谢谢。
