### ISSUE TITLE
如何把多任务神经网络的损失作为目标函数?

### ISSUE THREAD

**Issue by RuanGuojie** [geatpy-dev/geatpy#280]
我希望利用geatpy去优化多任务神经网络中不同任务的损失权重，不知道这样可不可行，以及怎样实现?

**Comment by geatpy-dev** [comment]
把优化问题写成问题类，然后调用进化算法求解。

**Comment by RuanGuojie** [comment]
> 把优化问题写成问题类，然后调用进化算法求解。

请问具体如何把优化问题转化呢，可以帮我看看代码吗
