### ISSUE TITLE
您好，运行时出现了这个报错

### ISSUE THREAD

**Issue by mdzyy** [geatpy-dev/geatpy#284]
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 7>()
        21 myAlgorithm.logTras = 0
        22 """===========================调用算法模板进行种群进化======================="""
---> 23 [population, obj_trace, var_trace] = myAlgorithm.run() # 执行算法模板
        24 population.save() # 把最后一代种群的信息保存到文件中
        25 # 输出结果

ValueError: not enough values to unpack (expected 3, got 2)

请问这个是什么原因呢？

**Comment by mdzyy** [comment]
看了FAQ已经解决了，谢谢！

**Comment by geatpy-dev** [comment]
好的。
