### ISSUE TITLE
添加conda源

### ISSUE THREAD

**Issue by luke396** [geatpy-dev/geatpy#287]
您好，发现本项目支持用pip进行安装和包管理，但是并没有上传到anaconda，无法使用conda进行安装和包管理，不知道是否后续有支持conda的计划，还是基于因为其他一些原因未能支持。

**Comment by geatpy-dev** [comment]
您好！尚未发现有此刚需。您可以在conda里创建虚拟环境，然后用虚拟环境里面的python以pip方式进行安装。

**Comment by luke396** [comment]
> 
当然，的确您的方式可以实现。吹毛求疵地说，pip和conda一起使用会把conda构建的虚拟环境弄乱，可能会在后续的某个时刻出现包版本冲突，不过也的确不是刚需。

感谢回复，祝好运。我已经安装并开始研究如何使用Geatpy了。
