### ISSUE TITLE
一次运行10代，和每次运行一代，每次将上次结果通过先验知识传入，结果并不相同

### ISSUE THREAD

**Issue by laye0619** [geatpy-dev/geatpy#294]
GEATPY，首先非常感谢提供这么好的lib！

在moea_demo5中，先验知识是传入的ea.moea_NSGA2_templet函数，通过查看源码，ea.moea_NSGA2_templet好像不接收prophetPop，通过单步调试也可以看到，run函数进来后，prophetPop是None。

我理解是不是应该将prophet通过ea.optimize传入？

我自己测试了一下，通过ea.optimize传入后，run函数的prophetPop是有数据的。

另外想请教一下，如果我每次运行1代，然后下一次运行将上次运行结果res['optPop']作为先验知识传入。这样运行10代，效果是否几乎等同于一次性运行10代的结果？

以上，十分感谢！

**Comment by zeroraiser** [comment]
Thank you. Your email is received and will be handled as soon as possible

**Comment by zzxzfy** [comment]
您好，您的邮件冯颖已收到！

**Comment by laye0619** [comment]
> GEATPY，首先非常感谢提供这么好的lib！
> 
> 在moea_demo5中，先验知识是传入的ea.moea_NSGA2_templet函数，通过查看源码，ea.moea_NSGA2_templet好像不接收prophetPop，通过单步调试也可以看到，run函数进来后，prophetPop是None。
> 
> 我理解是不是应该将prophet通过ea.optimize传入？
> 
> 我自己测试了一下，通过ea.optimize传入后，run函数的prophetPop是有数据的。
> 
> 另外想请教一下，如果我每次运行1代，然后下一次运行将上次运行结果res['optPop']作为先验知识传入。这样运行10代，效果是否几乎等同于一次性运行10代的结果？
> 
> 以上，十分感谢！

之所以需要分批次运行，是因为目标函数运行时间太长，假设种群数量为100，那么运行一代差不多要2-3个小时……所以想请教分批次运行，没批次承接上次运行的结果作为先验知识，是否可行，谢谢！

**Comment by geatpy-dev** [comment]
laye0619你好：你提到的分批次运行的方法，结果与设置很多代是等同的；对于前面的问题，你可以将prophet通过ea.optimize传入，也可以直接调用algorithm.run(prophetPop)传入一个包含先验知识的种群对象。

**Comment by laye0619** [comment]
> laye0619你好：你提到的分批次运行的方法，结果与设置很多代是等同的；对于前面的问题，你可以将prophet通过ea.optimize传入，也可以直接调用algorithm.run(prophetPop)传入一个包含先验知识的种群对象。

十分感谢！

**Comment by laye0619** [comment]
@geatpy-dev , 我又遇到一个问题，还需要请教一下：
我现在是每次跑一代，但是我发现每次跑出来的ObjV都是一样的，我在想是不是因为我在ea.optimize函数传入了seed=1这个参数所致？

如果我想实现每次跑一代这样的逐代进行的方式，seed是不是应该不传入？

还望不吝赐教！

**Comment by laye0619** [comment]
@geatpy-dev 实测下来，每次运行1代，每次运行将上一次运行结果通过prophet传入，运行10次，结果和一次性运行10代结果并不相同，而且差距还很大。我觉得应该不是seed的问题。

新手上路，还望指点。

**Comment by geatpy-dev** [comment]
正常现象，毕竟是EA是个随机优化算法。
