### ISSUE TITLE
Genetic Algorithm Limit for more than 300,000 variables

### ISSUE THREAD

**Issue by SightVanish** [geatpy-dev/geatpy#295]
Can GA(Genetic Algorithm) handle a mixed integer(0-1 problem) non-linear optimization problem with 500,000 variables? One objective function: linear; 80 constraints: 78 are linear, 2 are non-linear. The real challenge is the number of variables. I tried to implement that via geatpy but the model cannot return any feasible results.
I just wonder whether GA is a good option? Should I seek another non-linear solver?

**Comment by geatpy-dev** [comment]
Hi, actually, it's not a good choice to use GA to address your problem.

**Comment by SightVanish** [comment]
Thanks a lot!
