### ISSUE TITLE
M1芯片下，通过arch -arm64安装的geatpy仍存在芯片版本的问题，请问有什么解决办法吗

### ISSUE THREAD

**Issue by PatchouliJY** [geatpy-dev/geatpy#299]
Traceback (most recent call last):
  File "/Users/lixiang/Downloads/NSGAII-ATE.py", line 1, in <module>
    import geatpy as ea
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geatpy/__init__.py", line 11, in <module>
    from geatpy.core.awGA import awGA
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so' ###(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))###, '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so' ###(no such file)###, '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so' ###(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))###

**Comment by zzxzfy** [comment]
您好，您的邮件冯颖已收到！
