### ISSUE TITLE
no mudule named awGA

### ISSUE THREAD

**Issue by CodingThinking** [geatpy-dev/geatpy#3]
当我在mac os x中利用pip安装好geatpy后，在import geatpy as ga语句执行时报出no mudule named awGA 这个错误 我的python版本是3.7

**Comment by ZibinPan** [comment]
您好，非常抱歉，目前geatpy暂无MAC版本，其发行版只支持在windows系统上运行（详见README）。另外有linux版本，因文件过大不便放在github上，日后将在官网上有专属链接进行下载。谢谢反馈！

**Comment by hongweioliver** [comment]
您好， 官网现在好像打不开， 请问怎么样可以找到linux下的版本？ 非常感谢。

**Comment by ZibinPan** [comment]
> 您好， 官网现在好像打不开， 请问怎么样可以找到linux下的版本？ 非常感谢。

您好～官网linux版geatpy下载链接那边还在搞，这周内应该能上线。linux版本文件较大，您可以加我QQ：1061655604，我私发给您～

**Comment by hongweioliver** [comment]
太感谢您了。 我现在不在国内，QQ 等不上， 方便发到我邮箱吗？ 13091715687lhw@gmail.com 
十分感谢。

**Comment by famirtse** [comment]
> > 您好， 官网现在好像打不开， 请问怎么样可以找到linux下的版本？ 非常感谢。
> 
> 您好～官网linux版geatpy下载链接那边还在搞，这周内应该能上线。linux版本文件较大，您可以加我QQ：1061655604，我私发给您～

您好，非常感谢你们编写好用的遗传算法包，请问可以提供Linux平台的安装包吗？已向您的QQ1061655604发送申请了，我的QQ906931630，万分感谢！

**Comment by gaojunyan** [comment]
您好，在官网我并没有看到linux版geatpy下载链接，如果有链接可否发我一个？如果没有，我已加您QQ，或者麻烦您发到我邮箱 1982183239@qq.com。谢谢啦！
