### ISSUE TITLE
关于一些小细节

### ISSUE THREAD

**Issue by ZhengHui-Z** [geatpy-dev/geatpy#30]
在使用的过程中发现一个疑问，望指教。

```
NIND = 100                 # Set the number of individuals.
```
设置种群数量为100个，但是在测试问题中的aimFuc(self, Vars, CV)函数中ObjV维度是<class 'tuple'>: (91, 3)，不应该是(100, 3)吗？

**Comment by 1061655504** [comment]
> 在使用的过程中发现一个疑问，望指教。
> 
> ```
> NIND = 100                 # Set the number of individuals.
> ```
> 
> 设置种群数量为100个，但是在测试问题中的aimFuc(self, Vars, CV)函数中ObjV维度是<class 'tuple'>: (91, 3)，不应该是(100, 3)吗？

您好啊！

在NSGA3算法模板里面的种群初始化工作前，会将种群规模调整为跟参考点数目（91个）一致。详见moea_NSGA3_templet.py中的参考点生成以及种群初始化工作。
