### ISSUE TITLE
Dear developer，is it can be used in genetic programming problem？

### ISSUE THREAD

**Issue by burcewangdlut** [geatpy-dev/geatpy#31]

**Comment by burcewangdlut** [comment]
such as DEAP is can be used in genetic programming （GP）， so if geatpy can be used in GP？

**Comment by 1061655504** [comment]
> such as DEAP is can be used in genetic programming （GP）， so if geatpy can be used in GP？

Not yet, no GP operators are supported in Geatpy. Only GA, DE and ES are supported now. And probably no GP will be supported in Geatpy in the future because we have excogitated a advanced substitute for it. And after everything is ready, it will be supported in Geatpy.

**Comment by 1061655504** [comment]
> > such as DEAP is can be used in genetic programming （GP）， so if geatpy can be used in GP？
> 
> Not yet, no GP operators are supported in Geatpy. Only GA, DE and ES are supported now. And probably no GP will be supported in Geatpy in the future because we have excogitated an advanced substitute for it. And after everything is ready, it will be supported in Geatpy.

看到您的备注是中国人，意思是这样子：Geatpy很大可能不会内置GP的相关算子。
