### ISSUE TITLE
算法入口

### ISSUE THREAD

**Issue by Ashkf** [geatpy-dev/geatpy#312]
目前我找到的执行脚本的入口有两个：

1. geatpy.optimize。demo中多用 `ea.potimize()` 开始程序。
2. Algorithm.run() 。从算法类的成员函数 `run()` 开始程序。

哪一种更好？我猜是第一种
两者有何区别？

**Comment by geatpy-dev** [comment]
第一种是2.7.0版本之后新增的求解器模式的写法，比第二种更简洁一点点。第一种其实是在第二种的基础上再套了一层封装了。
