### ISSUE TITLE
ImportError: cannot import name 'awGA' from 'awGA' (unknown location)

### ISSUE THREAD

**Issue by AcceleratorCheney** [geatpy-dev/geatpy#32]
Traceback (most recent call last):
  File "Untitled 5.py", line 1, in <module>
    import geatpy as ea
  File "/anaconda3/lib/python3.7/site-packages/geatpy/__init__.py", line 42, in <module>
    from awGA import awGA
ImportError: cannot import name 'awGA' from 'awGA' (unknown location)
Mac python3.7

**Comment by 1061655504** [comment]
> Traceback (most recent call last):
> File "Untitled 5.py", line 1, in 
> import geatpy as ea
> File "/anaconda3/lib/python3.7/site-packages/geatpy/**init**.py", line 42, in 
> from awGA import awGA
> ImportError: cannot import name 'awGA' from 'awGA' (unknown location)
> Mac python3.7

您好！
您在Python控制台执行import geatpy然后执行print(geatpy.__version__)看看是什么版本。因为当前版本并没有你上面报错信息里面提到的“init.py”，而是“__init__.py”，此外，“__init__.py”的第42行并不是“from awGA import awGA”这段代码。详见`https://github.com/geatpy-dev/geatpy/blob/master/geatpy/__init__.py`
输出版本号然后告知我们，我们将进行进一步的判断分析。谢谢！

**Comment by ruifeng96150** [comment]
I have the same error today:
```
[root@localhost ~]# pip3 list|grep geatpy
geatpy             2.0.0.post6
[root@localhost ~]# python3
Python 3.6.8 (default, Jun  5 2019, 22:28:09) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import geatpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/geatpy/__init__.py", line 42, in <module>
    from awGA import awGA
ImportError: cannot import name 'awGA'
>>> print(geatpy.version)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'geatpy' is not defined
```

**Comment by 1061655504** [comment]
> I have the same error today:
> 
> ```
> [root@localhost ~]# pip3 list|grep geatpy
> geatpy             2.0.0.post6
> [root@localhost ~]# python3
> Python 3.6.8 (default, Jun  5 2019, 22:28:09) 
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import geatpy
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.6/site-packages/geatpy/__init__.py", line 42, in <module>
>     from awGA import awGA
> ImportError: cannot import name 'awGA'
> >>> print(geatpy.version)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'geatpy' is not defined
> ```

![image](https://user-images.githubusercontent.com/43485717/62024087-42b1b080-b206-11e9-8790-58cf1b72d46c.png)
您这里显示安装的是geatpy2.0.0公测版，2.0.0公测版并不支持Linux。试下执行：pip install --upgrade geatpy进行更新至支持Linux的2.1.0版本。

**Comment by ruifeng96150** [comment]
OK, I got it.   I find that the pip source https://pypi.pubyun.com/simple/, which provide lastest version 2.0.0.post6. when I remove it from config. I got the the lastest version 2.1.0.post1

thanks,

**Comment by 1061655504** [comment]
> OK, I got it. I find that the pip source https://pypi.pubyun.com/simple/, which provide latest version 2.0.0.post6. when I remove it from config. I got the latest version 2.1.0.post1
> 
> thanks,

You're welcome. You did a good job!
