### ISSUE TITLE
RuntimeError:error in moeaplot: The number of ObjVs columns must not be 1. (使用frontplot绘图函数时，ObjV的列数不能为1。)

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#33]
I was trying to solve a small optimization problem using NSGA2. 
In MyProblem.py, I defined the aimFuc function as the following: 
My input format is:
x1 = Vars[:,[0]]
x2 = Vars[:,[1]]
My output is of the format:
obj  =np.array( [[a],[b],[c]] )  #where a,b,c are integers and the len(obj) = len(Vars).
When I was running my main file, I ran across the following error saying my obj shape is wrong:
RuntimeError: error in moeaplot: The number of ObjVs columns must not be 1. (使用frontplot绘图函数时，ObjV的列数不能为1。)
Can anyone help me with this one? Thanks  : )

**Comment by 1061655504** [comment]
> I was trying to solve a small optimization problem using NSGA2.
> In MyProblem.py, I defined the aimFuc function as the following:
> My input format is:
> x1 = Vars[:,[0]]
> x2 = Vars[:,[1]]
> My output is of the format:
> obj =np.array( [[a],[b],[c]] ) #where a,b,c are integers and the len(obj) = len(Vars).
> When I was running my main file, I ran across the following error saying my obj shape is wrong:
> RuntimeError: error in moeaplot: The number of ObjVs columns must not be 1. (使用frontplot绘图函数时，ObjV的列数不能为1。)
> Can anyone help me with this one? Thanks : )

您好！我分析了一下您遇到了两个问题：
1. Geatpy更新的2.1.0版本没有上述判断代码。您安装的应该是2.0.0公测版。
2.在2.0.0公测版里面moeaplot()函数只能绘制二维及以上的目标空间图像。您可以
print(ObjV)看看ObjV是否正常。moeaplot函数要求传入的ObjV是一个目标函数值矩阵，每行对应一个个体，每一列对应一个目标。其API文档可通过help(ea.moeaplot)查看。

**Comment by xrzalreadytaken** [comment]
明白了。moea是针对多个目标函数使用的，所以objv应该对应最起码2个目标函数，因此至少要2列。我的情况要使用soea。多谢~
