### ISSUE TITLE
Mac M1 Run geatpy error :  awGA.cpython-310-darwin.so incompatible arm64

### ISSUE THREAD

**Issue by YangZ2020** [geatpy-dev/geatpy#331]
Hi, thank you for your effort & contribution!
I want to try Geatpy at my Macbook M1 Pro

I have installed latest Anaconda, (Python 3.10 default)
Run pip install geatpy
and installed Cython

When I import package,
import geatpy as gp

The following error appeared:
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 import geatpy as gp
      2 import numpy as np
      3 import scipy as scp

File ~/anaconda3/lib/python3.10/site-packages/geatpy/__init__.py:11
      8 __version__ = "2.7.0"
     10 # import the core
---> 11 from geatpy.core.awGA import awGA
     12 from geatpy.core.boundfix import boundfix
     13 from geatpy.core.bs2int import bs2int

ImportError: dlopen(/Users/zyzy/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so, 0x0002): tried: '/Users/zyzy/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/zyzy/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so' (no such file), '/Users/zyzy/anaconda3/lib/python3.10/site-packages/geatpy/core/awGA.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

How to solve this problem? Very appreciate!!!

**Comment by geatpy-dev** [comment]
Dear Sir/Madem,
It's a difficult problem. Maybe you can utilize Python 3.9 for another try.

**Comment by geatpy-dev** [comment]
Maybe there is something wrong with the installing. Maybe you can reinstall it or utilize another Python version like Python 3.9.

**Comment by YangZ2020** [comment]
Thank you very much.  Python 3.9 import geatpy normally on my macbook pro M1 with no error.
Other function need further test.
