### ISSUE TITLE
运行快速示例出现错误

### ISSUE THREAD

**Issue by ustcmashuai** [geatpy-dev/geatpy#34]
我在运行快速入门中的带约束的多目标优化问题时出现错误提示：
TypeError: __init__() takes 1 positional argument but 10 were given
请问有解吗？

**Comment by 1061655504** [comment]
> 我在运行快速入门中的带约束的多目标优化问题时出现错误提示：
> TypeError: **init**() takes 1 positional argument but 10 were given
> 请问有解吗？

今晚在进行维护，不慎把2.1.0版本删掉了，十点前重新更新。看您的描述，应该是装了2.0.0公测版。

**Comment by ustcmashuai** [comment]
多谢啦！

**Comment by 1061655504** [comment]
> 多谢啦！

这边已更新，可执行pip install --upgrade geatpy进行更新至2.1.0版。您上面的问题即可解决。
