### ISSUE TITLE
SEGA回调函数self.outFunc有问题,之前NSGA中并没有存在该问题

### ISSUE THREAD

**Issue by RebelYoung** [geatpy-dev/geatpy#348]
![image](https://github.com/geatpy-dev/geatpy/assets/59256512/933ae808-15e2-48c6-a068-94ade4e262b6)

我写了个回调函数`call_back2`，`type(call_back2)`输出是`function`，而`type(call_back2)`本身的`type`又不是`str`而是`type`，那么`type(outFunc)`是肯定`!='function'`字符串的。应该改成
```
t=type(func) # 写个函数func
isinstance(outFunc,t) # 结果是Ture
str(type(call_back2))=="<class 'function'>" # 结果也是True 

# 但是源码中用的是
type(self.outFunc) == 'function' # 结果是False

```

**Comment by RebelYoung** [comment]
@geatpy-dev

**Comment by geatpy-dev** [comment]
应该用if not callable(self.outFunc)，之前改过的。代码貌似被后面的人该回去了。你修改一下即可。

**Comment by geatpy-dev** [comment]
修改方法见：[https://github.com/geatpy-dev/geatpy/issues/292](url)
