### ISSUE TITLE
TypeError when running soea demo2

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#36]
I was running the main of soea_demo2. I ran into the following problem:

problem = MyProblem() # 生成问题对象
    ea.Problem.__init__(self, name, M, maxormins, Dim, varTypes, lb, ub, lbin, ubin)
TypeError: __init__() takes 1 positional argument but 10 were given

I didn't make any changes to the code. Is there anything wrong with the code?
Thanks!

**Comment by 1061655504** [comment]
应该是版本不一致问题。2. 1. 0版里面的实例化方法跟2. 0. 0公测版不一样。你描述的这个错误就是用2. 1. 0的demo但调用了2. 0. 0公测版的Problem. py里面的问题类的构造函数。
可用print(ea. __version__) 查看一下版本号～希望问题能尽快解决。

**Comment by xrzalreadytaken** [comment]
已解决。多谢！
