### ISSUE TITLE
How to interpret the pareto front image with many objective functions?

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#37]
I was running an optimization problem with 7 objective functions without any constraints using NSGA2. After running the model, I get the image of pareto front, but find it hard to interpret.

x-axis = Dimension of Number (# of objective functions in my point of view)
y_axis = Function Value
There are 7 lines in the image, the lines are close to each other but they don't coincide.

Can anyone help me interpreting the pareto front image? Or is it possible for the crew in geatpy to add a demo of multiple objective function with more than 3 dimension? Thanks!
￼￼

**Comment by 1061655504** [comment]
> I was running an optimization problem with 7 objective functions without any constraints using NSGA2. After running the model, I get the image of pareto front, but find it hard to interpret.
> 
> x-axis = Dimension of Number (# of objective functions in my point of view)
> y_axis = Function Value
> There are 7 lines in the image, the lines are close to each other but they don't coincide.
> 
> Can anyone help me interpreting the pareto front image? Or is it possible for the crew in geatpy to add a demo of multiple objective function with more than 3 dimension? Thanks!
> ￼￼

This document in the website may help you: 
http://geatpy.com/index.php/2019/07/28/4-%E8%BF%9B%E5%8C%96%E7%AE%97%E6%B3%95%E6%A8%A1%E6%9D%BF/

When using "moeaplot" with more than 3 objective values, the figure will be shown like this:
![image](https://user-images.githubusercontent.com/43485717/62182722-3c4c4180-b38a-11e9-8fcf-de09f5d26fe0.png)

**Comment by Tacitate** [comment]
The figure of many objective optimization is called the "Value Path", not the "Pareto Front" you can add these codes in "Algorithm.py" to control the file name when using "moeaplot()".
![image](https://user-images.githubusercontent.com/44204884/62183343-5ab33c80-b38c-11e9-9a02-745d83d97650.png)
