### ISSUE TITLE
Please add new version with python3.11 on linux

### ISSUE THREAD

**Issue by lzh-0330** [geatpy-dev/geatpy#372]
**Is your feature request related to a problem? Please describe.**
I need use this tool on linux platform, I still can't compile with source code successfully.
UI hope it can be used by python3.11
Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geatpy-dev** [comment]
Well copy that. It will be uploaded recently.

**Comment by lzh-0330** [comment]
Hi
How is going on? :)
I am still looking forward.
Thanks

**Comment by lzh-0330** [comment]
Looking......

**Comment by geatpy-dev** [comment]
@lzh-0330 Sorry that my disk was broken, the code for compiling is missing and will take time to fix.

**Comment by lzh-0330** [comment]
😅🤝

在 2024-08-29 16:14:35，geatpy ***@***.***> 写道：

@lzh-0330 Sorry that my disk was broken, the code for compiling is missing and will take time to fix.

**Comment by zzxzfy** [comment]
您好，您的邮件冯颖已收到！

**Comment by zeroraiser** [comment]
Thank you. Your email is received and will be handled as soon as possible

**Comment by geatpy-dev** [comment]
@lzh-0330 收到，目前已购置新电脑，尽量今日内弄好上传。

**Comment by geatpy-dev** [comment]
@lzh-0330 已编译完成并上传至https://github.com/geatpy-dev/geatpy/releases/tag/v2.7.0

**Comment by lzh-0330** [comment]
ok! got it 
many thanks for your powerful support
👍

在 2024-09-20 18:33:02，geatpy ***@***.***> 写道：

@lzh-0330 已编译完成并上传至https://github.com/geatpy-dev/geatpy/releases/tag/v2.7.0
