### ISSUE TITLE
单目标算法类中对于outFunc的类型检查错误还是没有更新？

### ISSUE THREAD

**Issue by daytime001** [geatpy-dev/geatpy#375]
你好。之前在github已更新修复了此问题。但pip安装包没有同步更新。
![image](https://user-images.githubusercontent.com/42562919/192988400-5c0ca9f8-8eb5-43d6-9f67-1775fa10e264.png)
你可以把github上的Algorithm.py文件幅改本地的~

_Originally posted by @geatpy-dev in https://github.com/geatpy-dev/geatpy/issues/292#issuecomment-1261981155_

**Comment by geatpy-dev** [comment]
pip安装包会在下一版本才把最新的上传。但github会保持源码的最新。

**Comment by daytime001** [comment]
> pip安装包会在下一版本才把最新的上传。但github会保持源码的最新。

pip上一次更新还是22年1月（捂脸）
