### ISSUE TITLE
网站进不去了，核心代码开源吗，方便后来者维护

### ISSUE THREAD

**Issue by lizhuang2511** [geatpy-dev/geatpy#384]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geatpy-dev** [comment]
算子代码开源了反而会极大地增加后来者维护了//因为用了C、以及部分汇编写，代码极其复杂。好在算子是与EA框架是独立的。后来者可以用Python自定义函数的方式自定义算子就OK了。EA框架是完全开源的。
