### ISSUE TITLE
如何解決：ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject的問題

### ISSUE THREAD

**Issue by Jiayu320** [geatpy-dev/geatpy#385]
import geatpy as ea
  File "C:\Users\JIAYU\anaconda3\envs\AIconcept\lib\site-packages\geatpy\__init__.py", line 11, in <module>
    from geatpy.core.awGA import awGA
  File "core\c\awGA.pyx", line 1, in init awGA
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by Jiayu320** [comment]
這個問題是和numpy的兼容問題嗎？
我的numpy版本是1.26.4

**Comment by Jiayu320** [comment]
python版本換做3.8就解決了

**Comment by Ateda** [comment]
我用的是python3.12，然后安装选的是发布的适配python12的安装包，numpy直接pip install numpy，没出问题
