### ISSUE TITLE
AttributeError: module 'geatpy' has no attribute 'Problem'

### ISSUE THREAD

**Issue by huangshizhi** [geatpy-dev/geatpy#39]
执行 ../demo/soea_demo/soea_demo1/main.py 就报错，提示 AttributeError: module 'geatpy' has no attribute 'Problem'

**Comment by 1061655504** [comment]
> 执行 ../demo/soea_demo/soea_demo1/main.py 就报错，提示 AttributeError: module 'geatpy' has no attribute 'Problem'

您好！先执行import geatpy; print(geatpy.__version__)检查一下安装的版本。旧版（Geatpy1.x）里面没有这个Problem模块，可通过pip install --upgrade geatpy进行更新。

**Comment by huangshizhi** [comment]
不好意思，我使用的是Geatpy1.x,升级后没问题了，谢谢

**Comment by 1061655504** [comment]
> 不好意思，我使用的是Geatpy1.x,升级后没问题了，谢谢

好的，不客气~~
