### ISSUE TITLE
submit...maybe a bug?

### ISSUE THREAD

**Issue by iceiceiceee** [geatpy-dev/geatpy#4]
when use sga_code_templet in my code,  report index error in line 139:
`var_trace[gen,:] = variable[bestIdx, :] # 记录当代最优的控制变量值.`  

Debug geatpy\source-code\templets\sga_code_templet.py, in line 179:
`variable = ga.bs2int(SelCh, FieldD).astype('int64')`

maybe it should be:
`variable = ga.bs2int(Chrom, FieldD).astype('int64')`

cause the index in line 139 is acquired from objv in line 130, and objv has changed in line 171 function ga.reins, so the dimensions of Objv and Selch are different.

thanks for apply.

**Comment by geatpy-dev** [comment]
> when use sga_code_templet in my code, report index error in line 139:
> `var_trace[gen,:] = variable[bestIdx, :] # 记录当代最优的控制变量值.`
> 
> Debug geatpy\source-code\templets\sga_code_templet.py, in line 179:
> `variable = ga.bs2int(SelCh, FieldD).astype('int64')`
> 
> maybe it should be:
> `variable = ga.bs2int(Chrom, FieldD).astype('int64')`
> 
> cause the index in line 139 is acquired from objv in line 130, and objv has changed in line 171 function ga.reins, so the dimensions of Objv and Selch are different.
> 
> thanks for apply.

The 'variable' in line 139 is the result of decoding the Chromosome matrix('Chrom'). 

Is there any chance you could provide a complete, minimal, self contained example that we can run to try and reproduce the issue? Otherwise it is hard to see what is going on to cause the issue.


> when use sga_code_templet in my code, report index error in line 139:
> `var_trace[gen,:] = variable[bestIdx, :] # 记录当代最优的控制变量值.`
> 
> Debug geatpy\source-code\templets\sga_code_templet.py, in line 179:
> `variable = ga.bs2int(SelCh, FieldD).astype('int64')`
> 
> maybe it should be:
> `variable = ga.bs2int(Chrom, FieldD).astype('int64')`
> 
> cause the index in line 139 is acquired from objv in line 130, and objv has changed in line 171 function ga.reins, so the dimensions of Objv and Selch are different.
> 
> thanks for apply.

Yes, you're right. Thanks a lot and we will rectify it soon. 
There is good news for you that the next version of Geatpy will offer DE and many other algorithms.

**Comment by geatpy-dev** [comment]
> when use sga_code_templet in my code, report index error in line 139:
> `var_trace[gen,:] = variable[bestIdx, :] # 记录当代最优的控制变量值.`
> 
> Debug geatpy\source-code\templets\sga_code_templet.py, in line 179:
> `variable = ga.bs2int(SelCh, FieldD).astype('int64')`
> 
> maybe it should be:
> `variable = ga.bs2int(Chrom, FieldD).astype('int64')`
> 
> cause the index in line 139 is acquired from objv in line 130, and objv has changed in line 171 function ga.reins, so the dimensions of Objv and Selch are different.
> 
> thanks for apply.

Yes, you're right. Thanks a lot and we will rectify it soon. 
There is good news for you that the next version of Geatpy will offer DE and many other algorithms.
