### ISSUE TITLE
能否类似Gurobi，Cplex优化器那样，求解*.lp文件

### ISSUE THREAD

**Issue by huangshizhi** [geatpy-dev/geatpy#40]
geatpy能否提供类似Gurobi，Cplex优化器那样的接口，可以先读取lp或MPS类型的模型文件，然后求解问题；
如read(test.lp),读取对应的模型文件，然后使用geatpy的遗传算法进行求解！谢谢！

**Comment by 1061655504** [comment]
> geatpy能否提供类似Gurobi，Cplex优化器那样的接口，可以先读取lp或MPS类型的模型文件，然后求解问题；
> 如read(test.lp),读取对应的模型文件，然后使用geatpy的遗传算法进行求解！谢谢！

有一些其他的Python库可以很高效地读取文件的数据，比如Numpy、Pandas、Openpyxl等。如果是类似表格的数据（不限后缀），可以用Numpy的loadtxt函数快捷地读取。

**Comment by 1061655504** [comment]
如果没有问题这个issue就将被关掉了噢。

**Comment by wordcount** [comment]
> > geatpy能否提供类似Gurobi，Cplex优化器那样的接口，可以先读取lp或MPS类型的模型文件，然后求解问题；
> > 如read(test.lp),读取对应的模型文件，然后使用geatpy的遗传算法进行求解！谢谢！
> 
> 有一些其他的Python库可以很高效地读取文件的数据，比如Numpy、Pandas、Openpyxl等。如果是类似表格的数据（不限后缀），可以用Numpy的loadtxt函数快捷地读取。

答非所问，是机器自动回答的？
