### ISSUE TITLE
关于多种群求解VRP 问题编码

### ISSUE THREAD

**Issue by qinhuai0607010** [geatpy-dev/geatpy#41]
我现在需要求解VRPTW问题，自己用python编写的多种群编码方式如下，k一般为2或3
![x](https://user-images.githubusercontent.com/37402238/63631705-b99f6500-c65d-11e9-97d3-6af6e29f73f3.png)

经群里咨询geatpy开发的博士，对每辆车的路径编写一个染色体来处理，但是参照多种群模板
![y](https://user-images.githubusercontent.com/37402238/63631732-fe2b0080-c65d-11e9-8d14-2ca537ebd58b.png)

我并不知道每辆车具体分哪些任务，所以这个field2(及field3)并不知道从第几个任务开始设置新的染色体，如果随机切割的话，在交叉变异时该车辆的任务没有变化，只是顺序变了而已？望解答？

**Comment by Haofenger** [comment]
这是一个十分有趣的问题，欢迎添加QQ：784068941进行深入的交流~

**Comment by Haofenger** [comment]
经过深入交流已基本解决问题。
