### ISSUE TITLE
DLL load failed: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by ICESDHR** [geatpy-dev/geatpy#42]
按照网站提示安装了github上的最新版本还是报这个错

**Comment by 1061655504** [comment]
> 按照网站提示安装了github上的最新版本还是报这个错

您好！请提供系统及python版本以及完整的执行代码或步骤描述以便这边工作人员能够重现出您遇到的问题噢。

**Comment by ICESDHR** [comment]
win10 python3.6.9（64位） 使用命令python setup.py install安装的
把python环境改为32位可以正常使用了

**Comment by ICESDHR** [comment]
> > 按照网站提示安装了github上的最新版本还是报这个错
> 
> 您好！请提供系统及python版本以及完整的执行代码或步骤描述以便这边工作人员能够重现出您遇到的问题噢。

win10 python3.6.9（64位） 使用命令python setup.py install安装的
把python环境改为32位可以正常使用了

**Comment by ICESDHR** [comment]
哥 64位的问题尽快解决呀~

**Comment by ICESDHR** [comment]
> > > 按照网站提示安装了github上的最新版本还是报这个错
> > 
> > 
> > 您好！请提供系统及python版本以及完整的执行代码或步骤描述以便这边工作人员能够重现出您遇到的问题噢。
> 
> win10 python3.6.9（64位） 使用命令python setup.py install安装的
> 把python环境改为32位可以正常使用了

哥 64位的问题尽快解决呀~

**Comment by 1061655504** [comment]
> > > > 按照网站提示安装了github上的最新版本还是报这个错
> > > 
> > > 
> > > 您好！请提供系统及python版本以及完整的执行代码或步骤描述以便这边工作人员能够重现出您遇到的问题噢。
> > 
> > 
> > win10 python3.6.9（64位） 使用命令python setup.py install安装的
> > 把python环境改为32位可以正常使用了
> 
> 哥 64位的问题尽快解决呀~

这边测试未能复现你遇到的问题，github下载的源码可以正常安装，你把本地已安装过的文件彻底删除后重新安装试一下。一般安装到的路径是Python目录/Lib/site-packages/，把该目录下的有geatpy字样的文件夹删除，然后重新安装就好了。或者直接pip install geatpy。

**Comment by ICESDHR** [comment]
> > > > > 按照网站提示安装了github上的最新版本还是报这个错
> > > > 
> > > > 
> > > > 您好！请提供系统及python版本以及完整的执行代码或步骤描述以便这边工作人员能够重现出您遇到的问题噢。
> > > 
> > > 
> > > win10 python3.6.9（64位） 使用命令python setup.py install安装的
> > > 把python环境改为32位可以正常使用了
> > 
> > 
> > 哥 64位的问题尽快解决呀~
> 
> 这边测试未能复现你遇到的问题，github下载的源码可以正常安装，你把本地已安装过的文件彻底删除后重新安装试一下。一般安装到的路径是Python目录/Lib/site-packages/，把该目录下的有geatpy字样的文件夹删除，然后重新安装就好了。或者直接pip install geatpy。

我这边不停复现这个问题，我用pip show geatpy命令找到位置，然后删除geatpy和geatpy-2.2.1.dist-inf两个文件夹，然后不管通过哪种方式安装都还是这个错误。
PS：demo/moea_demo/moea_demo3运行不了，报错如下
`File "core\ndsortESS.pyx", line 143, in ndsortESS.ndsortESS
  File "core\ndsortESS.pyx", line 27, in ndsortESS._ndsortESS
ValueError: Buffer dtype mismatch, expected 'long_t' but got 'int'`

**Comment by ICESDHR** [comment]
> > > > > > 按照网站提示安装了github上的最新版本还是报这个错
> > > > > 
> > > > > 
> > > > > 您好！请提供系统及python版本以及完整的执行代码或步骤描述以便这边工作人员能够重现出您遇到的问题噢。
> > > > 
> > > > 
> > > > win10 python3.6.9（64位） 使用命令python setup.py install安装的
> > > > 把python环境改为32位可以正常使用了
> > > 
> > > 
> > > 哥 64位的问题尽快解决呀~
> > 
> > 
> > 这边测试未能复现你遇到的问题，github下载的源码可以正常安装，你把本地已安装过的文件彻底删除后重新安装试一下。一般安装到的路径是Python目录/Lib/site-packages/，把该目录下的有geatpy字样的文件夹删除，然后重新安装就好了。或者直接pip install geatpy。
> 
> 我这边不停复现这个问题，我用pip show geatpy命令找到位置，然后删除geatpy和geatpy-2.2.1.dist-inf两个文件夹，然后不管通过哪种方式安装都还是这个错误。
> PS：demo/moea_demo/moea_demo3运行不了，报错如下
> `File "core\ndsortESS.pyx", line 143, in ndsortESS.ndsortESS File "core\ndsortESS.pyx", line 27, in ndsortESS._ndsortESS ValueError: Buffer dtype mismatch, expected 'long_t' but got 'int'`

PS中的问题根据网站中的【13】号公告已解决
64位的问题还待解决T.T

**Comment by geatpy-dev** [comment]
> > > > > > > 按照网站提示安装了github上的最新版本还是报这个错
> > > > > > 
> > > > > > 
> > > > > > 您好！请提供系统及python版本以及完整的执行代码或步骤描述以便这边工作人员能够重现出您遇到的问题噢。
> > > > > 
> > > > > 
> > > > > win10 python3.6.9（64位） 使用命令python setup.py install安装的
> > > > > 把python环境改为32位可以正常使用了
> > > > 
> > > > 
> > > > 哥 64位的问题尽快解决呀~
> > > 
> > > 
> > > 这边测试未能复现你遇到的问题，github下载的源码可以正常安装，你把本地已安装过的文件彻底删除后重新安装试一下。一般安装到的路径是Python目录/Lib/site-packages/，把该目录下的有geatpy字样的文件夹删除，然后重新安装就好了。或者直接pip install geatpy。
> > 
> > 
> > 我这边不停复现这个问题，我用pip show geatpy命令找到位置，然后删除geatpy和geatpy-2.2.1.dist-inf两个文件夹，然后不管通过哪种方式安装都还是这个错误。
> > PS：demo/moea_demo/moea_demo3运行不了，报错如下
> > `File "core\ndsortESS.pyx", line 143, in ndsortESS.ndsortESS File "core\ndsortESS.pyx", line 27, in ndsortESS._ndsortESS ValueError: Buffer dtype mismatch, expected 'long_t' but got 'int'`
> 
> PS中的问题根据网站中的【13】号公告已解决
> 64位的问题还待解决T.T

您好！您可以加一下工作人员QQ：1061655504帮您直接远程解决一下噢~
