### ISSUE TITLE
How to deal with conditional constraints?

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#45]
Hi,  I'm writing program that involves a conditional constraint:

if abs(x1-c) = 0, then x2 = 0,
 where x1 and x2 are decision variables.

I heard that  there are ways to express this using big M method, but is there any bettter way to formulate this constriant in geatpy?

Thanks

**Comment by 1061655504** [comment]
In this case you can try to change the segment of the chromosome which stands for the x2 directly instead of doing other things like punishing or building a CV matrix to handle the constraint,  because x2 should be 0 when x1 is equal to c, right?

**Comment by ustcmashuai** [comment]
Sorry, I don't know whether there is a better way. Maybe you can ask the geatpy programmer.


Best,
Shuai




------------------ 原始邮件 ------------------
发件人: "xrzalreadytaken"<notifications@github.com>;
发送时间: 2019年9月18日(星期三) 下午2:57
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [geatpy-dev/geatpy] How to deal with conditional constraints? (#45)




Hi,  I'm writing program that involves a conditional constraint:
 
if abs(x1-c) = 0, then x2 = 0,
 where x1 and x2 are decision variables.
 
I heard that  there are ways to express this using big M method, but is there any bettter way to formulate this constriant in geatpy?
 
Thanks

**Comment by xrzalreadytaken** [comment]
> In this case you can try to change the segment of the chromosome which stands for the x2 directly instead of doing other things like punishing or building a CV matrix to handle the constraint, because x2 should be 0 when x1 is equal to c, right?

Could you please be more explicit? I cannot fully get it.Do you mean I should add some code in my aimFunc() in problem.py file, or in the Population.py file? If in Population.py file, which function should I change? Thanks!

**Comment by 1061655504** [comment]
@xrzalreadytaken
For example,  if Encoding is 'RI',  then add these codes in your aimFunc() :
x1 = pop.Phen[:, [0]]
idx = np.where(x1 == c) [0]
pop.Chrom[idx, 1] = 0 # Change the chromosomes directly to let x2 is equal to 0. 

You can add QQ：1061655504 to chat with me more easily. 
Thx.

**Comment by xrzalreadytaken** [comment]
> For example, if Encoding is 'RI', then add these codes in your aimFunc() :
> x1 = pop.Phen[:, [0]]
> idx = np.where(x1 == c) [0]
> pop.Chrom[idx, 1] = 0 # Change the chromosomes directly to let x2 is equal to 0.
> 
> You can add QQ：1061655504 to chat with me more easily.
> Thx.

Problem solved. Thanks so much!
