### ISSUE TITLE
可变长度的编码

### ISSUE THREAD

**Issue by HaoLiuwide** [geatpy-dev/geatpy#46]
我现在遇到一个无人机路径优化问题，但麻烦的是路径经过的点的个数是不确定的，这种需要可变长度的编码吗？有其他解决方案吗？

**Comment by 1061655504** [comment]
> 我现在遇到一个无人机路径优化问题，但麻烦的是路径经过的点的个数是不确定的，这种需要可变长度的编码吗？有其他解决方案吗？

遗传算法求解路径优化问题目前比较流行的方法是使用“**优先级编码**”。可以参考这篇博客：
https://blog.csdn.net/weixin_37790882/article/details/100622338
或者下载这本《网络模型与多目标优化》资料，里面有非常多关于如何利用遗传算法求解路径优化及其他网络模型的案例，下载地址：
https://download.csdn.net/download/weixin_37790882/11699834

**Comment by HaoLiuwide** [comment]
> > 我现在遇到一个无人机路径优化问题，但麻烦的是路径经过的点的个数是不确定的，这种需要可变长度的编码吗？有其他解决方案吗？
> 
> 遗传算法求解路径优化问题目前比较流行的方法是使用“**优先级编码**”。可以参考这篇博客：
> https://blog.csdn.net/weixin_37790882/article/details/100622338
> 或者下载这本《网络模型与多目标优化》资料，里面有非常多关于如何利用遗传算法求解路径优化及其他网络模型的案例，下载地址：
> https://download.csdn.net/download/weixin_37790882/11699834

您说的这种方法确实能有效解决结点数目较少的问题。但我的问题比较复杂，结点的数目有上百个，而最终的最优解只经过十几个结点，这样的话，染色体矩阵是一个稀疏矩阵，所以我认为还是需要可变长度的编码。

**Comment by l976308589** [comment]
无人机的问题使用强化学习更好，有兴趣可以交流

**Comment by 1061655504** [comment]
> > > 我现在遇到一个无人机路径优化问题，但麻烦的是路径经过的点的个数是不确定的，这种需要可变长度的编码吗？有其他解决方案吗？
> > 
> > 
> > 遗传算法求解路径优化问题目前比较流行的方法是使用“**优先级编码**”。可以参考这篇博客：
> > https://blog.csdn.net/weixin_37790882/article/details/100622338
> > 或者下载这本《网络模型与多目标优化》资料，里面有非常多关于如何利用遗传算法求解路径优化及其他网络模型的案例，下载地址：
> > https://download.csdn.net/download/weixin_37790882/11699834
> 
> 您说的这种方法确实能有效解决结点数目较少的问题。但我的问题比较复杂，结点的数目有上百个，而最终的最优解只经过十几个结点，这样的话，染色体矩阵是一个稀疏矩阵，所以我认为还是需要可变长度的编码。

噢，那这样的话可就得针对这个可变长编码去设计专门的算子才能求解。平常像TSP、机器人走迷宫之类的问题，1000个以内的结点用经典的如排列编码、优先级编码基本可以有效求解。所以你看看能不能尽量把特殊编码划归为经典编码，不然那个编程量会比较大。

**Comment by HaoLiuwide** [comment]
> > > > 我现在遇到一个无人机路径优化问题，但麻烦的是路径经过的点的个数是不确定的，这种需要可变长度的编码吗？有其他解决方案吗？
> > > 
> > > 
> > > 遗传算法求解路径优化问题目前比较流行的方法是使用“**优先级编码**”。可以参考这篇博客：
> > > https://blog.csdn.net/weixin_37790882/article/details/100622338
> > > 或者下载这本《网络模型与多目标优化》资料，里面有非常多关于如何利用遗传算法求解路径优化及其他网络模型的案例，下载地址：
> > > https://download.csdn.net/download/weixin_37790882/11699834
> > 
> > 
> > 您说的这种方法确实能有效解决结点数目较少的问题。但我的问题比较复杂，结点的数目有上百个，而最终的最优解只经过十几个结点，这样的话，染色体矩阵是一个稀疏矩阵，所以我认为还是需要可变长度的编码。
> 
> 噢，那这样的话可就得针对这个可变长编码去设计专门的算子才能求解。平常像TSP、机器人走迷宫之类的问题，1000个以内的结点用经典的如排列编码、优先级编码基本可以有效求解。所以你看看能不能尽量把特殊编码划归为经典编码，不然那个编程量会比较大。

谢谢，我试试
