### ISSUE TITLE
如何设置初始解产生策略

### ISSUE THREAD

**Issue by HaoLiuwide** [geatpy-dev/geatpy#47]
我遇到的问题解空间太大，如果随机尝试解，不能找到符合约束条件的解，因此必须产生大量的随机的有效解，如何设置呢？

**Comment by 1061655504** [comment]
> 我遇到的问题解空间太大，如果随机尝试解，不能找到符合约束条件的解，因此必须产生大量的随机的有效解，如何设置呢？

可以在执行脚本中的实例化算法模板对象之前添加一个“循环尝试初始化可行染色体”的一段代码，代码如下：

`for i in range(100):
    tempPop = ea.Population(Encoding, Field, NIND)
    tempPop.initChrom(NIND) # 初始化种群染色体矩阵
    problem.aimFunc(tempPop) # 计算种群的目标函数值
    feasible = np.where(np.all(tempPop.CV <= 0, 1))[0] # 找到可行个体
    if len(feasible) > 0:
        if i == 0:
            population = tempPop[feasible]
        else:
            population = population + tempPop[feasible]
    if population.sizes >= NIND:
        break
if population.Chrom is not None:
    population = population[:NIND]`

以上代码的具体插入位置为：
![image](https://user-images.githubusercontent.com/43485717/65366203-75e74d80-dc53-11e9-974b-1f6f6deefc5d.png)

注：上述插入的代码通过不断的循环来尝试生成满足约束条件的个体染色体。如果第一遍循环还没生成足够的染色体，则继续循环生成。

**Comment by HaoLiuwide** [comment]
> > 我遇到的问题解空间太大，如果随机尝试解，不能找到符合约束条件的解，因此必须产生大量的随机的有效解，如何设置呢？
> 
> 可以在执行脚本中的实例化算法模板对象之前添加一个“循环尝试初始化可行染色体”的一段代码，代码如下：
> 
> `for i in range(100): tempPop = ea.Population(Encoding, Field, NIND) tempPop.initChrom(NIND) # 初始化种群染色体矩阵 problem.aimFunc(tempPop) # 计算种群的目标函数值 feasible = np.where(np.all(tempPop.CV <= 0, 1))[0] # 找到可行个体 if len(feasible) > 0: if i == 0: population = tempPop[feasible] else: population = population + tempPop[feasible] if population.sizes >= NIND: break if population.Chrom is not None: population = population[:NIND]`
> 
> 以上代码的具体插入位置为：
> ![image](https://user-images.githubusercontent.com/43485717/65366203-75e74d80-dc53-11e9-974b-1f6f6deefc5d.png)
> 
> 注：上述插入的代码通过不断的循环来尝试生成满足约束条件的个体染色体。如果第一遍循环还没生成足够的染色体，则继续循环生成。

不好意思，我的说法有问题：
我的初始解已经通过其他程序计算得到，现在需要将计算得到的解作为初始种群。

**Comment by 1061655504** [comment]
@HaoLiuwide 
那更加简单呀，先根据已得到的解创建一条或若干条染色体（有1个已知解就创建对应的一条染色体，有2个就创建两条，以此类推），再利用numpy的tile()函数将刚刚创建好的染色体复制若干份，使得生成的染色体矩阵的行数与种群规模相等，这样就完成初始化种群染色体了（注意染色体矩阵的类型要符合Geatpy数据结构，即染色体矩阵是Numpy array类型，每一行代表一个个体的染色体）。如果要增加初始染色体的随机性，则对其进行轻微的高斯变异就好了。

**Comment by HaoLiuwide** [comment]
是的，我就是不知道把染色体矩阵赋给谁？是先把染色体赋给tempPop，然后population = tempPop吗？

> @HaoLiuwide
> 那更加简单呀，先根据已得到的解创建一条或若干条染色体（有1个已知解就创建对应的一条染色体，有2个就创建两条，以此类推），再利用numpy的tile()函数将刚刚创建好的染色体复制若干份，使得生成的染色体矩阵的行数与种群规模相等，这样就完成初始化种群染色体了（注意染色体矩阵的类型要符合Geatpy数据结构，即染色体矩阵是Numpy array类型，每一行代表一个个体的染色体）。如果要增加初始染色体的随机性，则对其进行轻微的高斯变异就好了。

是的，我就是不知道把染色体矩阵赋给谁？是先把染色体赋给tempPop，然后population = tempPop吗？

**Comment by 1061655504** [comment]
@HaoLiuwide 赋值给population的Chrom属性。（Population类的属性定义详见Population.py文件）

**Comment by HaoLiuwide** [comment]
> @HaoLiuwide 赋值给population的Chrom属性。（Population类的属性定义详见Population.py文件）

谢谢，我试试
