### ISSUE TITLE
结果出现不满足约束的点

### ISSUE THREAD

**Issue by HaoLiuwide** [geatpy-dev/geatpy#48]
如题：
            if shift_h <= 30 and shift_v <= 30:
                cv_value = -100
            else:
                cv_value = 100
cv.append(cv_value)
pop.Cv = np.array([cv]).T
我已经将对应解得cv置为正数了，结果中还是出现不满足约束的解，而且保存的cv文件中全为0.
请问这是怎么回事？

**Comment by 1061655504** [comment]
> 如题：
> if shift_h <= 30 and shift_v <= 30:
> cv_value = -100
> else:
> cv_value = 100
> cv.append(cv_value)
> pop.Cv = np.array([cv]).T
> 我已经将对应解得cv置为正数了，结果中还是出现不满足约束的解，而且保存的cv文件中全为0.
> 请问这是怎么回事？

种群类的CV属性是大写的CV噢。
如果遇到疑惑的代码问题可以把完整测试代码发至邮箱mathscut@163.com这边客服帮忙测试和解答。

**Comment by HaoLiuwide** [comment]
> > 如题：
> > if shift_h <= 30 and shift_v <= 30:
> > cv_value = -100
> > else:
> > cv_value = 100
> > cv.append(cv_value)
> > pop.Cv = np.array([cv]).T
> > 我已经将对应解得cv置为正数了，结果中还是出现不满足约束的解，而且保存的cv文件中全为0.
> > 请问这是怎么回事？
> 
> 种群类的CV属性是大写的CV噢。
> 如果遇到疑惑的代码问题可以把完整测试代码发至邮箱[mathscut@163.com](mailto:mathscut@163.com)这边客服帮忙测试和解答。

非常感谢！！！
