### ISSUE TITLE
Really sad to find it's only for Windows

### ISSUE THREAD

**Issue by tony-tian** [geatpy-dev/geatpy#5]
Hey, guys! I'm really willing to try this new "seeming wonderful" toolbox, but it turned me down while I found the modules all folded by .pyd files. 
Feel sad about it. 
Really hope there could be mac version or linux version. If it happens someday, I will really appreciate!

**Comment by geatpy-dev** [comment]
> Hey, guys! I'm really willing to try this new "seeming wonderful" toolbox, but it turned me down while I found the modules all folded by .pyd files.
> Feel sad about it.
> Really hope there could be mac version or linux version. If it happens someday, I will really appreciate!

I am sorry that other versions are too big to upload. You can send an email to mathscut@163.com to get mac version or linux version now.
