### ISSUE TITLE
The problem of decision variables

### ISSUE THREAD

**Issue by yf950919** [geatpy-dev/geatpy#51]
What should I do if the decision variable is an array?

**Comment by yf950919** [comment]
若我的决策变量为0或1的一个数，一共有23个，即一个一行23列矩阵，那么代码中该如何表示它，目前我只理解了单个数的情况

**Comment by 1061655504** [comment]
> 若我的决策变量为0或1的一个数，一共有23个，即一个一行23列矩阵，那么代码中该如何表示它，目前我只理解了单个数的情况

你在自定义问题类那里设置Dim = 23（即决策变量是23个），然后下界lb = [0] * Dim，上界ub = [1] * Dim，这样就好啦~

**Comment by yf950919** [comment]
好的，谢谢
