### ISSUE TITLE
add a progress bar?

### ISSUE THREAD

**Issue by CodingThinking** [geatpy-dev/geatpy#52]
我注意到算法结束后可以给计算过程绘图，但是试用中发现比较在乎的还是能够实时看到计算过程，特别是计算问题比较大比较慢的时候。所以是否有可能在遗传算法过程中增加一个监控变量变化规律的功能？

**Comment by 1061655504** [comment]
> 我注意到算法结束后可以给计算过程绘图，但是试用中发现比较在乎的还是能够实时看到计算过程，特别是计算问题比较大比较慢的时候。所以是否有可能在遗传算法过程中增加一个监控变量变化规律的功能？

噢~你可以在算法模板类的stat()函数里面添加print()代码打印想要的变量来输出每一代的情况。位置在"Algorithm.py"文件里面的stat()函数（这个文件中有两个stat()函数，一个是单目标算法模板类的，另一个是多目标算法模板类的）。

**Comment by geatpy-dev** [comment]
该问题似乎已经得到解决，jazzbin暂时不在，我这里就把该问题关闭啦~
