### ISSUE TITLE
是否能提供moda/d算法的模板，非常感谢

### ISSUE THREAD

**Issue by ZhengHui-Z** [geatpy-dev/geatpy#53]

**Comment by geatpy-dev** [comment]
@ZhengHui-Z 您好！目前我们实验感觉到MOEA/D的整体性能比较低，故暂不提供内置的MOEA/D算法模板。可以参照MOEA/D相关论文在框架中自定义一个（我记得好像代码不是很长的）。待高性能MOEA/D研究出来后，一定马上更新噢~
