### ISSUE TITLE
pop.CV计算不正确

### ISSUE THREAD

**Issue by xrzalreadytaken** [geatpy-dev/geatpy#54]
你好，我在使用soea_DE_rand_1_L_templet运行一个单目标多限制条件的最优化问题。
我的变量一共有14位

>         Vars = pop.Phen #决策变量矩阵
>         m1 = Vars[:,[0]]
>         m2 = Vars[:,[1]]
>         delta_d = {'AR1_1':Vars[:,[2]],
>                    'AR1_2':Vars[:,[3]],
>                    'AR2_1':Vars[:,[4]],
>                    'AR2_2':Vars[:,[5]],
>                    'AR3_1':Vars[:,[6]],
>                    'AR3_2':Vars[:,[7]],
>                    'AP1_1':Vars[:,[8]],
>                    'AP1_2':Vars[:,[9]],
>                    'AP2_1':Vars[:,[10]],
>                    'AP2_2':Vars[:,[11]],
>                    'AP3_1':Vars[:,[12]],
>                    'AP3_2':Vars[:,[13]]}
模型给出的结果为 [5,10,-1,0,2,0,-4,0,-1,-3,0,-2,0,-2]。
我的限制条件共有36项，为 

>        sum_adj = abs(delta_d['AR1_1'])+abs(delta_d['AR1_2'])+abs(delta_d['AR2_1'])+abs(delta_d['AR2_2'])+abs(delta_d['AR3_1'])+ abs(delta_d['AR3_2'])+ abs(delta_d['AP1_1'])+ abs(delta_d['AP1_2'])+abs(delta_d['AP2_1'])+ abs(delta_d['AP2_2'])+ abs(delta_d['AP3_1'])+ abs(delta_d['AP3_2'])

>        qualification_list = [
>                         sum_adj - int(self.params['ADJUST_TOTAL'][0]),
>                         m1+1-m2,
>                         1-self.redmpt['AR1'] - delta_d['AR1_1'],
>                         1-self.redmpt['AR1']-delta_d['AR1_1']-delta_d['AR1_2'],
>                         1-self.redmpt['AR2'] - delta_d['AR2_1'],
>                         1-self.redmpt['AR2']-delta_d['AR2_1']-delta_d['AR2_2'],
>                         1-self.redmpt['AR3'] - delta_d['AR3_1'],
>                         1-self.redmpt['AR3']-delta_d['AR3_1']-delta_d['AR3_2'],
>                         1-self.redmpt['AP1'] - delta_d['AP1_1'],
>                         1-self.redmpt['AP1']-delta_d['AP1_1']-delta_d['AP1_2'],   
>                         1-self.redmpt['AP2'] - delta_d['AP2_1'],
>                         1-self.redmpt['AP2']-delta_d['AP2_1']-delta_d['AP2_2'],
>                         1-self.redmpt['AP3'] - delta_d['AP3_1'],
>                         1-self.redmpt['AP3']-delta_d['AP3_1']-delta_d['AP3_2'],    
>                         -delta_d['AR1_1']*delta_d['AR1_2'],
>                         -delta_d['AR2_1']*delta_d['AR2_2'],
>                         -delta_d['AR3_1']*delta_d['AR3_2'],
>                         -delta_d['AP1_1']*delta_d['AP1_2'],
>                         -delta_d['AP2_1']*delta_d['AP2_2'],
>                         -delta_d['AP3_1']*delta_d['AP3_2'],
>                         delta_d['AR1_1']+delta_d['AR1_2']-self.AR1_REDEMPT_RANGE_up,
>                         self.AR1_REDEMPT_RANGE_down-delta_d['AR1_1']-delta_d['AR1_2'], 
>                         delta_d['AR2_1']+delta_d['AR2_2']-self.AR2_REDEMPT_RANGE_up,
>                         self.AR2_REDEMPT_RANGE_down-delta_d['AR2_1']-delta_d['AR2_2'],
>                         delta_d['AR3_1']+delta_d['AR3_2']-self.AR3_REDEMPT_RANGE_up,
>                         self.AR3_REDEMPT_RANGE_down-delta_d['AR3_1']-delta_d['AR3_2'],
>                         delta_d['AP1_1']+delta_d['AP1_2']-self.AP1_REDEMPT_RANGE_up,
>                         self.AP1_REDEMPT_RANGE_down-delta_d['AP1_1']-delta_d['AP1_2'],
>                         delta_d['AP2_1']+delta_d['AP2_2']-self.AP2_REDEMPT_RANGE_up,
>                         self.AP2_REDEMPT_RANGE_down-delta_d['AP2_1']-delta_d['AP2_2'],
>                         delta_d['AP3_1']+delta_d['AP3_2']-self.AP3_REDEMPT_RANGE_up,
>                         self.AP3_REDEMPT_RANGE_down-delta_d['AP3_1']-delta_d['AP3_2'] ,
>                         -sumr1+sumar1+15,
>                         -sumr2+sumar2+20,
>                         -sumr2+sumar2+10,
>                         -sumap1 - sumap2 -sumap3 + sumc1 -30]
> pop.CV = np.hstack(qualification_list)

其中，int(self.params['ADJUST_TOTAL'][0]) = 15，self.redmpt['AR1']  = 3， self.redmpt['AR2']  = 6，self.redmpt['AR3']  = 6， self.redmpt['AP1']  = 4， self.redmpt['AP2'] =4, self.redmpt['AP3']  = 4，self.AR1_REDEMPT_RANGE_up = 2，self.AR1_REDEMPT_RANGE_down = -4,其他AR AP的REDMPT_RANGE与以上相同。

以下为population中与var_trace[best_gen]相同的解对应的CV：
<img width="276" alt="捕获" src="https://user-images.githubusercontent.com/50685245/67256113-1e3d3b80-f4b8-11e9-8f1a-8611924a4962.PNG">

如果手工按照限制条件计算，第四个限制条件应该与第三个限制条件值相等 = -1。除了第四个限制条件外有些其他限制条件的CV值也与手工计算年的值不符合。请问这是什么原因导致的呢？ 谢谢

**Comment by 1061655504** [comment]
@xrzalreadytaken 你输出一下population.Phen以及将它代入目标函数手工计算一下CV看看和代码计算得到的是否一样。因为整个框架里面除了这个自定义问题类之外不会对CV进行修改的，自定义问题类里面算出多少就是多少了。

**Comment by 1061655504** [comment]
如果还有问题可以继续提出来噢！
