### ISSUE TITLE
针对类装箱问题的咨询

### ISSUE THREAD

**Issue by l976308589** [geatpy-dev/geatpy#55]
您好，非常感谢您开源如此优秀的项目。
我当前应用的场景是机场停机位分配问题，使用咱们的排列模板。在计算适应度的时候，对不满足约束的进行惩罚。
但速度较慢，归根结底是约束条件过多，导致有相当程度的个体需要被惩罚。
请问有什么方式可以提高该类问题下的计算速度？

**Comment by geatpy-dev** [comment]
> 您好，非常感谢您开源如此优秀的项目。
> 我当前应用的场景是机场停机位分配问题，使用咱们的排列模板。在计算适应度的时候，对不满足约束的进行惩罚。
> 但速度较慢，归根结底是约束条件过多，导致有相当程度的个体需要被惩罚。
> 请问有什么方式可以提高该类问题下的计算速度？

书写aimFunc()函数的时候尽量少用循环，尽量用矩阵计算或者是采用python的一些并行库来实现并行计算。如果循环有好几层那么多，那么速度就会大幅降低。

**Comment by l976308589** [comment]
您好，aimFunc()函数很简洁。
每天不同的航班要被分配在不同的机位上，在使用进化算法的时候，需要按照机位分组，判断同一机位上面的航班是否有冲突。这个分组的过程最耗时。
在使用咱们的排列编码的时候，有没有办法冲根源上消除冲突分机位的方法？

**Comment by l976308589** [comment]
![image](https://user-images.githubusercontent.com/10337055/67351699-b69ef300-f580-11e9-9553-08082b44888e.png)

**Comment by geatpy-dev** [comment]
@l976308589 了解了解了。排列编码是经典编码方式，只能保证染色体上每一位都不一样。您现在要把这个约束用编码的方式取缔的话得设计专用的编码了呀。设计专用编码时最好能把该编码化归成经典编码，就是说：设计一个看起来是经典编码的编码，而对其进行若干层的解码之后能够表达出复杂的信息（即在这里能够处理这个约束）。因为这样一来交叉变异等算子就能套用经典的交叉变异了，整个框架不用改动，只需在aimFunc里面加多一个解码操作就好了。

**Comment by l976308589** [comment]
您好，您有什么思路吗？
航班有时间属性，只要保证时间属性不冲突即可
这是一块比较大的问题，市场也比较广
如果您有好的解决方案，我实现之后放在您的项目中，想必容易引起民航领域的兴趣

**Comment by geatpy-dev** [comment]
@l976308589 好呢～那这样吧：您把一些相关的文献给我发一下（geatpy@163.com），我先研究研究看看能否帮点忙。

**Comment by l976308589** [comment]
已经向您发送，请您查收。
为了方便其他人看到，我也贴一份到此

本问题是要把航班(f)分配给机位(s)。

航班有多个属性(P_f)，其中包括了时间、机型以及其他属性。

机位有2个属性(P_s)，分别是大小和远近。大小是指机位的尺寸，大的机位可以放下大的航班，小的机位无法放下大航班。远近是指机位于柜台的距离。

需要满足以下条件:

同一个机位上不允许出现时间冲突;

机位必须可以容纳航班

其他可配置约束。

主要是1、2，有了1和2，其他约束可以按照机场的情况添加。

目标:

近机位容纳的航班越多越好，俗称靠桥率

每个机位容纳的机位越均衡越好，该目标可以先不考虑


以下是我的代码:
import numpy as np
import pandas as pd

import Scripts.OlsonEV as Ea
from concurrent.futures import ProcessPoolExecutor as Pool


class MyProblem(Ea.Problem):  # 继承Problem父类
    def __init__(self):
        name = 'Airport'  # 初始化name（函数名称，可以随意设置）

        df = pd.read_csv('Bin/Data/2018-08-10Result.csv', encoding='gbk')[
            ['CRAFTSEAT', 'FILGHTNOARR', 'VALIDSEAT', 'DES_PLAN_LANDING', 'DEP_PLAN_TAKEOFF']]
        # 将机位\航班进行数字化编码
        self.seat = df.drop_duplicates(subset='CRAFTSEAT')['CRAFTSEAT'].values
        self.flight = df['FILGHTNOARR'].values
        self.df = df[['DES_PLAN_LANDING', 'DEP_PLAN_TAKEOFF']].copy()
        self.df['DES_PLAN_LANDING'] = pd.DataFrame(self.df['DES_PLAN_LANDING'])
        self.df['DEP_PLAN_TAKEOFF'] = pd.DataFrame(self.df['DEP_PLAN_TAKEOFF'])

        M = 1  # 初始化M（y的个数）
        maxormins = [-1]  # 初始化maxormins（目标最小最大化标记列表，1：最小化该目标；-1：最大化该目标）
        Dim = len(self.flight)  # 初始化Dim（x的个数）
        varTypes = [1] * Dim  # 初始化varTypes（x的类型，元素为0表示对应的变量是连续的；1表示是离散的）
        lb = [0] * Dim  # x下界
        ub = list(range(len(self.seat)))
        # [len(self.seat)] * Dim  # x上界
        lbin = [1] * Dim  # x下边界
        ubin = [0] * Dim  # x上边界
        # 调用父类构造方法完成实例化
        Ea.Problem.__init__(self, name, M, maxormins, Dim, varTypes, lb, ub, lbin, ubin)

    @staticmethod
    def no_clash(df=pd.DataFrame()):
        if df.shape[0] == 1:
            return True

        return (df['DES_PLAN_LANDING'] >= df['DEP_PLAN_TAKEOFF'].shift()).iloc[1:].all()

    def aimFunc(self, pop):  # 目标函数
        x = pop.Phen.astype(np.int)  # 得到决策变量矩阵
        # 计算靠桥率
        pop.ObjV = np.apply_along_axis(lambda row: [len(row[row <= 10])], 1, x)
        idxs = []
        for idx, i in enumerate(x):
            self.df['SEAT'] = i
            self.df.sort_values('SEAT', inplace=True)
            if self.df.groupby('SEAT').apply(self.no_clash).all():
                pass
            else:
                idxs.append(idx)
        # 找到违反约束条件的个体在种群中的索引，保存在向量exIdx中（如：若0、2、4号个体违反约束条件，则编程找出他们来）
        pop.CV[idxs] = 0  # 把求得的违反约束程度矩阵赋值给种群pop的CV

    def get_conflict(self, x):
        idx, i = x
        self.df['SEAT'] = i
        self.df.sort_values('SEAT', inplace=True)
        if self.df.groupby('SEAT').apply(self.no_clash).all():
            return None
        return idx

**Comment by l976308589** [comment]
您好，我发现修改crtpc文件应该可以极大提升速度。
但是咱们crtpc是pyd文件，有办法修改“生成染色体矩阵”这一块吗？

**Comment by geatpy-dev** [comment]
> 您好，我发现修改crtpc文件应该可以极大提升速度。
> 但是咱们crtpc是pyd文件，有办法修改“生成染色体矩阵”这一块吗？

如果Encoding是'P'，那么这个crtpc其实是直接调用crtpp的。您看下您正在使用的版本是不是2.2.3？这个版本的crtpp会比以前快一个数量级。

**Comment by l976308589** [comment]
您好，是2.2.3，Encoding是'P'，但crtpp也是pyd格式;

当下我将每一个机位都对应一个可选航班，比如机位A对应航班集合{1,3,4}，机位A对应航班集合{3,7,9}。这种取值能够使用现有框架？

**Comment by geatpy-dev** [comment]
@l976308589 pyd文件修改不了，编译好写死进去了的；应该可以用映射的方式实现。

**Comment by l976308589** [comment]
如何映射，方便指导一下吗？

**Comment by geatpy-dev** [comment]
您这个编码设计问题我觉得和一些离散调度问题、路径规划问题有异曲同工之处。比如无向图的最短路径规划问题那样，它不是直接编码的，而是用间接编码，然后通过字典或数组映射的方法把经典编码的染色体解码得到想要的决策变量。您可以去看一下同类的这些问题，或许能够研究出来了。

**Comment by l976308589** [comment]
谢谢您的指导。
我想先维护一个机位-航班表，然后染色体使用P编码。
初设摄像P编码代表机位-航班表中的位置，比如，
机位航班表为[[12,36,52],[19,36,52,56]]
Ｐ编码为[[1],[3]],
意思为第一个航班分配[12,36,52]的第一个位置-机位36，第二个航班分配,[19,36,52,56]的第3个位置-机位56
此时需要使用[]操作来取值，没有向量化操作快。
您有什么思路，让P编码和机位-航班表更好的映射吗？

**Comment by l976308589** [comment]
谢谢您，我已经使用dict对aimfunc做了处理，获得了可喜的速度。
只是现在在P编码的过程中，命名将ub设置为[40]，ubin设置为[0]，但是却产生了不在改取值范围的113。
