### ISSUE TITLE
决策变量的精度控制

### ISSUE THREAD

**Issue by Hemitr** [geatpy-dev/geatpy#57]
决策变量为实数，但是希望控制决策变量在某一精度上，例如希望决策变量最小变化是0.01。请问该如何实现

**Comment by 1061655504** [comment]
> 决策变量为实数，但是希望控制决策变量在某一精度上，例如希望决策变量最小变化是0.01。请问该如何实现

这种情况实际上是离散变量优化。用离散编码，然后在还原决策变量的时候利用数组下标映射到一个存储着实数的数组就好了。比如【0，1】之间精度为0. 1的实数，那么这个数组就是｛0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0｝，此时用【0, 10】的离散编码。

**Comment by 1061655504** [comment]
如果还有问题可以继续提出来噢！
