### ISSUE TITLE
单目标优化中目标函数含特殊运算符的问题

### ISSUE THREAD

**Issue by liwei066000** [geatpy-dev/geatpy#59]
参照实例在编写 单目标优化问题的目标函数时，里面含有“取大”和“阶乘”运算，目标函数如下：
 pop.ObjV = 1 - max(100/(2*x11),100/(3*x12)) * (1 - (1 - 100**x21/(4**x21 * math.factorial(x21))) * (1 - 100**x22/(6**x22 * math.factorial(x22))) * (1 - 100**x23/(8**x23 * math.factorial(x23))))   

结果运行出错：提示ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

临时去掉取大后，还是有问题，提示
TypeError: only size-1 arrays can be converted to Python scalars

希望大神赐教，多谢！

**Comment by liwei066000** [comment]
乘号 * 没有遗落，是复制粘贴时没有显示。

**Comment by 1061655504** [comment]
@liwei066000 你网上搜索一下Numpy的max()函数的用法。另外“TypeError: only size-1 arrays can be converted to Python scalars”的错误意思是说python的阶乘函数传入的必须是一个标量。你print(x21)和print(x23)看看是不是标量。要化为标量才能用python的那个阶乘函数。

**Comment by liwei066000** [comment]
@1061655504 感谢你的回复。我之前也有查过max()函数用法，在其它环境没问题，但放到优化问题中就报错。另外，x21和x23都是决策变量，在之前不涉及特殊运算符时就没有问题。所以我是想寻找一下上述目标函数的更好的Python表示语句。谢谢

**Comment by 1061655504** [comment]
这个是Numpy语法问题。决策变量是个numpy array矩阵来的，你可以通过创建类似的简单矩阵来练习一下，掌握numpy的np.max(矩阵)的用法。

**Comment by liwei066000** [comment]
好的，我试试看，谢谢回复
&nbsp;

小伟信箱


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jazz_bin"<notifications@github.com&gt;; 
发送时间: 2019年11月7日(星期四) 上午9:56
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;; 
抄送: "李伟"<1538883431@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [geatpy-dev/geatpy] 单目标优化中目标函数含特殊运算符的问题 (#59)




这个是Numpy语法问题。决策变量是个numpy array矩阵来的，你可以通过创建类似的简单矩阵来练习一下，掌握numpy的np.max(矩阵)的用法。
 
&mdash;

**Comment by 1061655504** [comment]
不客气呢！欢迎继续提出宝贵的问题噢！
