### ISSUE TITLE
是否可以通过txt文件进行种群初始化

### ISSUE THREAD

**Issue by c6ishere** [geatpy-dev/geatpy#61]
geatpy团队的成员你们好：

使用了一段时间的geatpy，非常感谢你们的工作。

我当前的优化问题比较耗时，在之前的科研工作中已经通过matlab程序得到了一些寻优的结果，现在将平台移植到python上，所以希望**在之前的基础上继续进行寻优**，这就涉及到**将之前得到的寻优结果txt文件去初始化population中的个体**。

我已经研究了一段时间，不过初始化这部分仿佛并未预留接口（比如可以np.loadtxt()），有什么方法可以实现所需功能吗？或者初始化需要什么样的数据格式？期待交流。：）

**Comment by 1061655504** [comment]
@c6ishere 您好呀！数据格式相见这个文档：
[http://geatpy.com/index.php/2019/07/28/2-geatpy%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/](url)
如果txt里面是种群的染色体数据，并且跟以下链接里面的一样：
[https://github.com/geatpy-dev/geatpy/blob/master/geatpy/testbed/moea_test/moea_test_DTLZ/Result/Chrom.csv](url)，
即每一行是一个个体的染色体数据，那么可以直接把np.loadtxt()的结果赋值给population.Chrom就OK了。如果还有问题欢迎继续提出来噢~

**Comment by c6ishere** [comment]
非常感谢！

**Comment by THUzhangga** [comment]
> @c6ishere 您好呀！数据格式相见这个文档：
> [http://geatpy.com/index.php/2019/07/28/2-geatpy%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/](url)
> 如果txt里面是种群的染色体数据，并且跟以下链接里面的一样：
> [https://github.com/geatpy-dev/geatpy/blob/master/geatpy/testbed/moea_test/moea_test_DTLZ/Result/Chrom.csv](url)，
> 即每一行是一个个体的染色体数据，那么可以直接把np.loadtxt()的结果赋值给population.Chrom就OK了。如果还有问题欢迎继续提出来噢~

您好，您举的例子是实数编码的吧？如果是二进制编码呢？有接口吗？
