### ISSUE TITLE
矩阵参数更新计算TypeError: only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by 928689035wings** [geatpy-dev/geatpy#62]
尊敬的geatpy开发者:
您好.感谢你们的幸苦劳动分享给了我们这么优秀的算法框架.在使用中,我遇到了如下问题,由于百思不得其解只得抱着试一试态度向你们寻求帮助:

函数:现有一条曲线,计算曲线上各点的理论与实际偏差之和
Loss函数=|实际末端三维坐标-数学建模三维坐标|
目的:更新数学建模计算三维坐标时使用的的八个参数,使得loss最小.
其中数学建模三维坐标用到了4x4的矩阵计算(arrays).
但是现在总是报错:
  File "H:\pythonchengx_u\凿岩台车数据处理\Zaoyan_robot.py", line 15, in D_H
    T = np.array([[cos(theta),-sin(theta),0 ,a],...
TypeError: only size-1 arrays can be converted to Python scalars

我不代入遗传算法,直接手动更新整个函数是能运行得到结果的.
由于没有找到解决办法,所以想询问一下,我们的geatpy里面的MyProblem是不是不支持有矩阵运算? 我是无法仿照moea_demo3/MyProblem.py 直接初始化矩阵的,因为我的矩阵是更新待求的. 
  如果您有建议和方法希望能得到您的指导,谢谢.如果我的问题比较幼稚,也希望您能多包涵,谢谢

**Comment by 1061655504** [comment]
@928689035wings 看上面的报错提示我目测估计是你没有使用numpy的cos和sin函数。手动计算的时候cos和sin你应该传入的是标量，但aimFunc()里面的theta目测是个矩阵或者向量，所以要用np.cos和np.sin代替。

**Comment by 928689035wings** [comment]
实在是太感谢您了,您一针见血的指出了我的问题,现在已经完美地跑出来了,再次感谢,祝您生活愉快!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jazz_bin"<notifications@github.com&gt;; 
发送时间: 2019年11月23日(星期六) 晚上8:04
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;; 
抄送: "戴驹_中南大学"<928689035@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [geatpy-dev/geatpy] 矩阵参数更新计算TypeError: only size-1 arrays can be converted to Python scalars (#62)




@928689035wings 看上面的报错提示我目测估计是你没有使用numpy的cos和sin函数。手动计算的时候cos和sin你应该传入的是标量，但aimFunc()里面的theta目测是个矩阵或者向量，所以要用np.cos和np.sin代替。

**Comment by 1061655504** [comment]
@928689035wings 好哒~不客气噢~~
