### ISSUE TITLE
帕累托前沿点个数为0

### ISSUE THREAD

**Issue by yinlichang** [geatpy-dev/geatpy#63]
通过多目标的优化求解NSGA-III，最后求出来的帕累托前沿点个数为0，说明我这个是解不出来了么?还是说增加迭代次数，优化变量范围才能够求解出来

**Comment by 1061655504** [comment]
@yinlichang 是不是待求解的问题中存在等式约束？

**Comment by yinlichang** [comment]
对的，存在着等式约束, 我总共有60000多个决策变量，等式约束有8000多个。

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=ylcyzkyp&uid=ylcyzkyp%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22ylcyzkyp%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
ylcyzkyp
ylcyzkyp@outlook.com
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年11月25日 12:55，Jazz_bin<notifications@github.com><mailto:notifications@github.com> 写道：

@yinlichang<https://github.com/yinlichang> 是不是待求解的问题中存在等式约束？

**Comment by 1061655504** [comment]
@yinlichang 进化算法处理等式约束比较鸡肋，一复杂起来往往会一直进化得不到满足等式约束的解。这里主要有四种处理方法：（1）修改待求解的模型，采用数学变量代换**去掉等式约束**，由此把等式约束变成不等式约束；（2）用NSGA-III-DE算法模板代替NSGAIII（即把NSGA-III里面的遗传算法换成差分进化算法），然后**暴力调参硬算**。（3）把等式约束变成一个新的优化目标，优化的时候让解尽可能地满足该目标（这里你有8000多个等式约束所以这个方法3可能不适用）。（4）**设计新型染色体结构**以及配套的进化算子，使得不论如何进化得到的解都是可行解。

**Comment by yinlichang** [comment]
好的，非常感谢，我先尝试下这几种方法，多学习学习

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=ylcyzkyp&uid=ylcyzkyp%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22ylcyzkyp%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
ylcyzkyp
ylcyzkyp@outlook.com
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年11月25日 13:07，Jazz_bin<notifications@github.com><mailto:notifications@github.com> 写道：

@yinlichang<https://github.com/yinlichang> 进化算法处理等式约束比较鸡肋，一复杂起来往往会一直进化得不到满足等式约束的解。这里主要有四种处理方法：（1）修改待求解的模型，采用数学变量代换去掉等式约束，由此把等式约束变成不等式约束；（2）用NSGA-III-DE算法模板代替NSGAIII（即把NSGA-III里面的遗传算法换成差分进化算法），然后暴力调参硬算。（3）把等式约束变成一个新的优化目标，优化的时候让解尽可能地满足该目标（这里你有8000多个等式约束所以这个方法3可能不适用）。（4）设计新型染色体结构以及配套的进化算子，使得不论如何进化得到的解都是可行解。

**Comment by yinlichang** [comment]
我把等式转为不等式，同时缩减不等式的个数为4000多个，将算法改为基于 NSGA-III-DE 算法的多目标进化算法模板,还是求解不出来最优解，我里面的公式也就个非常简单的加减乘除

**Comment by liuchong1995** [comment]
> 我把等式转为不等式，同时缩减不等式的个数为4000多个，将算法改为基于 NSGA-III-DE 算法的多目标进化算法模板,还是求解不出来最优解，我里面的公式也就个非常简单的加减乘除

老哥你的等式怎么转化为不等式的？我心在也有个问题有一堆等式约束，算出来的解全是一个样的，而且解适应度太差了

**Comment by 1061655504** [comment]
> 我把等式转为不等式，同时缩减不等式的个数为4000多个，将算法改为基于 NSGA-III-DE 算法的多目标进化算法模板,还是求解不出来最优解，我里面的公式也就个非常简单的加减乘除

如果没有等式约束的话用进化算法应该是起码地会有可行解的呀。你添加我QQ我帮你远程看一下1061655504

**Comment by yinlichang** [comment]
求通过啊，发送过去了，今天检查一天都没检查出来啥问题，我如果只是算局部五六十个变量的话就很容易出来

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=ylcyzkyp&uid=ylcyzkyp%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22ylcyzkyp%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
ylcyzkyp
ylcyzkyp@outlook.com
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年11月26日 07:37，Jazz_bin<notifications@github.com><mailto:notifications@github.com> 写道：

我把等式转为不等式，同时缩减不等式的个数为4000多个，将算法改为基于 NSGA-III-DE 算法的多目标进化算法模板,还是求解不出来最优解，我里面的公式也就个非常简单的加减乘除

如果没有等式约束的话用进化算法应该是起码地会有可行解的呀。你添加我QQ我帮你远程看一下1061655504

**Comment by 1061655504** [comment]
已解决~
