### ISSUE TITLE
寻找模型的最优参数问题

### ISSUE THREAD

**Issue by tuzhirun** [geatpy-dev/geatpy#64]
你好，这个对于参数优化的例子有吗？比如优化支持向量机的参数。谢谢！或者对应的资料？

**Comment by geatpy-dev** [comment]
> 你好，这个对于参数优化的例子有吗？比如优化支持向量机的参数。谢谢！或者对应的资料？

您好！只要把待优化的模型写成一个问题类，设置好决策变量和待优化的目标，就能够直接调用工具箱进行进化优化了。例如把SVM里面待优化的参数作为决策变量，SVM的分类精度作为待优化的目标，然后用单目标进化算法让分类精度不断提高。

换句话说，优化SVM参数和优化函数是同一个套路：把SVM的待优化参数记为x1,x2等等，SVM的分类精度记为F(x1,x2,...)，相当于用进化算法让这个F(x1,x2,...)最大化。于是在自定义问题类的aimFunc()里面，把第一个个体的决策变量取出来，代入SVM程序计算出对应的分类精度（记作O1），它就是第一个个体的目标函数值了。然后，循环种群所有个体，用同样的方法计算出O2、O3、O4、...，最后这些所有的O1、O2、O3、O4等拼成一个列向量赋值给种群pop的ObjV属性（即种群的目标函数值矩阵）。这样就OK了。

**Comment by tuzhirun** [comment]
&nbsp;def aimFunc(self, pop): # 目标函数，pop为传入的种群对象
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Vars = pop.Phen # 得到决策变量矩阵
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(Vars)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; x1 = Vars[:,[0]] # 取出第一列得到所有个体的x1组成的列向量
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(x1[:20])
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; x2 = Vars[:,[1]] # 取出第二列得到所有个体的x2组成的列向量
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(x2[:20])
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; x3 = Vars[:,[2]]
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(x3[:20])
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; svr = SVR(kernel='rbf', C = x1.all(), gamma = x2.all() ,epsilon = x3.all())
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; svr.fit(x_train,y_train)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; predict_value = svr.predict(x_test)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; squaredError = []
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; for i in range(len(predict_value)):&nbsp;&nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; val=predict_value[i-1]-y_test[i-1]&nbsp;&nbsp;&nbsp;&nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; squaredError.append(val * val)&nbsp; # target-prediction之差平方&nbsp;&nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print("MSE = ", sum(squaredError) / len(squaredError))&nbsp; # 均方误差MSE
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MSE = sum(squaredError) / len(squaredError)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; pop.ObjV =&nbsp; np.array(MSE).reshape(-1,1)



你好，这是我的目标函数设置，优化目标是SVR里面的三个参数值，目标函数是MSE。但是我运行main.py的时候报错了：
RuntimeError: error in scaling: CV and ObjV disagree. (违反约束程度矩阵的行数必须和目标函数值矩阵的行数相同。)
按理说这个的目的是最小化MSE即可，为什么还会有约束条件？
是我的目标函数错了还是其他的问题？谢谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liangxu chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 晚上8:34
收件人:&nbsp;"geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送:&nbsp;"NKing"<2542822050@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [geatpy-dev/geatpy] 寻找模型的最优参数问题 (#64)



 
你好，这个对于参数优化的例子有吗？比如优化支持向量机的参数。谢谢！或者对应的资料？
  
您好！只要把待优化的模型写成一个问题类，设置好决策变量和待优化的目标，就能够直接调用工具箱进行进化优化了。例如把SVM里面待优化的参数作为决策变量，SVM的分类精度作为待优化的目标，然后用单目标进化算法让分类精度不断提高。
 
换句话说，优化SVM参数和优化函数是同一个套路：把SVM的待优化参数记为x1,x2等等，SVM的分类精度记为F(x1,x2,...)，相当于用进化算法让这个F(x1,x2,...)最大化。于是在自定义问题类的aimFunc()里面，把第一个个体的决策变量取出来，代入SVM程序计算出对应的分类精度（记作O1），它就是第一个个体的目标函数值了。然后，循环种群所有个体，用同样的方法计算出O2、O3、O4、...，最后这些所有的O1、O2、O3、O4等拼成一个列向量赋值给种群pop的ObjV属性（即种群的目标函数值矩阵）。这样就OK了。

**Comment by geatpy-dev** [comment]
@tuzhirun  如果没有约束条件，CV矩阵是一个全为0的列向量。

**Comment by tuzhirun** [comment]
好的，谢谢。我已经明白了。还有我按照你说的把每一个决策变量（我的是三个）得到的目标函数值拼成了一个列向量赋值给了种群的ObjV属性，但是结果并不是输出的最优决策变量和最优目标函数值，然后我通过查看目标函数矩阵，发现最优值是另外一个，即输出的不是最优值。这个库是不是对于大样本处理速度很慢啊？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liangxu chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 上午10:41
收件人:&nbsp;"geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送:&nbsp;"NKing"<2542822050@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [geatpy-dev/geatpy] 寻找模型的最优参数问题 (#64)




@tuzhirun  如果没有约束条件，CV矩阵是一个全为0的列向量。

**Comment by geatpy-dev** [comment]
@tuzhirun  不应该对应不上的。您联系一下工作人员QQ 1061655504让他帮忙看一下代码或者远程看一下。另外速度快慢的瓶颈在于自定义函数aimFunc() ，写得快就很快。

**Comment by tuzhirun** [comment]
好的，谢谢回复。祝你身体健康





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liangxu chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 中午11:10
收件人:&nbsp;"geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送:&nbsp;"NKing"<2542822050@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [geatpy-dev/geatpy] 寻找模型的最优参数问题 (#64)




@tuzhirun  不应该对应不上的。您联系一下工作人员QQ 1061655504让他帮忙看一下代码或者远程看一下。另外速度快慢的瓶颈在于自定义函数aimFunc() ，写得快就很快。

**Comment by eheroqiu** [comment]
多线程在处理模型的超参寻优时是不是没有多进程合适啊？

**Comment by geatpy-dev** [comment]
@eheroqiu 计算单个个体的目标函数值时若耗时越久的话用多进程或者用分布式计算会比用多线程好。

**Comment by eheroqiu** [comment]
谢谢各位，目前已经提速了很多倍了

**Comment by eheroqiu** [comment]
关于MoeaAlgorithm算法模版父类中终止进化的条件
因为我没有看到任何对目标函数值的收敛判断或者估计
我是否可以理解为， 目前的maxgen其实是一个算法进化迭代次数的最小值


那么，如果我要实现对收敛判断，我应该在哪个类去复用或者实现呢？
def terminated(self, population): # 判断是终止进化，population为传入的种群对象
    self.stat(population) # 进行统计分析，更新进化记录器
    # 判断是否终止进化，由于代数是从0数起，因此在比较currentGen和MAXGEN时需要对currentGen加1
    if self.currentGen + 1 >= self.MAXGEN or self.forgetCount >= self.maxForgetCount:
        return True
    else:
        self.currentGen += 1 # 进化代数+1
        return False

**Comment by geatpy-dev** [comment]
@eheroqiu 需要定义一个正在使用的算法模板类的子类，去覆盖默认的terminated()函数。例如这篇文档的最后部分：[http://geatpy.com/index.php/2019/07/28/4-%E8%BF%9B%E5%8C%96%E7%AE%97%E6%B3%95%E6%A8%A1%E6%9D%BF/](url)
