### ISSUE TITLE
这个库的关键算子都是不开源吗？

### ISSUE THREAD

**Issue by zoo991230** [geatpy-dev/geatpy#65]
您好，我刚接触这个框架，发现很多算子都指向 `_core` 文件夹下的 `*.pyd` 文件，而这些文件都是编译后的文件。
我对整个架构了解还很粗浅，我想问问，这些算子是不是不开源？如果是开源的话，我在哪里能找到编译前的文件呢？

**Comment by zoo991230** [comment]
另外，感谢作者做的框架

**Comment by geatpy-dev** [comment]
@zoo991230 目前框架是开源的但中间过程调用到的一些经典的进化算子是封装好的。那些部分会涉及到C等底层编程，编译环境搭建复杂，目前项目组正在加紧整理注释。保守估计要到次年1月份更新内置的基因表达式编程GEP后再进行内核开源。

**Comment by bofengshuimen77** [comment]
您好，主要想看一下你们的inidcator.hv的源码，能共享吗

**Comment by geatpy-dev** [comment]
可以根据API文档的里面的算法参考文献中的通讯方式找到作者的算法代码。

**Comment by bofengshuimen77** [comment]
好的，多谢



---原始邮件---
发件人: "geatpy"<notifications@github.com&gt;
发送时间: 2019年12月16日(周一) 晚上8:39
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"bofengshuimen77"<772362319@qq.com&gt;;
主题: Re: [geatpy-dev/geatpy] 这个库的关键算子都是不开源吗？ (#65)



可以根据API文档的里面的算法参考文献中的通讯方式找到作者的算法代码。
