### ISSUE TITLE
测试问题ZDT1的计算是否忘了除29？

### ISSUE THREAD

**Issue by lepecoder** [geatpy-dev/geatpy#66]
**Describe the bug**
![ZDT1](https://img-blog.csdnimg.cn/2019061819165481.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQwNDU2ODI5,size_16,color_FFFFFF,t_70)

文件位置：
[https://github.com/geatpy-dev/geatpy/blob/master/geatpy/testbed/moea_test/moea_test_ZDT/ZDT1.py](https://github.com/geatpy-dev/geatpy/blob/master/geatpy/testbed/moea_test/moea_test_ZDT/ZDT1.py)

**Comment by geatpy-dev** [comment]
@lepecoder 不同论文版本不同。不除以29的会在一定程度上提高进化的难度。国内比较新的一些多目标优化测试平台里面采用的也是不除以29的版本，而国外的仍旧用除以29的。两个都是可以的。不过值得注意的是如果要做算法比较，那么在测试的时候得统一使用同一种版本。

**Comment by lepecoder** [comment]
原来是这样，多谢
