### ISSUE TITLE
限制决策变量数目

### ISSUE THREAD

**Issue by wd1969** [geatpy-dev/geatpy#67]
我有许多待选决策变量，因为无法事先精简，所以能否在搜索中精简掉一些不重要的决策变量，例如决策变量矩阵值为0。我尝试降低精度，并把决策变量数量更少需求加入目标，在不降低结果质量的情况下精简掉 1/3.  之后我尝试加入约束条件，比如少于50. 但是结果很差。请教是否有更好的办法。

**Comment by geatpy-dev** [comment]
@wd1969  工具箱内置的算法模板是对染色体整体进行进化寻优的。如果需要“染色体局部进化优化”，需要自定义改进的进化算法模板：在每一代交叉变异的时候把想要重点搜索的变量对应到染色体抽取出来（即把某些列抽取出来组成“子染色体矩阵”），对这个“子染色体矩阵”进行交叉变异。

**Comment by wd1969** [comment]
好的谢谢
