### ISSUE TITLE
官网进化算法介绍-变异部分无法打开

### ISSUE THREAD

**Issue by SuenChiaChow** [geatpy-dev/geatpy#68]
官网进化算法介绍-第六章变异部分无法打开，希望修复一下
如果无法修复，希望能把文件发送给我，我的邮箱为sunjzh@tongji.edu.cn
感谢

**Comment by geatpy-dev** [comment]
您好啊！感谢您的反馈！网站出现了异常，现已恢复。给您造成的不便我们深表歉意！

**Comment by SuenChiaChow** [comment]
谢谢您的答复，希望你们越做越好！

**Comment by geatpy-dev** [comment]
好呢！💪
