### ISSUE TITLE
怎样设置决策变量权重

### ISSUE THREAD

**Issue by wd1969** [geatpy-dev/geatpy#69]
因为决策变量比较多，100代以内有部分决策变量 还是未被搜索到(很少参与交叉变异)  请教如何让部分未用到“不活跃”决策变量 加入到种群中？

**Comment by geatpy-dev** [comment]
@wd1969 在每一代交叉变异的时候把想要重点搜索的变量对应的染色体片段利用numpy的矩阵片取运算抽取出来得到一个“子染色体矩阵”，例如：SubChrom = population.Chrom[:, [0,1,3,5]]，即让种群染色体矩阵中的第0、1、3、5列抽取成SubChrom，然后对这个SubChrom进行交叉变异，完后让population.Chrom[:, [0,1,3,5]] = SubChrom即把交叉变异的结果赋值给原染色体矩阵即可。

长染色体进化优化如果用经典的进化算法会比较吃力。以上是“局部染色体重点进化”的策略，更建议参考一些专门针对长染色体进化优化进行过改进的算法对问题进行求解。
