### ISSUE TITLE
2.2.3 P编码性能下降问题

### ISSUE THREAD

**Issue by faaanbingbing** [geatpy-dev/geatpy#70]
之前用版本2.0.0.post6优化一个调度问题，
由于需要缩小搜索空间采用P编码，如不用P编码则违反约束过多不收敛。
此调度问题在版本2.0.0.post6下可以最快在4分钟100代--最慢40分钟500代内找到有效的解。
同时运行7个优化进程，一般有2个进程可以4分钟内找到接近最优的有效解，其余则4-40分钟不等。

现在需要重新跑这个实验，安装了当前最新版本即2.2.3，
同时运行7个优化进程，90%的情况下，只有1个进程能找到离最优解很远的有效解，
相比之前的版本2.0.0.post6，性能下降很大，根本无法解决这个调度问题。
版本2.0.0.post6跟版本2.2.3之间存在一些API调用差异，
本人确信已完全把自己的问题修改成适合2.2.3规范的版本，
然而始终没法达到版本2.0.0.post6那样的愉快收敛。

时间关系没法确定从哪个版本开始出现这样的性能下降问题，仅报告发生在上诉两个版本之间。

**Comment by 1061655504** [comment]
@faaanbingbing 两个版本的算法模板默认的进化算子设置不一样。v2.0.0的默认的变异算子是'mutpp',而v2.2.3里面默认用的是'mutinv'（染色体片段逆转变异），您在v2.2.3里面设置一下用'mutpp'看下会不会好一些。

**Comment by faaanbingbing** [comment]
> 
> 
> @faaanbingbing 两个版本的算法模板默认的进化算子设置不一样。v2.0.0的默认的变异算子是'mutpp',而v2.2.3里面默认用的是'mutinv'（染色体片段逆转变异），您在v2.2.3里面设置一下用'mutpp'看下会不会好一些。

刚刚把Mutinv改成Mutpp，结果还是一样，不收敛，我一直用的都是soea_studGA_templet。

**Comment by 1061655504** [comment]
@faaanbingbing 现在在这儿只能文字交流不方便解决问题，您加一下我QQ：1061655504我来远程帮您看一下呗~

**Comment by 1061655504** [comment]
后续还有问题的话欢迎继续提问噢！
