### ISSUE TITLE
关于拟合曲线无法调用最小方差

### ISSUE THREAD

**Issue by 928689035wings** [geatpy-dev/geatpy#71]
尊敬的开发者：
       您好
       我在使用我们的geatpy库拟合文档曲线时，Loss为经计算后各点的误差（类型为list ），目标函数为min(np.std(loss)),结果发现无法调用np.std()，查其原因是因为在geatpy并行运算时，对于每一个点都会生成由每个种群的计算结果组成的一个array，以至于无法对一个这样的格式 [array[点1的 种群结果 ],array[ 点2的种群结果 ]...  ]。想请问开发者有没有什么建议
![image](https://user-images.githubusercontent.com/49859388/71000935-2069f200-2117-11ea-86a7-9d6ecaa4a436.png)

**Comment by 1061655504** [comment]
@928689035wings 可以在一个练习脚本里面创建一些简单的数据实验一下如何书写生成符合FitnV数据结构的语法，例如：
a = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7], [8, 9, 10]])
FitnV = np.array([np.std(a, 1)]).T

**Comment by 928689035wings** [comment]
非常感谢，我试一试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jazz_bin"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 上午9:00
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;; 
抄送: "戴驹_中南大学"<928689035@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [geatpy-dev/geatpy] 关于拟合曲线无法调用最小方差 (#71)




@928689035wings 可以在一个练习脚本里面创建一些简单的数据实验一下如何书写生成符合FitnV数据结构的语法，例如：
 a = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7], [8, 9, 10]])
 FitnV = np.array([np.std(a, 1)]).T

**Comment by 928689035wings** [comment]
尊敬的开发者：
&nbsp; &nbsp; 您好，上次的问题早已经解决，感谢你们耐心指导。
&nbsp; &nbsp; 现在我想请问一下，我们geatpy有没有函数能够在最优解收敛时做判断提前跳出评价？当寻优对象很多的时候，需要大规模的种群和进化代数。我在我们geatpy官网上没有找到相关的函数或注释。
&nbsp;可能是我粗心了，所以直接想询问一下。谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jazz_bin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 上午9:00
收件人:&nbsp;"geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送:&nbsp;"戴驹_中南大学"<928689035@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [geatpy-dev/geatpy] 关于拟合曲线无法调用最小方差 (#71)




@928689035wings 可以在一个练习脚本里面创建一些简单的数据实验一下如何书写生成符合FitnV数据结构的语法，例如：
 a = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7], [8, 9, 10]])
 FitnV = np.array([np.std(a, 1)]).T

**Comment by 1061655504** [comment]
@928689035wings 对的。。框架里面的terminated()判断进化终止函数里面没有这个通过收敛性来判断的代码。需要添加代码实现。在这个文档：[http://geatpy.com/index.php/2019/07/28/4-%e8%bf%9b%e5%8c%96%e7%ae%97%e6%b3%95%e6%a8%a1%e6%9d%bf/](url) 的倒数第二段有相关讲述，希望能够帮到您~

**Comment by 928689035wings** [comment]
非常感谢，我认真的学习一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jazz_bin"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 晚上9:52
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;; 
抄送: "戴驹_中南大学"<928689035@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [geatpy-dev/geatpy] 关于拟合曲线无法调用最小方差 (#71)




@928689035wings 对的。。框架里面的terminated()判断进化终止函数里面没有这个通过收敛性来判断的代码。需要添加代码实现。在这个文档：http://geatpy.com/index.php/2019/07/28/4-%e8%bf%9b%e5%8c%96%e7%ae%97%e6%b3%95%e6%a8%a1%e6%9d%bf/ 的倒数第二段有相关讲述，希望能够帮到您~

**Comment by geatpy-dev** [comment]
该问题似乎已经得到解决，jazzbin暂时不在，我这里就把该问题关掉啦。
