### ISSUE TITLE
提个建议：请开发者用下Python编程风格检查工具，优化下代码命名、API风格

### ISSUE THREAD

**Issue by zhouquan03** [geatpy-dev/geatpy#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geatpy-dev** [comment]
@zhouquan03 这是一个很有必要的提议。由于核心开发者们全是搞算法的，这些问题自最初代版本以来一直困扰着开发者们。不过目前已邀请前辈抽点精力回来帮忙改善代码注释和文档优化，请君静候佳音~
代码命名这一块是个复杂的历史性问题，最初是考虑为了让一些习惯matlab经典的工具箱的老用户过渡到python上面而设计的，现有的命名怕是不好改动了。
