### ISSUE TITLE
operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by Morpherous** [geatpy-dev/geatpy#73]
![image](https://user-images.githubusercontent.com/33863509/71266257-fddc1100-2382-11ea-82ea-d9913f77833d.png)
您好，请问这个错误是什么意思呢，我的初始种群维度是（5,26），这个这里的shape是怎么出的呢。感谢

**Comment by 1061655504** [comment]
@Morpherous 说明不符合geatpy设定的数据结构，您看一下aimFunc()里面所计算的ObjV等是否满足数据结构的设定~

**Comment by Morpherous** [comment]
已解决，多谢
