### ISSUE TITLE
多目标优化moea_NSGA2_templet设定迭代次数与期望不一致

### ISSUE THREAD

**Issue by Morpherous** [geatpy-dev/geatpy#74]
![image](https://user-images.githubusercontent.com/33863509/71455269-3474ba00-27cf-11ea-8957-172d9e3525f2.png)
![image](https://user-images.githubusercontent.com/33863509/71455285-4c4c3e00-27cf-11ea-91f8-abf2841d7463.png)
您好，我遇到了这个问题，就是我设定种群规模30，遗传10代，在aimfun里一直在调用一个change_layer的函数，按照计算应该是一共调用change_layer30*10=300次，但是在实际运行的时候，我发现它迭代的次数超过了这个次数，请问这个是什么原因呢
![image](https://user-images.githubusercontent.com/33863509/71455373-a1884f80-27cf-11ea-91f4-158c814b51e4.png)

**Comment by 1061655504** [comment]
@Morpherous 您看一下myAlgorithm.evalsNum（评价次数）的值是多少。算法模板里面采用了“遗忘策略”，对于约束优化会让实际进化代数比设定值更多，从而让评价次数比预期的高。如果要与预期一样，需要删去Algorithm.py文件中的105-118行中的条件语句，即取消“遗忘策略”。

**Comment by Morpherous** [comment]
好的好的，感谢感谢
