### ISSUE TITLE
交叉和变异的问题。

### ISSUE THREAD

**Issue by jesselasse** [geatpy-dev/geatpy#77]
交叉和变异具体是怎么实现的，这一部分是不开放的对嘛。我看有的变异算子不管Pm设的多大也只有少数几个个体参与变异。交叉也是，不清楚怎么实现的，特别是里面的概率。

**Comment by 1061655504** [comment]
@jesselasse 你用help()命令查看一下算子的API，Pm表示表示每条染色体发生突变的概率。有一些会有参考文献，可以在参考文献里面看到关于交叉和变异概率的详细描述。

**Comment by jesselasse** [comment]
我用help()看过了，但实验的时候并不这样。
1. help()中前面说突变率决定个体的每个决策变量发生突变，后面又说pm表示每条染色体的突变概率。这个Pm 和突变率不是一个东西吗，那突变率是哪个参数呢？
2. 做实验时mutbga算子不管Pm设置成多大，也只有少数个体参与突变，它的Pm决定这每个参与突变的染色体中有多少个决策变量突变 (设成Pm=1000，20条也只有4条突变，只不过这4条几乎每个基因都突变了）；而mutuni算子则是Pm越大，越多个体参与突变，每个个体突变的决策变量也更多。但他俩help()中解释是一样的，都是上一条提到的。
3. 如果是概率的话，为什么可以大于1呢，而且对mutuni来说Pm=1甚至>1时也没有每个个体都突变。

**Comment by 1061655504** [comment]
@jesselasse Pm是指每条染色体发生变异的概率噢，而不是个体发生变异的概率。Pm/染色体长度=染色体每一位发生变异的概率。如果Pm大于1，那么除以染色体长度之后染色体每一位发生变异的概率就会更大一些。这些变异的公式和实现在参考文献里面都有详细描述的。

**Comment by jesselasse** [comment]
@1061655504 谢谢解答。
所以Pm大于1时有的染色体没有突变是因为恰好它的每一位都没被选中突变。
