### ISSUE TITLE
决策变量为矩阵时该如何编码？

### ISSUE THREAD

**Issue by yf950919** [geatpy-dev/geatpy#78]
你好，请问，当决策变量为一个矩阵时需要如何进行表示，上下界的设置又该如何设定？
![image](https://user-images.githubusercontent.com/54619154/71711800-9b344c00-2e3d-11ea-9bd1-b23caadac004.png)

**Comment by geatpy-dev** [comment]
@yf950919 您好！矩阵编码是特别的编码方式，目前工具箱中并无内置矩阵编码。有两种处理办法：
方法1.利用向量来表示矩阵，把矩阵编码转化为线性的染色体编码。
方法2.手动编程实现矩阵编码的Population类，然而矩阵编码文献很多，且编码方式不统一，方法2意味着需要查阅文献选择合适的矩阵编码方式，而且要写代码实现配套的重组和变异算子，代码量较大。
建议用第一种方法。如果矩阵比较庞大，导致转化为线性染色体后染色体比较长，可以参考超长染色体的改进型进化算法相关文献来实现改进的EA算法模板进行求解。编程量会比第二种方法少很多。

**Comment by yf950919** [comment]
> @yf950919 您好！矩阵编码是特别的编码方式，目前工具箱中并无内置矩阵编码。有两种处理办法：
> 方法1.利用向量来表示矩阵，把矩阵编码转化为线性的染色体编码。
> 方法2.手动编程实现矩阵编码的Population类，然而矩阵编码文献很多，且编码方式不统一，方法2意味着需要查阅文献选择合适的矩阵编码方式，而且要写代码实现配套的重组和变异算子，代码量较大。
> 建议用第一种方法。如果矩阵比较庞大，导致转化为线性染色体后染色体比较长，可以参考超长染色体的改进型进化算法相关文献来实现改进的EA算法模板进行求解。编程量会比第二种方法少很多。

**Comment by yf950919** [comment]
> > @yf950919 您好！矩阵编码是特别的编码方式，目前工具箱中并无内置矩阵编码。有两种处理办法：
> > 方法1.利用向量来表示矩阵，把矩阵编码转化为线性的染色体编码。
> > 方法2.手动编程实现矩阵编码的Population类，然而矩阵编码文献很多，且编码方式不统一，方法2意味着需要查阅文献选择合适的矩阵编码方式，而且要写代码实现配套的重组和变异算子，代码量较大。
> > 建议用第一种方法。如果矩阵比较庞大，导致转化为线性染色体后染色体比较长，可以参考超长染色体的改进型进化算法相关文献来实现改进的EA算法模板进行求解。编程量会比第二种方法少很多。

**Comment by yf950919** [comment]
> @yf950919 您好！矩阵编码是特别的编码方式，目前工具箱中并无内置矩阵编码。有两种处理办法：
> 方法1.利用向量来表示矩阵，把矩阵编码转化为线性的染色体编码。
> 方法2.手动编程实现矩阵编码的Population类，然而矩阵编码文献很多，且编码方式不统一，方法2意味着需要查阅文献选择合适的矩阵编码方式，而且要写代码实现配套的重组和变异算子，代码量较大。
> 建议用第一种方法。如果矩阵比较庞大，导致转化为线性染色体后染色体比较长，可以参考超长染色体的改进型进化算法相关文献来实现改进的EA算法模板进行求解。编程量会比第二种方法少很多。

用向量标识后，向量形式的决策变量的上下界该如何定义，种群在迭代时，每次也是以向量形式进行交叉变异的吗？

**Comment by yf950919** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"geatpy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月3日(星期五) 下午4:00
收件人:&nbsp;"geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送:&nbsp;"851378084"<851378084@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [geatpy-dev/geatpy] 决策变量为矩阵时该如何编码？ (#78)




@yf950919 您好！矩阵编码是特别的编码方式，目前工具箱中并无内置矩阵编码。有两种处理办法：
 方法1.利用向量来表示矩阵，把矩阵编码转化为线性的染色体编码。
 方法2.手动编程实现矩阵编码的Population类，然而矩阵编码文献很多，且编码方式不统一，方法2意味着需要查阅文献选择合适的矩阵编码方式，而且要写代码实现配套的重组和变异算子，代码量较大。
 建议用第一种方法。如果矩阵比较庞大，导致转化为线性染色体后染色体比较长，可以参考超长染色体的改进型进化算法相关文献来实现改进的EA算法模板进行求解。编程量会比第二种方法少很多。

**Comment by geatpy-dev** [comment]
@yf950919 原本要设计的矩阵的每个元素的范围是多少，那么将矩阵展开变成向量之后每一位的取值范围就对应地设置多少。种群在迭代时，根据具体调用的算法来进行交叉变异，也就是说不用管底层的具体实现，只要保证数据结构符合工具箱的设定就OK了。相见Geatpy数据结构[http://geatpy.com/index.php/2019/07/28/2-geatpy%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84/](url)

**Comment by aenron** [comment]
你好，请问当变量为矩阵，且相互存在约束关系时，该如何处理？如下，R、x均为决策变量。
$R_i-x_{i+1}-R_{i+1}=0$          
以及当约束中存在变量累加求和该如何处理
