### ISSUE TITLE
对LSGO（大规模全局优化问题）是否有较好的解决方法

### ISSUE THREAD

**Issue by CodingLittlePig** [geatpy-dev/geatpy#79]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 1061655504** [comment]
@CodingLittlePig 目前工具箱里面只提供了一些经典的进化算法的模板，它们均无法很好地应对LSGO问题。需要参照相关论文来自定义进化算法模板求解。
