### ISSUE TITLE
Run quickstart_demo.py show error message under geatpy 1.1.5 python 3.7

### ISSUE THREAD

**Issue by Zonter-tw** [geatpy-dev/geatpy#8]
Under geatpy 1.1.5 python 3.7 run quickstart_demo.py show error :
AttributeError: module 'geatpy' has no attribute 'crtfld'
Under spider to run line by line OK.
Why?

**Comment by geatpy-dev** [comment]
> Under geatpy 1.1.5 python 3.7 run quickstart_demo.py show error :
> AttributeError: module 'geatpy' has no attribute 'crtfld'
> Under spider to run line by line OK.
> W

> Under geatpy 1.1.5 python 3.7 run quickstart_demo.py show error :
> AttributeError: module 'geatpy' has no attribute 'crtfld'
> Under spider to run line by line OK.
> Why?

There are two different pythons in your computer. One is on the anaconda, the other is python3.7. You just installed geatpy on anaconda's python, so that ou have to install geatpy on the python3.7 if you want to run the toolbox on it.
