### ISSUE TITLE
怎么自己添加群智能算法呢？

### ISSUE THREAD

**Issue by jiaobendaye** [geatpy-dev/geatpy#80]
由于要用布谷鸟算法和多目标优化相结合，想把默认的GE算法，替换成CS算法，
自己实现相同的接口，应该怎样实现呢？
感谢你们的开发工作

**Comment by Haofenger** [comment]
> 由于要用布谷鸟算法和多目标优化相结合，想把默认的GE算法，替换成CS算法，
> 自己实现相同的接口，应该怎样实现呢？
> 感谢你们的开发工作

在QQ群：Evolutionary Computation（399652146）里面有人做过类似的，他/她在Geatpy里面实现了PSO算法，布谷鸟算法应该也有异曲同工之妙，您可以加群问一下~

**Comment by jiaobendaye** [comment]
> > 由于要用布谷鸟算法和多目标优化相结合，想把默认的GE算法，替换成CS算法，
> > 自己实现相同的接口，应该怎样实现呢？
> > 感谢你们的开发工作
> 
> 在QQ群：Evolutionary Computation（399652146）里面有人做过类似的，他/她在Geatpy里面实现了PSO算法，布谷鸟算法应该也有异曲同工之妙，您可以加群问一下~

已经加了，麻烦同意一下

**Comment by geatpy-dev** [comment]
据悉该问题已经得到解决，我这里就把它关闭啦~

**Comment by Elaine-LM** [comment]
您好，我想请问一下您的问题后来是怎么在geatpy中添加布谷鸟算法的。我也需要做一个混合遗传算法。
