### ISSUE TITLE
是否可以将生成的决策变量对应到设计的0-1变量里面

### ISSUE THREAD

**Issue by yf950919** [geatpy-dev/geatpy#81]
我定义了整数型的决策变量，随后做了判断，将决策变量对应到0-1变量中去，因为设置了种群数量为500，所以将每一个0-1变量也复制了500次，但是在求解过程中，出现了以下错误，不知道是什么原因？
![image](https://user-images.githubusercontent.com/54619154/72221281-1a3f2800-3594-11ea-865b-3c0a1ef15a59.png)
![image](https://user-images.githubusercontent.com/54619154/72221310-55415b80-3594-11ea-9e65-1e80208aeeb6.png)

**Comment by yf950919** [comment]
是赋值，不是复制

**Comment by 1061655504** [comment]
@yf950919 在line 89上一行加入一行语句：
print(self.problem.maxormins * population.ObjV)
看看是否会抛出同样的异常。估计是你算出的ObjV不符合框架设定的数据结构。

**Comment by yf950919** [comment]
@1061655504 现在报错显示维度不同
![image](https://user-images.githubusercontent.com/54619154/72233413-2366de00-3602-11ea-8ecb-13cf50dd39a4.png)
因为我的决策变量并未直接参与计算，而是将决策变量转化为0-1变量之后再进行的，所以赋值过程是先用列表算的，然后再转换为矩阵运算，这样可行吗？
![image](https://user-images.githubusercontent.com/54619154/72233523-d33c4b80-3602-11ea-828b-ae9dafdbbb0b.png)

**Comment by 1061655504** [comment]
@yf950919 不能用numpy的mat类型矩阵，要把np.mat改成np.array。Geatpy设定的矩阵类型都是numpy array类型，和matrix类型不能混合使用的。

**Comment by yf950919** [comment]
好的，谢谢



---原始邮件---
发件人: "Jazz_bin"<notifications@github.com&gt;
发送时间: 2020年1月13日(周一) 下午2:04
收件人: "geatpy-dev/geatpy"<geatpy@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"yf950919"<851378084@qq.com&gt;;
主题: Re: [geatpy-dev/geatpy] 是否可以将生成的决策变量对应到设计的0-1变量里面 (#81)



@yf950919 不能用numpy的mat类型矩阵，要把np.mat改成np.array。Geatpy设定的矩阵类型都是numpy array类型，和matrix类型不能混合使用的。
