### ISSUE TITLE
AttributeError: 'MyProblem' object has no attribute 'getBest'

### ISSUE THREAD

**Issue by yf950919** [geatpy-dev/geatpy#82]
![image](https://user-images.githubusercontent.com/54619154/72351180-d296d880-371a-11ea-8312-f0d91257b978.png)
程序可以运行但是在求真实前沿时显示Myproblem没有变量getBest，这是为什么？

**Comment by geatpy-dev** [comment]
@yf950919 你应该是更新到了v2.3.0，最新版里面把getBest()更名成getReferObjV()了。详见[http://geatpy.com/index.php/geatpy2-v2-3-0%e6%9b%b4%e6%96%b0%e5%85%ac%e5%91%8a/](url)

**Comment by yf950919** [comment]
好的



---Original---
