### ISSUE TITLE
在原有基础上进行种群初始化，优化原有数据

### ISSUE THREAD

**Issue by MacsYan** [geatpy-dev/geatpy#83]
**Is your feature request related to a problem? Please describe.**
种群的初始化过程，能不能在原有数据上加上随机扰动，对随机扰动进行编码和迭代。
这样能够利用原有数据和专业领域的知识，提高程序程序的运行效率
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by geatpy-dev** [comment]
@MacsYan 您可以在初始化种群染色体后调用种群类的setChrom()函数来把已有的染色体经验数据(比如记作Chrom1)插入到种群中。在插入之前，可以调用变异算子对Chrom1进行随机扰动，然后再插入。这样种群就会附带上原有的经验数据。

**Comment by MacsYan** [comment]
非常感谢您的回复。
我按照您说的来尝试一下。
我还有个问题，我计算部分不是数学函数；是一个物理模型，是要优化其中部分参数。
现在难以直接进行向量化计算。
有能加速计算的方法吗？

**Comment by geatpy-dev** [comment]
@MacsYan 可以并发、并行或者利用第三方分布式框架例如SCOOP等进行这部分的计算。[https://github.com/geatpy-dev/geatpy/tree/master/geatpy/demo/soea_demo/soea_demo6](url) 这个例子给出了用多线程并发加速，不过加速效果一般。用多核并行就效果会好很多不过代码比较复杂。这一块你可以添加一下QQ1061655504他会给你提供详细的帮助。

**Comment by MacsYan** [comment]
好的，非常感谢。接下来要在优化方面多做工作，一定好好利用geatpy这个工具。

**Comment by geatpy-dev** [comment]
> 好的，非常感谢。接下来要在优化方面多做工作，一定好好利用geatpy这个工具。

不客气~~您的肯定是我们前进的持久动力！祝学习工作生活愉快！
