### ISSUE TITLE
Add an option to enable/disable using C implementation of lower-level functions

### ISSUE THREAD

**Issue by JackieNgF** [geatpy-dev/geatpy#84]
感觉geatpy比deap用得更省心。不过geatpy要是有选项决定是否开启C源代码产生的动态链接库或者直接就用等效的python代码就好了。

**Comment by geatpy-dev** [comment]
@JackieNgF 非常感谢您的关注与支持以及提出的宝贵建议~！底层采用C是为了让框架跑得更快噢，很多python框架也是采用了这种机制的噢，比如sklearn、tensorflow等等，耗时大的核心部分都是用了C，并为不同的环境编译出能够与之兼容的版本。您是出于什么需求而需要用到纯python的版本呢？

**Comment by JackieNgF** [comment]
> @JackieNgF 非常感谢您的关注与支持以及提出的宝贵建议~！底层采用C是为了让框架跑得更快噢，很多python框架也是采用了这种机制的噢，比如sklearn、tensorflow等等，耗时大的核心部分都是用了C，并为不同的环境编译出能够与之兼容的版本。您是出于什么需求而需要用到纯python的版本呢？

有些环境下读取动态链接库受限制。

**Comment by geatpy-dev** [comment]
@JackieNgF 下载安装的时候会针对不同的环境安装对应版本的动态链接库的噢，只要按照[安装教程](http://geatpy.com/index.php/install/)的方法：执行pip install geatpy后如果安装过程没有报错那就是安装成功就能正常使用的了。
