### ISSUE TITLE
如何修改染色体的变异概率等参数？

### ISSUE THREAD

**Issue by yf950919** [geatpy-dev/geatpy#86]
在遗传算法框架的上可以通过添加某些参数实现吗？

**Comment by geatpy-dev** [comment]
@yf950919 您好！您这个标题和正文描述的不一致，您是要问什么问题呢？如果是修改变异概率，那就在调用变异算子的时候传入想要的变异概率就可以了~

**Comment by yf950919** [comment]
![image](https://user-images.githubusercontent.com/54619154/74010379-4f3a7100-49c0-11ea-8816-54a204c3caa4.png)
是在这里添加吗，可以举个例子吗

**Comment by geatpy-dev** [comment]
@yf950919 您好~在这个地方添加代码来修改：
![image](https://user-images.githubusercontent.com/42562919/74010904-878e7f00-49c1-11ea-97ac-9e2c10ace5d1.png)

**Comment by yf950919** [comment]
好的，谢谢

**Comment by geatpy-dev** [comment]
不客气~如果还有问题可以继续提出来噢~
