### ISSUE TITLE
决策变量类型

### ISSUE THREAD

**Issue by zjx2020** [geatpy-dev/geatpy#87]
设置决策变量时只能设置连续或离散型，但我现在其中一个变量只能取整数，应该怎么做

**Comment by 1061655504** [comment]
@zjx2020  您好呀！一直是可以设置决策变量为混合实数整数的呀～例如有3个变量，第二个想设为整数，其余设为实数，那么就在自定义的问题类里面设置varTypes = [0,1,0]

**Comment by zjx2020** [comment]
不行额吗，我设置为1了，他还是给我返回
ValueError: beta must a an integer

**Comment by 1061655504** [comment]
@zjx2020 您可以添加一下QQ 1061655504，将会有工作人员远程协助您解决问题。

**Comment by 1061655504** [comment]
已顺利解决~
