### ISSUE TITLE
是否支持自定义初始化种群？

### ISSUE THREAD

**Issue by tools-only** [geatpy-dev/geatpy#88]
例如，初始化阶段给定了用户的自定义表现型Phen，如何能够逆向得到Chrom？

**Comment by 1061655504** [comment]
@tools-only 方法1：在实例化算法模板对象之前，把种群对象的Chrom属性修改为自己初始化号的染色体矩阵。方法2：修改Population.py里面的initChrom()函数。把里面调用初始化种群的函数替换为自己写的代码就好了。方法3：另外可以通过继承种群类把initChrom()函数给覆盖为自己写的初始化种群染色体函数。方法4：把自己初始化了染色体的种群对象作为先验知识传入算法模板对象的run()函数。
