### ISSUE TITLE
是否可以在aimFunc中调用自己写的一个函数来得到目标函数值

### ISSUE THREAD

**Issue by SARAS3008** [geatpy-dev/geatpy#89]
由于目标函数较为复杂，我自己写了一个函数，在aimFunc中调用。单独测试该函数是可运行的，在调用之后，总是报错。
报错位置为诸多for循环控制位置： 
` for i in range(A+1,34):`  
报错信息：
“only integer scalar arrays can be converted to a scalar index”
请问这个是怎么回事，是程序本身，还是不可以这样使用呢？感谢

**Comment by geatpy-dev** [comment]
@SARAS3008 python当然可以在函数里面调用另外一个自己写的函数。你这个报错是因为A不是个整数，与工具箱无关。这个aimFunc是自定义的python函数，python支持什么就能做什么。

**Comment by SARAS3008** [comment]
谢谢你们，小哥哥已经帮我把问题解决了。

**Comment by geatpy-dev** [comment]
@SARAS3008 好的，那我这边把问题close掉了。如果后面还有问题可以重新打开。
