### ISSUE TITLE
我是在linux下直接pip installgeatpy的，在运行demmo的时候总会没有名为awGA的mudule，是我安装的问题还是这个只适用于windows啊

### ISSUE THREAD

**Issue by nov058** [geatpy-dev/geatpy#9]

**Comment by 1061655504** [comment]
> _No description provided._

您好，网上发行的是Windows版本。需要Linux版本的可发邮件到：1061655504@qq.com 以获取噢。

**Comment by nov058** [comment]
你好，我给你发了邮件了，我的邮箱是734952381@qq.com，就是发给你的邮箱，有时间的话麻烦尽快，万分感谢！

**Comment by nov058** [comment]
你好，我给你发了邮件了，我的邮箱是[734952381@qq.com]，就是发给你的邮箱，有时间的话麻烦尽快，万分感谢！

**Comment by 1061655504** [comment]
> 你好，我给你发了邮件了，我的邮箱是[ [734952381@qq.com](mailto:734952381@qq.com) ]，就是发给你的邮箱，有时间的话麻烦尽快，万分感谢！

OK了~请查收。

**Comment by donydex** [comment]
> > 你好，我给你发了邮件了，我的邮箱是[ [734952381@qq.com](mailto:734952381@qq.com) ]，就是发给你的邮箱，有时间的话麻烦尽快，万分感谢！
> 
> OK了~请查收。

能否也发我一份，我的邮箱是[2508090629@qq.com]谢谢

**Comment by ustcmashuai** [comment]
为什么我在Windows下运行demo1 也出现了这个问题：ImportError: cannot import name 'awGA' from 'awGA' (unknown location)？

**Comment by 1061655504** [comment]
> 为什么我在Windows下运行demo1 也出现了这个问题：ImportError: cannot import name 'awGA' from 'awGA' (unknown location)？

您的是windows 64位的Python3.5, 3.6, 3.7吗？目前只编译了这3个版本。

**Comment by ustcmashuai** [comment]
python 3.7.3 ,32位的。

**Comment by AcceleratorCheney** [comment]
麻烦也发我一份，万分感谢，cheneyjx@qq.com
