### ISSUE TITLE
是否支持可变上下界

### ISSUE THREAD

**Issue by ImLaoBJie** [geatpy-dev/geatpy#90]
比方说2个决策变量，x1和x2,
x1的上下界为[1,10]
那么x2的上下界能否为[x1, 10]
类似这样

**Comment by ImLaoBJie** [comment]
我看了一下代码，是不是修改ea.Population类中的initChro()方法就行了，理论上这样做是不是不用ea.crtfld都行，谢谢

**Comment by geatpy-dev** [comment]
@ImLaoBJie 您好~ 修改initChrom()只能够让初始的染色体满足可变上下界，在后面进化之后又会变回不可变的上下界的了（因为种群的区域描述器是固定上下界的）。可变上下界的问题是一类有效地可化归为经典的固定上下界的问题，加一些不等式约束来限制这些变量的值就好啦。

**Comment by ImLaoBJie** [comment]
非常感谢，再麻烦一下，现在我遇到的这个情况是关于VRP问题里的一个约束：
![image](https://user-images.githubusercontent.com/48209234/76165740-6e314c00-6194-11ea-8b62-92369f80d216.png)
就是某个经过某个顾客车辆上货物的变化值应该小于或者等于这个顾客的需求量，如果用f_{ij}强行构造出决策变量的话，搜索空间会很大，而且经常会出现所有个体都不满足约束的情况，想请教有没有比较好的处理方法

**Comment by ImLaoBJie** [comment]
谢谢， 问题已解决
