### ISSUE TITLE
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by uQaing** [geatpy-dev/geatpy#92]
I get an error when I run the main.py of Geatpy 2.40  on my MacBook pro. 

 ea.Problem.__init__(self, name, M, maxormins, Dim, varTypes, lb, ub, lbin, ubin)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by geatpy-dev** [comment]
@uQaing  Hello!  You can add QQ: 1061655504,  the assistant will help you address the problem online.

**Comment by geatpy-dev** [comment]
I heard that the problem had been handled. Cheers for that.
