### ISSUE TITLE
是否可以加入功能：循环尝试可行染色体并去除重复值

### ISSUE THREAD

**Issue by c6ishere** [geatpy-dev/geatpy#93]
**类似issue#47，但循环尝试可行染色体起作用位置不同，希望达到的效果不同**

issue#47 中，开发者给出了一种循环尝试初始化可行染色体的方法，在此基础上，我增加了部分代码，在初始化过程中去除离散变量重复的问题，使得初始解都可行且离散决策变量取值不重复。

实际运行中，经过几代进化之后，解集集中在某几个离散决策变量，导致解集种群多样性不够。

我的问题是，有没有方法在moea算法中增加离散变量的多样性，比如通过：

1. 在插入生成新一代种群位置复用初始化种群产生方法，但我不太清楚在哪里加，是否会有其他问题？geatpy中好像有去除重复染色体的功能，但由于我的变量为离散连续混合，只需要对离散部分去重。是否可以在此基础上改进，大概在哪里改动呢？

2. 单独为离散变量设置杂交变异参数，从而保持初始化染色体离散部分的多样性，这一个在哪里设置呢？

3. 因为这个要求高度定制化，有无自己创建算法模板的同学可以相互交流一下啊？

感谢geatpy团队的工作！！

**附上初始化寻找可行且离散变量去重代码**
```#创建区域描述器，这里需要创建两个，
#变量a，b，c，d，e，f，g，都是用RI实数整数混合编码
Encoding = 'RI'
Field = ea.crtfld(Encoding, problem.varTypes, problem.ranges,
                    problem.borders)  #创建区域描述器
population = ea.Population(Encoding, Field,
                            NIND)  #实例化种群对象（此时种群还没被初始化，仅仅是完成种群对象的实例化）
for i in range(100): 
    tempPop = ea.Population(Encoding, Field, NIND) 
    tempPop.initChrom(NIND) # 初始化种群染色体矩阵 
    problem.CVFunc_pre(tempPop) # 判断初始化种群的可行性，CVFunc_pre定义在Myproblem.py中 
    feasible = np.where(np.all(tempPop.CV <= 0, 1))[0] # 找到可行个体
    discrete_cols = np.where(problem.varTypes == 1) # 离散取值的那些列
    print('当前i：',i)
    if len(feasible) > 0: 
        print('找到可行解，当前i为：',i)
        if i == 0 or population.Chrom is None: 
            temp_feasible = tempPop[feasible]
            first_duplicate = temp_feasible.Phen[:,discrete_cols] # 分离离散取值所在列，准备去重
            # a接收去重结果，rows_index接收行索引，return_index=True输出索引，axis=0对行去重 
            a,rows_index = np.unique(first_duplicate, return_index=True, axis= 0)
            # 重新索引得到去重后的population
            population = temp_feasible[rows_index]
            # print('现在可行解：', population.Phen)
        else:
            # 第一次去重，合并
            temp_feasible = tempPop[feasible] 
            first_duplicate = temp_feasible.Phen[:,discrete_cols]
            a,rows_index = np.unique(first_duplicate, return_index=True, axis= 0)
            population = population + temp_feasible[rows_index]
            # print('现在可行解：', population.Phen)
            if population.sizes >= NIND:
                # print('展示去重后的解集：', population.Phen)
                # print('退出寻找可行解，当前总数量：',population.sizes)
                break
if population.Chrom is not None: 
    population = population[:NIND] # 取前NIND个
print('截取后，总数量：',population.sizes)
```

**Comment by sc1101** [comment]
朋友你是不是用：“从父子两代中选择个体的环境选择”方法？这种环境选择方式经常会造成大量重复解。以下几篇文献有相关的改进：
http://qikan.cqvip.com/Qikan/Article/Detail?id=40184439[http://qikan.cqvip.com/Qikan/Article/Detail?id=40184439](url)
[http://xueshu.baidu.com/usercenter/paper/show?paperid=0048ec3126d5e02362fbcd05b863ab8c&site=xueshu_se](url)

**Comment by geatpy-dev** [comment]
@c6ishere 您好！

问题1的去重方法：在选择个体生成新一代种群处使用以下方法去重：
[ans, uniIndex] = np.unique(population.Chrom,axis = 0, return_index=True)，返回的“uniIndex”将会是种群中染色体不重复的个体的索引。

对于问题2：问题等同于要对染色体局部进行加强的变异，则需要把染色体这部分取出来，单独调用合适的变异算子。

对于问题3，我赞同上面网友的做法，NSGA2、NSGA3等采用父子两代合并选择生成新一代个体的方法在某些场合很容易会造成大量重复个体。一个缓解方法是调节重组、变异算子的参数等，例如加大变异概率，以防变异得到的个体有很多性状与父代重复。

希望以上回复可以帮到您~

**Comment by c6ishere** [comment]
谢谢 @sc1101 @geatpy-dev 你们提供的思路！很受启发！

**Comment by Elaine-LM** [comment]
> **类似issue#47，但循环尝试可行染色体起作用位置不同，希望达到的效果不同**
> 
> issue#47 中，开发者给出了一种循环尝试初始化可行染色体的方法，在此基础上，我增加了部分代码，在初始化过程中去除离散变量重复的问题，使得初始解都可行且离散决策变量取值不重复。
> 
> 实际运行中，经过几代进化之后，解集集中在某几个离散决策变量，导致解集种群多样性不够。
> 
> 我的问题是，有没有方法在moea算法中增加离散变量的多样性，比如通过：
> 
> 1. 在插入生成新一代种群位置复用初始化种群产生方法，但我不太清楚在哪里加，是否会有其他问题？geatpy中好像有去除重复染色体的功能，但由于我的变量为离散连续混合，只需要对离散部分去重。是否可以在此基础上改进，大概在哪里改动呢？
> 2. 单独为离散变量设置杂交变异参数，从而保持初始化染色体离散部分的多样性，这一个在哪里设置呢？
> 3. 因为这个要求高度定制化，有无自己创建算法模板的同学可以相互交流一下啊？
> 
> 感谢geatpy团队的工作！！
> 
> **附上初始化寻找可行且离散变量去重代码**
> 
> ```
> #变量a，b，c，d，e，f，g，都是用RI实数整数混合编码
> Encoding = 'RI'
> Field = ea.crtfld(Encoding, problem.varTypes, problem.ranges,
>                     problem.borders)  #创建区域描述器
> population = ea.Population(Encoding, Field,
>                             NIND)  #实例化种群对象（此时种群还没被初始化，仅仅是完成种群对象的实例化）
> for i in range(100): 
>     tempPop = ea.Population(Encoding, Field, NIND) 
>     tempPop.initChrom(NIND) # 初始化种群染色体矩阵 
>     problem.CVFunc_pre(tempPop) # 判断初始化种群的可行性，CVFunc_pre定义在Myproblem.py中 
>     feasible = np.where(np.all(tempPop.CV <= 0, 1))[0] # 找到可行个体
>     discrete_cols = np.where(problem.varTypes == 1) # 离散取值的那些列
>     print('当前i：',i)
>     if len(feasible) > 0: 
>         print('找到可行解，当前i为：',i)
>         if i == 0 or population.Chrom is None: 
>             temp_feasible = tempPop[feasible]
>             first_duplicate = temp_feasible.Phen[:,discrete_cols] # 分离离散取值所在列，准备去重
>             # a接收去重结果，rows_index接收行索引，return_index=True输出索引，axis=0对行去重 
>             a,rows_index = np.unique(first_duplicate, return_index=True, axis= 0)
>             # 重新索引得到去重后的population
>             population = temp_feasible[rows_index]
>             # print('现在可行解：', population.Phen)
>         else:
>             # 第一次去重，合并
>             temp_feasible = tempPop[feasible] 
>             first_duplicate = temp_feasible.Phen[:,discrete_cols]
>             a,rows_index = np.unique(first_duplicate, return_index=True, axis= 0)
>             population = population + temp_feasible[rows_index]
>             # print('现在可行解：', population.Phen)
>             if population.sizes >= NIND:
>                 # print('展示去重后的解集：', population.Phen)
>                 # print('退出寻找可行解，当前总数量：',population.sizes)
>                 break
> if population.Chrom is not None: 
>     population = population[:NIND] # 取前NIND个
> print('截取后，总数量：',population.sizes)
> ```
![image](https://user-images.githubusercontent.com/77914331/105624982-efeba000-5e60-11eb-9c6c-ed64f7abfd4e.png)，您好，请问产生初始可行染色体时，提示“种群染色体矩阵未初始化”这个错误，请问有什么办法解决
