### ISSUE TITLE
ea.scaling线性变换内部将目标函数值转适应度的原理大致是什么样的

### ISSUE THREAD

**Issue by fcx-Mars** [geatpy-dev/geatpy#94]
进行单目标优化时，每一代都会将目标函数值转换成适应度，想了解一下变换的原理

**Comment by geatpy-dev** [comment]
@fcx-Mars 可以用help()查看到算法描述及参考文献，更详细的算法细节在对应的参考文献《Genetic Algorithms in Search, Optimization and Machine Learning》的76页，大致如下图：
![image](https://user-images.githubusercontent.com/42562919/78418450-bdbd4780-766e-11ea-9b0d-87871378979d.png)
![image](https://user-images.githubusercontent.com/42562919/78418454-c9a90980-766e-11ea-89ed-380aba2b4563.png)
![image](https://user-images.githubusercontent.com/42562919/78418459-d0378100-766e-11ea-8c28-982766df9924.png)

**Comment by geatpy-dev** [comment]
后续如果还有问题可以继续发issue噢。

**Comment by Tzera** [comment]
老哥，这里搞懂了吗，适应度函数是怎么把CV矩阵加进去的？

**Comment by weiweiisok** [comment]
> 老哥，这里搞懂了吗，适应度函数是怎么把CV矩阵加进去的？

请问你搞懂了吗，这是如何将CV矩阵加入到适应度计算的
