### ISSUE TITLE
您好,我在测试一个双决策变量单目标函数时遇到一些问题.

### ISSUE THREAD

**Issue by 13483332422** [geatpy-dev/geatpy#97]
求解
min f(x) = e^x*(4*x^2 + 2*y^2+ 4*x*y+2*y+1)
s.t.
1.5+xy-x-y<=0
-xy<=10
x y 无其他约束条件
两个自变量
__________________________
其中需要修改的几处我已经改为:
Dim=2
M = 1  # 初始化M（目标维数）
lb = [float("-inf")] * Dim  # 决策变量下界
 ub = [float("inf")] * Dim  # 决策变量上界

________________________________________
 def aimFunc(self, pop):  # 目标函数
        Vars = pop.Phen  # 得到决策变量矩阵
        x = np.array(Vars[:, [0]])
        y = np.array(Vars[:, [1]])
        pop.ObjV = np.exp(x)*(4*x**2 + 2*y**2 + 4*x*y + 2*y + 1)
        # 利用可行性法则处理约束条件
        pop.CV = np.hstack([1.5 + x*y - x - y,
                                - x*y - 10 ])
__________________________________
主函数没有做修改,运行时报错:
error in Population: Field disagree. (两者的译码矩阵必须一致。)
____________________________________
请问如何修改

**Comment by geatpy-dev** [comment]
@13483332422 进化算法里面变量上下界均需要为实数，不能设置为无穷。

**Comment by 13483332422** [comment]
> @13483332422 进化算法里面变量上下界均需要为实数，不能设置为无穷。

对于这个题,我们只能大概写一个范围吗.

**Comment by 13483332422** [comment]
> @13483332422 进化算法里面变量上下界均需要为实数，不能设置为无穷。

刚刚更改过了范围,成功运行,感谢您.

**Comment by geatpy-dev** [comment]
> > @13483332422 进化算法里面变量上下界均需要为实数，不能设置为无穷。
> 
> 对于这个题,我们只能大概写一个范围吗.

对哒~进化算法里面决策变量空间是要有限的。

**Comment by 13483332422** [comment]
> > > @13483332422 进化算法里面变量上下界均需要为实数，不能设置为无穷。
> > 
> > 
> > 对于这个题,我们只能大概写一个范围吗.
> 
> 对哒~进化算法里面决策变量空间是要有限的。

好的,感谢.
