### ISSUE TITLE
如何设置目标函数的初始值？

### ISSUE THREAD

**Issue by githublth** [geatpy-dev/geatpy#98]
我在做目标函数优化的过程中，使用了matlab的全局优化函数globalsearch函数，在给定较好初始值的情况下，能够得到比较好的结果，但使用geatpy函数时，如果不设置初值，求解不出结果， 用soea_demo2里的例子，尝试设置初值，如下：

```
init=np.array([-0.5,0.005,0.5])
init_aa=np.tile(init,(NIND,1))
population.Phen=init_aa
````
感觉并没有起到效果，请问有设置初值的例子吗？ 或者能否给一份具体的例子呢？ 谢谢了

**Comment by geatpy-dev** [comment]
@githublth 您好！Phen是会在Population.py中的decoding()函数里面随染色体矩阵Chrom而变化的，因为Phen是表现型矩阵，Chrom是染色体矩阵。表现型由染色体解码得到。因此您应该设置Chrom的初始值，而不是设置Phen的初始值。在main.py中调用算法对象的run()方法前面，添加代码myAlgorithm.population.Chrom = ... 即可。

**Comment by githublth** [comment]
![image](https://user-images.githubusercontent.com/25904480/79117254-38980800-7dbd-11ea-8250-b7a8f13e9ecb.png)
像上图所示那样设置吗？  这样的话，很容易报：No feasible solution. (有效进化代数为0，没找到可行解。)， 有时迭代一次就结束了，。请问是什么原因呢？

**Comment by geatpy-dev** [comment]
@githublth 你那句np.tile让后面种群的多样性大大降低了。你可以调用ea.crtrp来初始化染色体Chrom，然后对Chrom的第一行赋值。

**Comment by geatpy-dev** [comment]
已添加[soea_demo10](https://github.com/geatpy-dev/geatpy/tree/master/geatpy/demo/soea_demo/soea_demo10)，里面有展示如何使用先验知识辅助进化优化~

**Comment by geatpy-dev** [comment]
该问题已达最长期限，欢迎后续继续发issue提问噢！
