### ISSUE TITLE
如何在种群初始化的时候就令其满足某些约束条件?

### ISSUE THREAD

**Issue by itrrti** [geatpy-dev/geatpy#99]
比如，我有一个离散变量u，他的维度是1x10
我有一个约束条件，必须**至少连续三个1**和**至少连续三个0**
我不作任何处理，将这条约束添加到pop.CV中，求解效果很差
我想可能是因为无效的种群太多了？
比如，这样的种群是符合条件的，假设种群数为1
[1,1,1,1,0,0,0,1,1,1]
[1,1,1,0,0,0,0,0,0,0]
[1,1,1,1,1,1,0,0,0,0]
这样的种群就是不符合条件的
[1,0,1,0,1,0,1,0,1,0]
[0,1,1,0,0,1,0,1,1,0]

**Comment by geatpy-dev** [comment]
@itaoxiaoran 这种可以用间接编码的方法来扩大可行域的大小。比如试一下这样编码：把[1,1,1,1,0,0,0,1,1,1]变成[1,4,3]。变更后染色体的第一个元素表示一开始是1还是0，第二个元素4表示连续的4个1；第三个元素3表示连续的3个0；剩下有多少个1，由10 - 4 - 3 = 3计算得到。于是[1,4,3]表示[1,1,1,1,0,0,0,1,1,1]。类似地，[0, 3, 3] 表示[0, 0, 0, 1, 1, 1, 0, 0, 0, 0]。

**Comment by itaoxiaoran** [comment]
谢谢，我想我可能没有表达清楚，我的约束是：0一旦出现就是至少连续3个，1一旦出现就是至少连续3个。
比如 [0,4,4]表示[0,0,0,0,1,1,1,1,0,0]就不能满足了
我尝试了很久，但还是不知道如何做

**Comment by geatpy-dev** [comment]
@itaoxiaoran hi! 非常抱歉漏看消息了，以致刚刚检查才发现还没回复您。我前面提供的编码思路是这样的：[0, 4, 4]表示的是[0, 0, 0, 0, 1, 1, 1, 1]，而不是[0,0,0,0,1,1,1,1,0,0]。

**Comment by geatpy-dev** [comment]
该问题已超过最长期限，特此关闭。
